### ISSUE TITLE
Survey URL card

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1011]
## Description
A user should be able to find the link to a survey easily.

## Relevant Job Stories
* When my survey is ready for responses, I want to share a link to where it can be filled out online, so that users can easily submit their responses

## Prerequisites
None

## Requirements
- [ ] There should be a smallish card on the overview page
- [ ] The card always contains a text field with the public URL for the survey
- [ ] A copy button copies the link to the clipboard
- [ ] A clickable link opens the public survey page in a new tab, at the url ``/o/${orgId}/surveys/${surveyId}`` (which will automatically be redirected by NEXT to the correct URL)
- [ ] The card has two states
- [ ] When the survey is active, display it's "active" state
  - [ ] Headline is "Open for submissions"
  - [ ] Caption is "Now accepting submissions at this link"
  - [ ] There is a green status indicator
  - [ ] The link reads "Visit survey in activist portal"
- [ ] When the survey is not active, display it's "preview" state
  - [ ] Headline is "Preview survey"
  - [ ] Caption is "Will accept submissions at this link"
  - [ ] There is a gray status indicator
  - [ ] The link reads "Preview survey in activist portal"

## Possible implementations
See `ZUICopyToClipboard` and `ZUIInlineCopyToClipboard` for code to copy text to clipboard, and consider refactoring to create something more reusable.

### Active state in situ
This task only concerns the smallish card in the top right called "Open for submissions" in the mockup below.

<img width="843" alt="image" src="https://user-images.githubusercontent.com/550212/218246837-8511feb8-91ac-4ea0-901a-f1ece25b47f1.png">

### Draft/preview state
<img width="519" alt="image" src="https://user-images.githubusercontent.com/550212/218246891-35291570-d67f-476b-8a57-a669b387f5fe.png">

## Open questions
None

**Comment by niklasva82** [comment]
Is the `app.zetkin.org/<number>` some kind of short link to a survey or is it just a part of the illustration?

**Comment by richardolsson** [comment]
> Is the `app.zetkin.org/<number>` some kind of short link to a survey or is it just a part of the illustration?

It's just an illustration. We will use the old Gen2 links for now.

**Comment by richardolsson** [comment]
This page is here (but empty at the time of writing): http://localhost:3000/organize/1/campaigns/standalone/surveys/1
