### ISSUE TITLE
Submissions list missing pieces

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1043]
## Description
There are some minor issues still in the survey submissions list.

## Relevant Job Stories
None

## Prerequisites
None

## Requirements
- [x] The "Person record" should have a different title, maybe "link"
- [x] Deal with anonymous submissions, by showing "Anonymous" in first name, last name and email column

## Possible implementations
None

## Design specifications
<img width="919" alt="bild" src="https://user-images.githubusercontent.com/346211/220312808-285e24d8-9482-4b66-8323-48b3f7312a1f.png">

## Open questions
* What to call "Person record" column?

**Comment by richardolsson** [comment]
At the meeting today we incorrectly assumed that the pane was missing, but it's actually tracked separately by #1024.

**Comment by niklasva82** [comment]
Regarding "Person record", why not simply "Person"?

**Comment by niklasva82** [comment]
Or "Respondent"

**Comment by richardolsson** [comment]
> I'm assuming there is a separate issue for the actual linking?

Yes! You can find all the related issues in EPIC #1022.
