### ISSUE TITLE
Layout breaks on Survey Overview

### ISSUE THREAD

**Issue by Bagera** [zetkin/app.zetkin.org#1125]
## Description
At times when I navigate to and always when I re-load a survey overview page, the layout is broken.
Console gives this error: "TypeError: l.app is undefined" but I think that is also shown on other working pages.

Using the browser forward and back navigation takes you back to states where everything looks ok but when you go to survey overview again the menu might have disappeared or the title or other random stuff.

This is on dev server and latest Firefox and latest Chrome

## Steps to reproduce
1. Go to [Projects page](http://app.dev.zetkin.org/organize/1/projects)
2. Click on 'Activities'
3. Click on 'testing Survey'

Re-load to see the error persist

## Screenshots

![image](https://user-images.githubusercontent.com/2950171/226912639-c65fb3b1-282f-4c0e-80b9-8c7b3db8fcfd.png)

Menu has disappeared:
![image](https://user-images.githubusercontent.com/2950171/226907345-ebf94b97-a397-4c6a-a944-6f24f80ce172.png)

No title:
![image](https://user-images.githubusercontent.com/2950171/226913312-966c6438-45af-45f1-ac5b-9d4803ea8719.png)

**Comment by richardolsson** [comment]
This has already been fixed, just not deployed to the dev server. See #1115

**Comment by richardolsson** [comment]
Great report though! It would have been perfect for reproducing the issue, had we not already fixed it. 😊
