### ISSUE TITLE
Activity list items show zero stats while loading

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1142]
## Description
While activity stats are loading, I think the item should show some sort of loading indicator instead of showing zeros, as is currently the case.

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/projects/6/activities
2. Watch how the activities load (potentially throttle your browser or use redux dev tools to see the different states)

### Expected Behaviour
First the list should appear. While the stats load, the stats should be showing some sort of a loading indicator. After the stats load, the three numbers should appear.

### Actual Behaviour
First the list appears, but with all zeroes for the stats. Then after a short while (when the stats load) the zeroes are updated with the correct numbers.

## Proposed solution
This will require refactoring in some way how the `ActivityListItem` component works, which I think is fine. Maybe add a `statsLoading` property or something?

As a loading indicator, use MUI `<CircularProgress>`

### While loading
I reproduced this state using redux dev tools to disable the `statsLoaded` action.

<img width="799" alt="image" src="https://user-images.githubusercontent.com/550212/227757302-eed61233-e735-4635-b10b-6decdd22602c.png">

### After loading
<img width="799" alt="image" src="https://user-images.githubusercontent.com/550212/227757316-7b227ee3-8425-45bf-888a-1f6748f35f1c.png">

**Comment by theo8theo8** [comment]
I'll take a look at this!
