### ISSUE TITLE
Add call assignments and surveys to search modal

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1143]
## Description
A user should be able to search for call assignments and surveys, using the same global search feature as other things, by clicking the magnifying glass at the top right of the screen and typing in the name (or other relevant identifier).

## Relevant Job Stories
* When my survey has been live for a while, I want to be able to easily find it, so that I can go look at the responses

## Prerequisites
None

## Requirements
- [ ] Add support for call assignments in search modal
- [ ] Add support for surveys in search modal

## Possible implementations
The backend is already implemented for this. Reuse the patterns for tasks, views etc. The "type" for call assignments is `callassignment" and the type for surveys is `survey`.

See `ActivityList/CallAssignmentListItem.tsx` and `ActivityList/SurveyListItem.tsx` to find primary icons and href logic for call assignments and surveys respectively.

## Design specifications
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/550212/227757627-9dcd1a1a-7abd-4ccb-b21b-36e25269d45b.png">

## Open questions
None

**Comment by Jrende** [comment]
I'm on it!
