### ISSUE TITLE
Fix 404 for avatar image

### ISSUE THREAD

**Issue by samuelskanberg** [zetkin/app.zetkin.org#115]
In the header, there is a link to the avatar image. 

In the web console we get a 404 for `http://www.dev.zetkin.org/api/users/4/avatar` when logged in with testuser@example.com

**Comment by richardolsson** [comment]
Solved by #107

**Comment by richardolsson** [comment]
My bad, the PR that actually fixes this is #116. I remembered having fixed this, but was mistaken about the PR. I had actually just pushed the branch and forgot to create a PR. 😊
