### ISSUE TITLE
Cannot select entire text of ZUIPersonSelect

### ISSUE THREAD

**Issue by niklasva82** [zetkin/app.zetkin.org#1157]
## Description
When typing to search for a person in the ZUIPersonSelect, e.g. to add new person to a view, it's not possible to hold shift and press home in order to select the entire text (in order to delete it).

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/people/views
2. Click a view
3. Search for a new person at the bottom of the screen.
4. Hold shift and press Home

### Expected Behaviour
Select entire text.

### Actual Behaviour
Go to first/last person in list.

### Screenshot
![bild](https://user-images.githubusercontent.com/14962107/228381395-2cacc2e0-57a5-4cec-b5c2-9b1f67ba51b6.png)

### Possible fix
Ignore the home/end buttons when the Shift button is pressed.

**Comment by theo8theo8** [comment]
I'm on this!
