### ISSUE TITLE
Event META 🤘 

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#1163]
This Epic deals with the basic framework of Events - page tabs, layout, model/store/repo creation and all that good stuff. 

## Definitions of key terminology
* An EVENT is an ACTIVITY that is created as part of a PROJECT.

## Target audience
These are the roles that will most likely use this feature:
* Organizers

## Requirements (job stories)
- When I’m planning events that require certain people or resources to be available, I want to make a schedule without publishing it, so that I can check the dates with the key people/resources
- When I’m planning events far in advance, I want to be able to hold off from publishing them until we get closer to the event, so that participants don’t start signing up before the event is ready
- When I create an event I want to be able to estimate the amount of attendees needed so that I don’t happen to allocate precious activist resources inefficiently 

## Solution
A basic Events page with dummy tabs and basic header! 

## Tasks
- [x] #1159 
- [x] #1160
- [x] #1161
- [x] #1162
- [x] #1182
- [x] #1237

**Comment by richardolsson** [comment]
Closing this as all tasks are done! 🎉
