### ISSUE TITLE
Event Overview tab 👀 

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#1164]
The overview tab is the place where the user defines and updates information about an event. It contains three cards: the event card, the participants card and the related events card.

## Definitions of key terminology
* an EVENT is an ACTIVITY that is part of a PROJECT

## Target audience
These are the roles that will most likely use this feature:

* Organizers

## Requirements (job stories)
Below are job stories that describe the requirements for this feature.

- When two unrelated organizations collaborate to organize an event, I want both of their names to be visible when marketing the event, so that people associated with both organizations will want to attend.
- When I create an event I want to be able to estimate the amount of attendees needed so that I don’t happen to allocate precious activist resources inefficiently 
- When I have a lot of small events coming up, such as flyering or other basic activism, I want to make sure that there is someone assigned as the contact for all the events, so that I can relax knowing that they are fully prepared
- When I’m planning an online event using Zoom or some other video conferencing service, I want the event to include the link to the meeting, so that attendees can’t miss the information about how to get into the meeting
- When I’m creating a new event, I don’t want to forget adding a type, so that later when I use Smart Search or some other indirectly related feature I will find the people who attended the event
- When I’m organizing an event that spans over a full weekend, I want to be able to set the start and end times on different days, so that there are no misconception about the duration of the event
- When I’m looking for people based on previous activity, I want to exclude everyone who attended a “Member meeting” type event, so that I can focus my search on activists and not meeting attendees
- When I’m creating an event and I know exactly the right location for it, I know the name of the location in the database and I’m not worried about the event colliding with anything else, I want to be able to quickly search and pick that location from a list, so that I don’t have to navigate a map just to find the location

## Solution
The Event overview tab!
![bild](https://user-images.githubusercontent.com/58265097/228559595-755da234-df60-4aa1-9b6f-a1a56e06c316.png)
![bild](https://user-images.githubusercontent.com/58265097/228559812-84c08000-e506-4ffd-b9a7-96cae60ee269.png)

## Tasks
- #1165 
- #1166
- #1169
- #1170
- #1171
- #1183 

![Image](https://user-images.githubusercontent.com/36491300/229172943-34cc6109-4340-4878-990e-99cb46032d5c.png)

**Comment by richardolsson** [comment]
Closing this as all the features planned for R39 have been completed. The remaining task (#1166) will be handled lated.
