### ISSUE TITLE
Image upload for Event details card - edit mode 👀 

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#1166]
## Description
A user should be able to add a custom image to their event.

## Relevant Job Stories
No particular ones

## Prerequisites
#1165 

## Requirements
- [x] Can upload file from computer
- [x] Can drag and drop file
- [x] Lists file formats that are possible + max file size
- [x] Displays image

## Possible implementations
Load locations from `/orgs/ID/locations`

## Design specifications
![bild](https://user-images.githubusercontent.com/58265097/228567819-e800d028-771f-4440-a3a3-b8079148a567.png)

![bild](https://user-images.githubusercontent.com/58265097/228567707-73447f79-105a-4fc0-9f5f-ace7a9687749.png)

**Comment by niklasva82** [comment]
Cover images for actions/events are not implemented in the API yet.
