### ISSUE TITLE
Location Modal 🌍

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#1167]
The location modal is an interface where organizers who are about to create an event, or are editing an existing event, can find a location for the event, either by picking one of the organization's existing locations from a map, or creating a new location on that map. It also provides some basic editing capabilities for locations.

## Definitions of key terminology
* An EVENT is an activity that takes place at a certain location at a certain time. Events were called "Actions" in Gen2.
* A LOCATION is a predefined geographical place where an event takes place. Users store locations in a list in Zetkin, to be reused, which allows for filtering etc.

## Target audience
These are the roles that will most likely use this feature:

* Event organizers who are adding an event to the Zetkin calendar

## Requirements (job stories)
Below are job stories that describe the requirements for this feature.

* When I’m planning a physical event, I want to specify it’s location with coordinates, title, description, address and other information, so that participants will be able to find the event
* When I select a location for an event I want to see what else is planned for this location, so that I can find the best fit for my event and avoid collisions
* When I’m adding a new event in an already very busy campaign (e.g. because so many people signed up at some timeslot, and I want to distribute them more widely), and I’m picking the location for the new event, I want to see what other locations have events happening around that time, so that I don’t direct the people to a location where we will be that day anyway
* When I’m creating an event and I want to pick a certain location that I personally refer to by some name but others may refer to by some other name, I want to be able to see nearby locations, so that I don’t create a new location with a slightly different name than one that already exists in our database
* When I need to create a new location, I want to be able to find it by searching for a nearby address, landmark etc, so that I don’t have to pan and zoom to the right location using a map

## Solution
We have designed a modal that can be opened when creating an event, and in which locations can be explored, edited and created. 

![image](https://user-images.githubusercontent.com/550212/228745056-8e1ad87c-aad2-41fa-91e0-6d766b94bd44.png)

![image](https://user-images.githubusercontent.com/550212/228745316-3c08a49c-931e-4510-9050-5c40a00649b4.png)

## Tasks
* #1172
* #1174 
* #1175
* #1176
* #1178
* #1179
* #1180

**Comment by richardolsson** [comment]
Closing this as all tasks have been completed except one, which is postponed to a future release.
