### ISSUE TITLE
Participants card on event overview 👀

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1170]
## Description
A user should be able to see a summary of the number of participants for an event, as well as the contact person.

## Relevant Job Stories
- When I create an event I want to be able to estimate the amount of attendees needed so that I don’t happen to allocate precious activist resources inefficiently 
- When I have a lot of small events coming up, such as flyering or other basic activism, I want to make sure that there is someone assigned as the contact for all the events, so that I can relax knowing that they are fully prepared

## Prerequisites
#1159 

The "cancelled" state is currently not supported by the backend. If anyone takes on this issue before this has been implemented in the API, just ignore that part for now.

## Requirements
- [ ] The top right should show the number of currently booked participants against the user defined minimum participants
  - [ ] The chip should be red if two or more people are missing
  - [ ] The chip should be yellow if one person is missing
  - [ ] The chip should be bright green there are enough attendees
  - [ ] The cogwheel next to the chip should open a small popper where the number of minimum participants can be changed
- [ ] The rows below should list pending sign-ups, booked participants and cancelled (currently not supported in the backend)
- [ ] The last row should show the contact person, or "None assigned" if there is no contact person
- [ ] At the bottom should be a link to the participants tab

## Possible implementations
Use `<ZUICard>` for the card, which should have support for all the different sections of the card.

## Design specifications
This refers to the "Participants" card on the right hand side of the overview page.

![image](https://user-images.githubusercontent.com/550212/228750233-1aaf0bb1-577e-4303-ae46-1789dd0c6e10.png)

## Open questions
None

**Comment by theo8theo8** [comment]
I'll work on this :)
