### ISSUE TITLE
Implement Location Dropdown in Event Overview Card 👀 

### ISSUE THREAD

**Issue by rebecarubio** [zetkin/app.zetkin.org#1183]
## Description
A user should be able to select a Location from the Event Details Card

## Relevant Job Stories
- When I’m creating an event and I know exactly the right location for it, I know the name of the location in the database and I’m not worried about the event colliding with anything else, I want to be able to quickly search and pick that location from a list, so that I don’t have to navigate a map just to find the location

## Prerequisites
Don´t start until #1169 is done

## Requirements
- [ ] The location dropdown shows the available locations
- [ ] The location selection have a defined state for preview and another for edit

## Possible implementations
`Autocomplete/Dropdown `material ui 

## Design specifications
Preview state
![image](https://user-images.githubusercontent.com/36491300/229171896-3d6e76af-6458-483f-a779-cc075f2bd3e4.png)

Edit state
![image](https://user-images.githubusercontent.com/36491300/229172038-56c18bc5-f901-4f7c-b943-ccf7dcf3961b.png)

![image](https://user-images.githubusercontent.com/36491300/229172106-7c19c74a-8c3e-4961-a8f5-fbb1676bd344.png)

**Comment by richardolsson** [comment]
This was solved by #1185.
