### ISSUE TITLE
🌍 "Create new location" always an option when selecting location

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#1198]
## Description
A user should be able to easily open the location modal to add a new location.

## Prerequisites
#1172 done and merged

## Requirements
- [ ] "Create new location" is always an option in the `Autoselect` for selecting location on the `EventOverviewCard`.
- [ ] Has `Add` icon (+) in the beginning
- [ ] Clicking on this option should open the location modal 

### The card
![image](https://user-images.githubusercontent.com/550212/230549279-be0170f5-3e84-4ee9-b0fa-2047ceb2068d.png)

### Dropdown
The image below is a screenshot from the location modal, where a similar option has been designed. This issue however deals with the `EventOverviewCard` as pictured above.

![bild](https://user-images.githubusercontent.com/58265097/230104723-b41310a9-587e-4dea-93d8-e42897a80ae5.png)

**Comment by richardolsson** [comment]
This is one page where this interface exists: http://localhost:3000/organize/1/projects/1/events/1

**Comment by GustavAndreasson** [comment]
I'll do this!
