### ISSUE TITLE
Events, surveys and call assignments can be accessed through any project

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1200]
## Description
The direct URLs for a survey, call assignment or event includes the ID of a project (or `standalone`), but because of the way the Zetkin API works, no project ID is actually required. This leads to the NEXT backend not really caring about the project ID, which means a call assignment, survey or event can be found regardless of whether the project ID is correct or not.

**NOTE**: In the API, the term "project" does not exist. What we now call projects used to be called campaigns, and is still referred to as such in the API.

## Steps to reproduce
1. Go to each of the following URLs (bug exists on all)
  a. http://localhost:3000/organize/1/projects/999/surveys/1
  b. http://localhost:3000/organize/1/projects/999/callassignments/1
  c. http://localhost:3000/organize/1/projects/999/events/1

### Expected Behaviour
Should show a 404 page (because survey 1 is not part of project 999, which in fact doesn't exist)

### Actual Behaviour
Shows the survey/call assignment/event page without any errors.

## Screenshots
<img width="1483" alt="image" src="https://user-images.githubusercontent.com/550212/230543219-f84a84e9-b633-47b6-9d82-b02d5944861d.png">

## Proposed solution
Here's a suggestion for a solution. Others may exist, so feel free to explore!

The surveys, events and call assignments data objects all have a `campaign` property, that can be `null`. If it exists, the `campId` in the URL should be `data.campaign.id`, and if `data.campaign == null`, then `campId` should be `standalone`.

It should be possible to create an API client in the `getServerSideProps()` of each of the above routes, retrieve the necessary data, and check that the campaign matches.

```tsx
const client = new BackendApiClient(ctx.req.headers);
const data = await client.get(`/api/orgs/${orgId}/surveys/${surveyId}`)
// TODO: Check data.campaign before proceeding.
```

**Comment by danbjork** [comment]
Hey! I'm working on this ticket as of today's hackathon 7th April
