### ISSUE TITLE
Bad redirect after deleting a view

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1201]
## Description
A "View" is a dynamic list/table of people which is the main way to access the people database in Zetkin. When a view is deleted from within it's own page, Zetkin should redirect to the list of views, but doesn't.

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/people
2. Click on "Create view" in top right, which will create and navigate to a new view
3. On the new view, click the "ellipsis menu" (⋮) in the top right
4. Click "Delete view"
5. Click "Confirm"

### Expected Behaviour
View should be deleted, and user redirected to /organize/1/people (or whatever organization they're working in).

### Actual Behaviour
View is deleted, but user is redirected to /organize/1/people/views, which is interpreted as a profile page of a person that does not exist.

## Screenshots
<img width="1483" alt="image" src="https://user-images.githubusercontent.com/550212/230544347-ba6946b3-b313-4817-ac30-dcc23803435a.png">

**Comment by KraftKatten** [comment]
I'll work on this 🙌
