### ISSUE TITLE
Display full path of folders in breadcrumbs for view

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1202]
## Description
A user should be able to see the full path of folders in the breadcrumbs when on the view page, not just the "People" (root folder) page. This is working for folders (i.e. when in a subfolder, you can see the parent folders in the breadcrumbs) but as soon as you navigate to a view the breadcrumbs "reset" to just displaying "People"

## Steps to reproduce
1. Go to http://app.dev.zetkin.org/organize/1/people/folders/8
2. Note the breadcrumbs (screenshot A below)
3. Click "My view in folder"

### Expected Behaviour
Breadcrumbs should include the folders, so that user can navigate back to the folder that contains the view, or to one of it's ancestors.

In this case, the full path of the breadcrumbs should be:

* Organize
* My organization
* People
* My folder
* My subfolder
* My view in a folder

### Actual Behaviour
On the view page, the name of the view is displayed directly after "People", which is the root of the view folder structure.

### A. Folder page (working)
<img width="771" alt="image" src="https://user-images.githubusercontent.com/550212/230545874-d8ee5b55-8108-4d02-a4b5-5938e886b1be.png">

### B. View page (not displaying folders)
<img width="770" alt="image" src="https://user-images.githubusercontent.com/550212/230545927-970a309b-f65a-4f3a-a83d-512433f2d9ac.png">

## Proposed solution
The breadcrumbs work by making an API request to `/api/breadcrumbs` (src/pages/api/breadcrumbs.ts`). It already handles this for when displaying a folder, through a special case in `fetchElements()`.  Maybe extend it somehow to also handle views?

**Comment by awarn** [comment]
I'll try my hand at this one.
