### ISSUE TITLE
Can't open view of blocked targets in new tab

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1203]
## Description
A user should be able to click a link on a call assignment page, and be directed to a view containing all the people who are blocked from calling for some reason. This is currently possible, but not in a way that allows the user to cmd/ctrl+click the link to open it in a new browser window/tab.

## Steps to reproduce
1. Go to some call assignment, e.g. http://localhost:3000/organize/7/projects/standalone/callassignments/14
2. In the bottom left, locate the "View sheet" button (if you can't find it, you may need to fake some phone calls, see below) 
  a.  Go to http://call.dev.zetkin.org/assignments
  b. Sign in using `testadmin@example.com` and `password`
  c. Select the call assignment you looked at in step 1
  d. Go through the user flow to make some (fake) phone calls
  e. In at least one of the calls, when reporting it, answer yes to "did something happen that requires action by an official"
  f. Return to the call assignment on localhost 
3. Ctrl/cmd+click the button

### Expected Behaviour
Should open a view in a new tab

### Actual Behaviour
Opens in same tab

## Screenshots
This concerns the "View sheet" button in the bottom left of this screenshot.

<img width="1483" alt="image" src="https://user-images.githubusercontent.com/550212/230550609-4013dcc5-84c2-4839-bd3b-0f3b55eaa0b9.png">

## Proposed solution (refactor `getOrganizerActionView` RPC as redirect page instead)
Navigating to this view is currently accomplished using an RPC. When clicking the "View sheet" button on the call assignment page an RPC is invoked, which either finds an existing or creates a new view for this purpose, and returns its ID, at which point the router redirects to the view page.

This is where the UI for this exists:
https://github.com/zetkin/app.zetkin.org/blob/3b02385ce6c1f97cbce7450377a36cb116604d74/src/features/callAssignments/components/CallAssignmentStatusCards.tsx#L140-L152

And this is the model logic that does the redirect:
https://github.com/zetkin/app.zetkin.org/blob/3b02385ce6c1f97cbce7450377a36cb116604d74/src/features/views/models/ViewBrowserModel.ts#L167-L178

Because it's the router doing this redirect, it doesn't work as a link. Instead, I think the logic from the RPC should be moved over to a page route (in `src/pages`, e.g. `src/pages/organize/[orgId]/people/views/blocked.tsx`) in which the `getServerSideProps()` will do the work instead, and then redirect using a regular NEXT redirect.

**Comment by niklasva82** [comment]
@msdsk is on this!

**Comment by richardolsson** [comment]
Since this issue was written, we have refactored the way we make API requests to not use the model/repo pattern anymore, but instead use hooks. The problem persists though, because the proposed refactor (to using a page route with `getServerSideProps()` has not happened).
