### ISSUE TITLE
"Allocated" targets counted twice in `CallAssignmentStatusCards`

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1204]
## Description
The "allocated" number is counted twice in `CallAssignmentStatusCards`, making sums not add up properly.

## Steps to reproduce
1. Go to a call assignment where someone is calling, e.g. localhost:3000/organize/7/projects/standalone/callassignments/14
2. Calculate the sum of all numbers under "status"

### Expected Behaviour
The numbers on each card should match (number at top right should be sum of numbers below).
The sum of all the colored numbers should be the gray number at top right.

### Actual Behaviour
"Targets allocated to caller" is counted towards the "Blocked" sum _and_ the "Ready" sum.

## Screenshots
![image](https://user-images.githubusercontent.com/550212/230561951-b1a80ef5-2043-45c5-ad2e-7945eba6f3dc.png)

**Comment by KraftKatten** [comment]
I'll work on this! ✨

**Comment by richardolsson** [comment]
Closed by #1205
