### ISSUE TITLE
Deleted view is still referenced

### ISSUE THREAD

**Issue by KraftKatten** [zetkin/app.zetkin.org#1209]
## Description
When a view is deleted, it is still referenced somewhere even though it it is null, triggering this error. 

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/people
2. Click on "Create view" in top right, which will create and navigate to a new view
3. On the new view, click the "ellipsis menu" (⋮) in the top right
4. Click "Delete view"
5. Click "Confirm"
6. If the fix for #1201 is not present, click the "People" link among the breadcrumbs.

### Expected Behaviour
Shows the list of views.

### Actual Behaviour
Gets two equal errors. 

## Screenshots
![bild](https://user-images.githubusercontent.com/21238654/230620217-24a7141e-8f78-4d99-9e7f-b643d98f9731.png)

**Comment by ziggabyte** [comment]
Confirm that this is still a bug after the email feature has been merged to main

**Comment by ziggabyte** [comment]
Confirming that this is no longer a bug :D

**Comment by ziggabyte** [comment]
....and remembering to close it also
