### ISSUE TITLE
Use location ID as value in `EventOverviewCard` Autocomplete

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1213]
## Description
The `Autoselect` in `EventOverviewCard` uses the `title` of locations as it's value (and hence as the unique identifier of a location). It's technically possible to have two locations with the same title, so that's not guaranteed to be unique.

https://github.com/zetkin/app.zetkin.org/blob/da050a37cd3694974b902e2c62bb2a776df024b9/src/features/events/components/EventOverviewCard/index.tsx#L97-L101

## Requirements
- [ ] Use the `id` of locations as the unique identifier

## Possible implementations
Use the location array itself as the `options` and render it's title as the label using `renderOption()` or something

## Design specifications
None

## Open questions
None

**Comment by ziggabyte** [comment]
This was a mistake made by me, and I corrected it in #1222
