### ISSUE TITLE
🤸‍♀️ Participants summary card

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1217]
## Description
A user should be able to see a summary of the participation at an event, at the top of the participants tab, and take common actions from there.

Also see epic #1214 for context.

## Relevant Job Stories
* When I’m using events to organize basic activism like handing out flyers or putting up posters, I want to make sure that at least one of the people signed up for the event has done the work before and assign them as the contact for the rest of the activists, so that I can feel comfortable that they will be able to run the event
* When I’m using events to organize basic activism and one of the actvists who signed up would be suitable for running the event, I want to reach out to them, so that I can make sure they are able to do so
* When certain events have taken place, I want to feedback into the system who actually showed up, so that I can keep track of attendance and search accordingly
* When I’m using events to organize basic activism and I have done all of the preparations (assigning a contact etc), I want to be able to send out a reminder e-mail, so that all of the attendees get the information they need

## Prerequisites
None

## Requirements
- [ ] The top left should have the title "Participants"
- [ ] The top right should have the current participant count (not including sign-ups) and minimum required participant count
- [ ] The top right should also have a cogwheel to open a popper where the minimum required participant count can be changed
- [ ] There should be a column for "Pending sign-ups"
  - [ ] The column displays the number of people who have signed up but have not been added as participants
  - [ ] When there are >0 pending sign-ups, display a button that when clicked converts all sign-ups to participants
- [ ] There should be a column for "Notifications"
  - [ ] The column displays the number of booked participants that have received notifications (R), against the total number of participants (P)
  - [ ] When R < P, and there is a contact person set, display a button that when clicked sends reminders to the ones who have not yet been reminded

The third column, "Cancelled" is tracked elsewhere

## Possible implementations
The popper for setting the minimum required participant count is already implemented as part of the participants card on the overview tab, added in PR #1196.

"Convert" sign-ups to participants by adding participants the same way as in #1216.

Send all (unsent) reminders by posting to `/orgs/{org_id}/actions/{action_id}/reminders`.

### In situ on page
![image](https://user-images.githubusercontent.com/2950171/231714651-a5aef1a2-cd11-4e52-a4ed-30e804a4fb71.png)

The card in question is the one marked with a blue frame in the screenshot below.
![image](https://user-images.githubusercontent.com/2950171/231715114-5b3a2590-c640-4e90-84b4-b127b5334139.png)

### First sign-ups (no participants, 7 sign-ups)
![image](https://user-images.githubusercontent.com/550212/231190329-c74dfaf0-6f95-42dd-a9eb-b4217e3d5ea4.png)

### Reminders disabled (no contact person)
![image](https://user-images.githubusercontent.com/550212/231190494-e1767fb1-55a2-4561-8c61-4d65e9f15729.png)

### Reminders enabled (contact person defined)
![image](https://user-images.githubusercontent.com/550212/231190673-1c6c6818-ebf8-466d-b67d-9710a87c2a7a.png)

### More sign-ups (note total counter)
![image](https://user-images.githubusercontent.com/550212/231190852-6c8b1913-44cc-46d9-84c7-eeb15b575169.png)

### Fully booked
![image](https://user-images.githubusercontent.com/550212/231190952-0d1e5e45-4275-4cca-8615-d9ccf2b2ead8.png)

## Open questions
None

**Comment by theo8theo8** [comment]
Working on this!
