### ISSUE TITLE
Add spy to mock API

### ISSUE THREAD

**Issue by kristofferlarberg** [zetkin/app.zetkin.org#123]
Add spy functionality to mock API and verify so API requests during sign-up onClick are done correctly.

**Comment by richardolsson** [comment]
This has to do with event sign-up, as introduced in #104. The tests should verify that the correct API requests are made, but that's not possible currently with moxy. A separate ticket for the moxy functionality has been filed as zetkin/moxy#1.

Note to @kristofferlarberg: It's a good idea to be slightly more specific or provide som extra context (e.g. the pull request link above) in the issue description. Fixing this issue might not be a priority right now, and when we return to it a long time from now, we need to be able to understand what it's all about.

**Comment by richardolsson** [comment]
I've implemented this in moxy now, so after a `yarn install` it should be possible to get the list of requests made with `GET http://localhost:8001/_log`. Reset the log between tests using `DELETE` at the same URL.

**Comment by kristofferlarberg** [comment]
Very nice!
