### ISSUE TITLE
🗓  Day calendar view

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1236]
## Description
A user should be able to see a list of all events, day by day.

## Relevant Job Stories
* When I have lots of small events and activists sign up only for some of them, I want it to be clearly visible for me which events are missing people, so that I can decide which ones to cancel and reallocate resources to the ones we decide to keep
* When I’m planning a campaign or event that is similar to something that we’ve done before (e.g. May 1st, last year), I want to look at the events in Zetkin on a particular date, so that I can learn from and mimic patterns used then

## Prerequisites
Be cautious if you start working on this before #1234 is merged, to avoid duplicating work.

## Requirements
- [x] Navigation bar (also tracked in #1234 and #1235) should work like this:
  - [x] The left/right buttons should move to prev/next day
  - [x] Picking a new month should move to the same date that month, unless the current date does not exist in that month, in which case the last date of that month should become active
  - [x] Picking a new year should move to the same date that year (unless the current date does not exist that year as can be the case with leap years) in which case either Feb 28 or Mar 1 is fine)
- [x] List of days with events on them
  - [x] Each day that has events on it should be displayed with date, month and weekday
  - [x] Today's date, month and weekday should be marked with the primary color (red)
- [ ] Navigating backwards:
  - [x] At the top of the list should be a "ghost day" for the most recent previous date with events
  - [ ] Hovering the ghost day should give slight darker background
  - [x] Clicking should show the previous date (and load the one before that)
- [ ] Navigating forward:
  - [ ] Scrolling to the end of the list should load more events, e.g. 100 events or so
  - [ ] If there are no more events, display a small label saying "There are no more events"

## Possible implementations
Reuse the `EventListItem` from the activity list to render events.

For loading events, we're going to want to use the date filtering with the `/orgs/ID/actions` (or `/orgs/ID/campaigns/ID/actions`) endpoints, e.g. `GET /orgs/1/campaigns/2/actions?filter=start_date%3E2023-04-21` to get events starting after 2023-04-21.

## Design specifications
Ignore the top line of each day that contains surveys etc, which is tracked elsewhere.

See full design including hints [in Figma](https://www.figma.com/file/EjLcpjKWgNizCb5PRBF51P/Zetkin-3?node-id=4884-89113&t=6WXv71VavjxVK7QS-4).

![image](https://user-images.githubusercontent.com/550212/233592186-c85aaa95-2215-4669-b3ac-1b727c9dbb0f.png)

## Open questions
None

**Comment by samuelskanberg** [comment]
Please assign me!

**Comment by joe-irving** [comment]
I would like to do this pls

**Comment by richardolsson** [comment]
This has been merged into the epic branch.
