### ISSUE TITLE
🗓 Event component for calendar views (all states)

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1238]
## Description
A user should be able to see as much information as possible about an event in the calendar.

## Relevant Job Stories
* When I’ve prepared some events but not published them, and they are among many other events that are already published, I want to be able to find the unpublished events so that I can publish them without sifting through all of the already published ones
* When I have a lot of basic activism events happening in the next few days and I’m not sure they’re all fully staffed, I want to see only the ones where people are missing, so that I can focus on mobilizing for those specific events
* When I have lots of events, I want to be able to see them in a calendar view, so that I can easily assess events’ durations and distribution over time
* When I have lots of small events and activists sign up only for some of them, I want it to be clearly visible for me which events are missing people, so that I can decide which ones to cancel and reallocate resources to the ones we decide to keep
* When I view a very busy day/week of events I want to still be able to get a birds-eye view of what events will happen, so that the clutter won’t impede my event planning
* When I select a date/time for an event I want to see what’s already planned so that I can find the best fit for my event and avoid collisions

## Prerequisites
None

## Requirements
- [ ] There should be one or multiple reusable components for displaying events in the week and month calendar views
- [x] Single events should be able to have all the states represented in figma
- [ ] Multi-shift events should be able to have all the states represented in figma
- [x] Multi-location events should be able to have all the states represented in figma
- [ ] Arbitrarily clustered events should be able to have all the states represented in figma

## Possible implementations
Use Storybook to implement these as "dumb" components that we can then use in the calendar views.

## Design specifications
See [full matrix in figma](https://www.figma.com/file/EjLcpjKWgNizCb5PRBF51P/Zetkin-3?node-id=4072-58606&t=mjBj8RCNKhr1F5lx-4)

![image](https://user-images.githubusercontent.com/550212/233597821-27af8100-539e-41f6-95df-276452e24986.png)

## Open questions
There might be combinations of states that have not been covered in figma. Lets try to find sensible solutions together, raise the question if you're not sure!

**Comment by alexander-js** [comment]
Working on this.
