### ISSUE TITLE
🗓 Creating multi-shift events from week calendar view

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1243]
## Description
A user should be able to create multiple events in one go when dragging to create in week calendar view.

See epic #1233 for context.

## Relevant Job Stories
None

## Prerequisites
Don't start this until #1242 is done.

## Requirements
- [ ] The popper that opens when dragging in a calendar should contain an option called "Multiple events that form shifts"
- [ ] Picking "Multiple events that form shifts" should open a modal (see design)
  - [ ] In the modal, the date and times should be pre-filled based on how the user dragged in the calendar
  - [ ] The modal should work like the [figma prototype](https://www.figma.com/proto/EjLcpjKWgNizCb5PRBF51P/Zetkin-3?page-id=3362%3A42339&node-id=4095-63301&viewport=-826%2C-1360%2C0.26&scaling=min-zoom&starting-point-node-id=4095%3A63301&show-proto-sidebar=1)
- [ ] Clicking the "Publish" button should create all of the events with `published` set to the current time
- [ ] Clicking the "Draft" button should create all of the events with `published = null`
- [ ] After the events have been created, the modal should close and the calendar be navigated to the date of the created events

## Possible implementations
None

### Options in popper
![image](https://user-images.githubusercontent.com/550212/233619719-7fe44ab1-a9d5-4d90-b184-3f6c14e504af.png)

### Modal
See [figma prototype](https://www.figma.com/proto/EjLcpjKWgNizCb5PRBF51P/Zetkin-3?page-id=3362%3A42339&node-id=4095-63301&viewport=-826%2C-1360%2C0.26&scaling=min-zoom&starting-point-node-id=4095%3A63301&show-proto-sidebar=1) for detailed user journey.

![image](https://user-images.githubusercontent.com/550212/233619788-eeb4875d-a80e-424d-a62e-3c851f0c22ac.png)

## Open questions
None

**Comment by theo8theo8** [comment]
Have begun working on this :)
