### ISSUE TITLE
View reloads unnecessarily when cell is edited

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1247]
## Description
When the user edits an interactive cell in a view table, e.g. by toggling a checkbox, the view will often reload causing the scroll to be reset. The edit happens correctly, but the scroll reset is very annoying to the user.

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/people
2. Click on "Create view" to create a new empty view and give it some useful name
3. Click "Configure" under the smart search option to the right
4. Pick "Start with a list of all people in the organization" and save the smart search – all people should be loaded
5. Click "New column"
6. Pick a "Toggle" column
7. Scroll to middle of list
8. Wait for 60 seconds
9. Click the toggle

### Expected Behaviour
The toggle state should update and nothing else happen.

### Actual Behaviour
The toggle state does update, but the user won't see that because the scroll is reset so that the person that was toggled is no longer visible.

## Screenshots
<img width="1548" alt="image" src="https://user-images.githubusercontent.com/550212/233635618-5154006d-25ec-44f0-998e-29ff00e78999.png">

## Proposed solution
I think the problem is that the view reloads when the cache gets too old. This is good, but the UI should continue using the old data while it's loading and not reset.

**Comment by danbjork** [comment]
I tried reproducing the issue of unnecessary reloads, but couldn't! I therefor will close this issue

Screen recording of me having set the timeout to 10 milliseconds and pressing the toggle:
https://github.com/zetkin/app.zetkin.org/assets/10441376/74a47f28-0bb0-4856-80dd-de1f9a040157
