### ISSUE TITLE
No way to see full name in `local_person` columns

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1255]
## Description
A user should be able to see the full name of a person who has been "assigned" a certain row in a view using the `local_person`. Currently there is no way to see it except by editing the cell.

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/people
2. Click on "Create view"
3. In the new view, click "New column" and add a "Assigned person" column
4. Add at least one person to the view, e.g. "Jane Doe"
5. In the "Assignee" column, on the "Jane Doe" row, double click the cell and type in "Jane" to assign Jane
6. Hover the "JD" avatar

### Expected Behaviour
Display the name in a tooltip

### Actual Behaviour
Nothing happens

## Screenshots (if you have any)
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/550212/233714799-b039664f-3f08-4b7b-bfcc-8b62ee20d09b.png">

**Comment by carl-gjerris** [comment]
currently working on it

**Comment by djbusstop** [comment]
Just made a new PR for this as went with a different solution to #1265
