### ISSUE TITLE
Keyboard input ignored when editing `local_person` cell

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1256]
## Description
Keyboard input does not work when editing a `local_person` column cell. This means that users need to use their mouse in order to select a person to be assigned in a cell.

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/people/views/169
2. Double click the person cell to edit
3. Type in "Jane"
4. Once the Jane Doe person appears, tap the "down" key

### Expected Behaviour
Jane Doe should be marked as selected somehow, and pressing enter should select them.

### Actual Behaviour
Nothing happens, arrow and enter keys are ignored.

## Screenshots (if you have any)
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/550212/233716515-71c1a647-da02-4744-9fb6-22aa2694d2e2.png">

## Proposed solution
Implement keyboard input by listening to keyboard input while the popper is open. Something similar has been implemented before in the `ViewJumpMenu` (pictured below).

<img width="1206" alt="image" src="https://user-images.githubusercontent.com/550212/233716572-d6b4cbea-ddfb-4019-9567-9737f2b688d6.png">

**Comment by KraftKatten** [comment]
Hejhej, may I work on this?
