### ISSUE TITLE
☢ Add image to Event Popper

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#1261]
When woking on #1194 we were not able to add the image since this was not implemented on the backend yet. 

If the event has an image, it should be shown, if no image show nothing. 

![bild](https://user-images.githubusercontent.com/58265097/233826144-9559ae23-8d95-4e53-8363-c8f3cdc88266.png)

**Comment by richardolsson** [comment]
This is actually already implemented in the API, but this issue should be implemented alongside #1166.

**Comment by richardolsson** [comment]
This was solved by #2043
