### ISSUE TITLE
Cancellning events

### ISSUE THREAD

**Issue by niklasva82** [zetkin/app.zetkin.org#1281]
## Description
A user should be able to cancel an event.

## Requirements
- [x] Clicking the ellipsis menu to the right of the Publish button should show a Cancel option.
- [x] Clicking Cancel should PATCH the event with `{ cancelled: currentDate }`

## Design specifications'
![bild](https://user-images.githubusercontent.com/14962107/235861866-86c9ce55-2b5a-4bdc-b2ea-eec8e3cb6386.png)

**Comment by richardolsson** [comment]
There should probably be a confirm dialog before cancelling, and maybe a way to undo it as well?

**Comment by rebecarubio** [comment]
Good idea! Do we have any designs for this @Bagera ?
