### ISSUE TITLE
Duplicate event

### ISSUE THREAD

**Issue by niklasva82** [zetkin/app.zetkin.org#1282]
## Description
A user should be able to easily duplicate an event.

## Requirements
- [x] Clicking the ellipsis menu to the right of the Publish button should show a Duplicate option.
- [x] Clicking Duplicate should POST to `/orgs/1/actions/` with the same data as the current event and navigate to that event.

## Design specifications'
![bild](https://user-images.githubusercontent.com/14962107/235861866-86c9ce55-2b5a-4bdc-b2ea-eec8e3cb6386.png)

**Comment by joe-irving** [comment]
Added a duplicate event option to the event popper and event page.

I noticed some inconsistency in how the event pages are linked to, including a bug in the event popper where the page being routed to was

```ts
`/organize/${event.organization.id}/${event.campaign ? `projects/${event.campaign.id}` : 'standalone'}/events/${event.id}`
```

when it should be

```ts
`/organize/${event.organization.id}/projects/${event.campaign ? `${event.campaign?.id}` : 'standalone'}/events/${event.id}`
```

where `event` is a `ZetkinEvent` type. Events without a campaign were getting 404 errors

I've added the method `getBrowserUrl` to the `EventDataModel` which might be helpful but not gone through and updated all other places that use this. Just wanted to flag if if needs a separate issue.

**Comment by richardolsson** [comment]
> Events without a campaign were getting 404 errors
> 
> I've added the method `getBrowserUrl` to the `EventDataModel` which might be helpful but not gone through and updated all other places that use this. Just wanted to flag if if needs a separate issue.

Well spotted! Can you create a single separate issue for this bug that you've found? Modifying the `EventDataModel` is not ideal (mostly because we are moving away from the models, which was always an experiment) but a utility in `src/features/events/utils` would be a great place to put a `getEventUrl()` utility.

**Comment by joe-irving** [comment]
Okay great, added that as a separate issue and removed most changes to EventDataModel. Hope merging it works out!
