### ISSUE TITLE
Implement a solution to failed calls after DELETE an EVENT

### ISSUE THREAD

**Issue by rebecarubio** [zetkin/app.zetkin.org#1289]
## Description
After delete an event the chain of calls of the page is trying to fetch some data from the already deleted event, so that brings fetch errors.
 
## Steps to reproduce
1. Go to any event
2. Open chrome dev tools (F12)
3. Click on ellipsis menu and DELETE it
4. The DELETE call is successful bus the re-render of the page brings this error (look in Network in devtools)

### Expected Behaviour
Don't trigger any more calls of the event after deletion
### Actual Behaviour
Triggers event calls after deletion

## Screenshots (if you have any)
![image](https://user-images.githubusercontent.com/36491300/236213205-293b772c-4e26-438d-a48a-1a36f85e48ff.png)

**Comment by richardolsson** [comment]
This is reported again in #1496, which has more information in the discussion.
