### ISSUE TITLE
Fix status chip in Related Events Card

### ISSUE THREAD

**Issue by rebecarubio** [zetkin/app.zetkin.org#1293]
## Description
Status chip number of participants gets hidden when event title is too long.

## Steps to reproduce
1. Go to 'http://localhost:3000/organize/1/projects/1/events/2'
2. Look in Related Events card, event with title "[Book club with Haeju's cool book it is a very long book very long]"
3. Get the screen view smaller to see the chip shrink

### Expected Behaviour
Display full status chip

### Actual Behaviour
Status chip is hidden when screen is smaller

## Screenshots (if you have any)
![image](https://user-images.githubusercontent.com/36491300/236466574-d1eb9695-83d3-41a5-a356-ac96ee4f426d.png)

**Comment by mikemissing** [comment]
I take this one, if its ok ....

**Comment by richardolsson** [comment]
Perfect @mikemissing! I would try setting `flexShrink: 0` on the chip/container and see if that helps.
