### ISSUE TITLE
Correct logic to sort events into archives

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#1294]
## Description
I'm experiencing unexpected behaviours in the activity archive, where recently added, open activities get added to the archive and not the current activities. My suspicion is that this is because the endDate property is set to a date without time, here on line 179, which is interpreted as 00:00 when it is compared to now in the next image, line 228.
This means that an activity created today, set to take place later today, will show up as "in the past" because the time of the event is set to 00:00 today = in the past.

## Steps to reproduce
1. Go to gen2, create an event that takes place later today in org and project of your choice
2. Go to gen3, to this org and project
3. go to archive tab
4. see your recently created event in the archive

### Expected Behaviour
The event has not happened yet, and is open, so it should be in the overview and activities tabs.

### Actual Behaviour
it gets sorted into the archive

## Screenshots (if you have any)
![bild](https://user-images.githubusercontent.com/58265097/236475112-83e45d1c-5963-40b9-b8e5-27b9b4f95689.png)
![bild](https://user-images.githubusercontent.com/58265097/236475164-04ebcbab-0e2f-46e8-a7ba-6f69dd9df760.png)
![bild](https://user-images.githubusercontent.com/58265097/236475200-71252bd3-d393-4785-94e2-40faacc42ace.png)

**Comment by mikemissing** [comment]
I can take this one ...
