### ISSUE TITLE
Adding participants fail after recent update to API

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1301]
## Description
Adding a participant to an event used to work, but is no longer working. Probably because the API used to ignore the body of the `PUT` request used for adding people, but now requires only certain parameters to be included, while the frontend sends incorrect parameters.

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/projects/1/events/115/participants
2. Click on "Add person"
3. Type some name that exists in the database (e.g. "Richard")
4. Click on any person

### Expected Behaviour
The person should be added as a participant to the list below

### Actual Behaviour
There is a 400 error from the API.

## Screenshots (if you have any)
<img width="1952" alt="image" src="https://user-images.githubusercontent.com/550212/236603242-ef3b75ca-702c-4909-bf93-3fee23fca88d.png">

## Possible solution
The body of the `PUT` request made to the server includes the `id` and `reminder_sent`. It should not. The body should be empty in this case. The body can be used for other things, e.g. adding a participant in another state (like `cancelled`) right away, but that's not relevant in this use case.

**Comment by theo8theo8** [comment]
Will begin with this to then be able to work on #1306

**Comment by richardolsson** [comment]
Great plan @theo8theo8. Fixing this will make several other issues easier to deal with.
