### ISSUE TITLE
Hide selection column in participants list

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1302]
## Description
In the design mockups there are select boxes for the participants list of an event (e.g. on http://localhost:3000/organize/1/projects/1/events/15/participants), and this has been implemented as part of the codebase. However, these are only intended for a future feature that has not yet been designed, so the checkboxes will need to be hidden until that feature becomes available.

## Relevant Job Stories
None

## Prerequisites
None

## Requirements
- [ ] Hide checkbox column in all sections on event participant page

## Possible implementations
There should be a property on the `DataGrid` to hide them, something like `disableSelection`.

## Design specifications
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/550212/236603534-7ce8ec97-38e2-427e-a409-db363e94576b.png">

## Open questions
None

**Comment by eli-ennab** [comment]
i will take this
