### ISSUE TITLE
UI not updated after sending reminders

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1306]
## Description
Sending reminders does not immediately update UI.

NOTE: Reproducing this may require also fixing #1301.

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/projects/1
2. Click "Create activity" And pick "Create event"
3. Click the "Participants" tab
4. Click "Add person" add search for "Richard", click any person to add (this may not work right now because of #1301)
5. Repeat step four once or twice
6. In the list of participants, hover any person and click the icon to add them as the contact
7. Click the "Send all" button under notifications in the summary up top

### Expected Behaviour
The number 0/3 should update to 3/3 and something like "3 seconds ago" should show up in the list of participants in the "Notified" column below.

### Actual Behaviour
UI does not update.

## Screenshots (if you have any)
![image](https://user-images.githubusercontent.com/550212/236609704-7bd7b270-0581-4c63-8c1b-9d3940e04d6b.png)

## Proposed solution
Mark the participants list (`participantsById[eventId]`) in the store as stale to force it to reload.

**Comment by theo8theo8** [comment]
Working on this!
