### ISSUE TITLE
Fix errors/warnings related to React Spectrum

### ISSUE THREAD

**Issue by kristofferlarberg** [zetkin/app.zetkin.org#133]
- [ ] Issue related to `ref` when using the `Link` component together with `NextLink`.
- [ ] Non-plain text is unsupported as title attribute prop in the `Item` component inside `Tabs`.

Examples can be found in `OrgHeader` and `MainOrgLayout`.

**Comment by nehahirve** [comment]
Can we close this since no longer using Spectrum @richardolsson?

**Comment by richardolsson** [comment]
> Can we close this since no longer using Spectrum @richardolsson?

Good point! 👍
