### ISSUE TITLE
Add public page link for projects

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1331]
## Description
A user should be able to navigate to the public page for a project.

## Relevant Job Stories
None

## Prerequisites
None

## Requirements
- [x] Under the ellipsis menu on a project page, add an option "Show public sign-up page"
- [x] The option should have an external link icon
- [x] Clicking the option should open the public page in a new browser tab, the URL being `https://www.zetk.in/o/{orgID}/campaigns/{projectId}`

## Possible implementations
None

## Design specifications
None

## Open questions
None

**Comment by niklasva82** [comment]
Should this link be visible even when the campaign is not public? Or should it be greyed out in those cases perhaps?
