### ISSUE TITLE
ZUIDateRange message problem

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#1344]
**Please be as thorough as possible, but if you can't answer everything, please just submit what you have! Thank you!**

## Description
There seems to be an issue with the ZUIDateRange messageIds, specifically the message for indefinite.

## Steps to reproduce
1. Go to an event, like 'projects/1/events/1'
2. Open the console so you can see error messages
3. See the error message that looks like below

### Expected Behaviour
No console error messages

### Actual Behaviour
Gets a console error message

## Screenshots (if you have any)
![bild](https://github.com/zetkin/app.zetkin.org/assets/58265097/3fca6891-f7c2-45b5-b99b-bbf087298f36)

**Comment by niklasva82** [comment]
This appears to be a bit of a mystery. The error message comes from `isDateElement` in `icu-messageformat-parser` which is used by `formatjs`. It appears that the type of the start variable is somehow date (3 in the internal representation of the above package), but the type of start in messageIds is `string`.

I also tried commenting out the date formatting component altogether and replacing the value for `start` with `"hej"`, but still got the same results. On the other hand, when providing the raw dayjs `date` variable, the message disappears and the date is rendered, although always with the year, but then the typing system (rightly so) complains that Dayjs is not assignable to string.

Maybe @richardolsson can take a look at this, perhaps it's a bug in the interpretation of the typing in messageIds. I guess it's not very high priority though.

**Comment by richardolsson** [comment]
Sounds good @niklasva82. Thanks for investigating, it sounds to me like an incorrectly typed parameter is being passed to the localization library. Let's postpone to R40 and I will take a look there.

**Comment by ziggabyte** [comment]
This bug does no longer seem to exist when I attempt to make it appear. I am closing this issue.
