### ISSUE TITLE
Scrolling bar not working and displayed wrong in Calendar View Popper (windows only??)

### ISSUE THREAD

**Issue by rebecarubio** [zetkin/app.zetkin.org#1345]
## Description
Calendar Month and Week View popper is showing scroll bars in a weird way in Windows machines (only multi-shifts events) and also not working when we click them or try to execute the scroll action

## Steps to reproduce
1. Go to http://app.dev.zetkin.org/organize/1/projects/calendar?focusDate=2023-05-12&timeScale=month
2. Choose a multishift event, like "Test5" event of 10th of May 2023
3. Popper will open and you can see how the vertical and horizontal scroll bars are displayed and try to use them

### Expected Behaviour
Get the scroll bars displayed in the margins of the popper

### Actual Behaviour
Bars displayed not in the edges of the popper borders

## Screenshots (if you have any)
Month view:
![image](https://github.com/zetkin/app.zetkin.org/assets/36491300/0ff33352-0435-4033-b0bc-d4eb11e94698)

Week view:
![image](https://github.com/zetkin/app.zetkin.org/assets/36491300/b9c3d42c-a48d-4eac-84b5-85980639835b)

https://github.com/zetkin/app.zetkin.org/assets/36491300/e126bcc6-c6d7-4431-9573-03e8adc7d425

**Comment by rebecarubio** [comment]
It's fixed now

**Comment by richardolsson** [comment]
How was it fixed? Was this issue found before #1329 was merged?

**Comment by rebecarubio** [comment]
Exactly! I have tried to reproduce the bug now in main and it's fixed!
