### ISSUE TITLE
Consistent Event URL Usage

### ISSUE THREAD

**Issue by joe-irving** [zetkin/app.zetkin.org#1354]
When the browser friendly URL is needed for an event, for example in the Event Popper or the Event Page, there is slightly inconsistent usage of how the URL is templated. And in the event popper there is a bug for events that don't sit within the campaign

## Suggestion

Create a utility in src/features/events/utils called getEventUrl() that templates the URL as:

```ts
`/organize/${event.organization.id}/projects/${event.campaign ? `${event.campaign?.id}` : 'standalone'}/events/${event.id}`
```

And update where the URL is needed in pages and components.

**Comment by joe-irving** [comment]
This was mildly annoying me, so added in the linked branch!

**Comment by richardolsson** [comment]
> This was mildly annoying me, so added in the linked branch!

That's great @joe-irving! Can you create a pull request?
