### ISSUE TITLE
Redirect /events url to /projects (o calendar ?) page

### ISSUE THREAD

**Issue by rebecarubio** [zetkin/app.zetkin.org#1369]
## Description
The user will currently see the 404 page when clicking in Events breadcrumb. Instead redirect that to projects page.

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/projects/1/events/298
2. Click on 'Events in the top breadcrumbs
3. See the 404 page

### Expected Behaviour
Redirect to projects page

### Actual Behaviour
showing 404 page

## Screenshots (if you have any)
![image](https://github.com/zetkin/app.zetkin.org/assets/36491300/1419b7bc-25a6-46e5-be06-13d56191258b)

**Comment by richardolsson** [comment]
I think it should be redirected to the calendar. 💯

**Comment by alexandrakoch** [comment]
Gör denna!
