### ISSUE TITLE
Scroll events into view in calendar week view

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1388]
## Description
A user should be able to see their events in the week calendar view. Currently, the week calendar view always displays the first hours of the day (00.00 - 08.00 or so, depending on screen size) when first opened. It would be much nicer if it scrolled down to reveal events.

Example where this issue manifests: http://localhost:3000/organize/1/projects/calendar?focusDate=2023-05-29&timeScale=week

## Relevant Job Stories
None

## Prerequisites
None

## Requirements
- [ ] When navigating to the week view, scroll to the time of the earliest event
- [ ] Also do this when navigating between weeks.

## Possible implementations
Maybe use `scrollTo()` or `scrollIntoView()`.

## Design specifications
None

## Open questions
None

**Comment by richardolsson** [comment]
Didn't you start working on this @danbjork?

**Comment by danbjork** [comment]
Yes I did! But I didn't get much time to spend on it :/ I think I wont add any fix for this ticket. (My idea was to look through all days and find the day with the earliest event, and the make for that event to be the scroll ref)

**Comment by richardolsson** [comment]
> Yes I did! But I didn't get much time to spend on it :/ I think I wont add any fix for this ticket. (My idea was to look through all days and find the day with the earliest event, and the make for that event to be the scroll ref)

Fair enough!

For whoever works on it next, I think an even easier solution might be to get the time of the first event, calculate it's position (which is a linear function of it's start time) and use `scrollTo({ top: offsetPixels, behavior: 'smooth' })` on the scrolling container to scroll there.

**Comment by Jrende** [comment]
I'm going to make an attempt on this.
