### ISSUE TITLE
`null` title prevents clustering

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1399]
## Description
Two events that would normally be clustered (multi-shift or multi-location) will not be when one has a empty string title (`""`) and the other has a `null` title.

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/projects/calendar?timeScale=week
2. In the week calendar, drag to create an event
3. In the event page, choose an event type and a location
4. Go back to the calendar and create another event right after the first one
5. In the event page of the second event, choose the same type and location as in step 3
6. In the event page of the second event, change the title to "Whatever"
7. In the event page of the second event, change the event title back to empty (will display the type)
8. Go back to http://localhost:3000/organize/1/projects/calendar?timeScale=week

### Expected Behaviour
The two events should be clustered as multi-shift, since they appear right after each other

### Actual Behaviour
The don't get clustered, because the first event has a `null` title and the second one has an empty string.

## Screenshots
None

**Comment by amerharb** [comment]
I will look into this
