### ISSUE TITLE
Add tooltips to menu icons

### ISSUE THREAD

**Issue by rebecarubio** [zetkin/app.zetkin.org#1406]
## Description
Users needs to be able to see the tooltips with the name of the different menu items when the menu is closed

## Relevant Job Stories
None

## Estimated size (S, M, L)

I think this issue is Small because all the menu is already done, we just need to add the Tooltip component from the Material UI library.

## Prerequisites
None

## Requirements

- [ ] When hover in any menu icon when menu is collapsed a tooltip with the item menu title should appear.

## Possible implementations
use <Tooltip> component https://mui.com/material-ui/react-tooltip/

## Design specifications
![image](https://github.com/zetkin/app.zetkin.org/assets/36491300/b1b45a73-6254-44ca-b185-87a21a25b89b)

**Comment by alexandrakoch** [comment]
👋
