### ISSUE TITLE
Event is not updating in calendar after editing in event page

### ISSUE THREAD

**Issue by kaulfield23** [zetkin/app.zetkin.org#1411]
**Please be as thorough as possible, but if you can't answer everything, please just submit what you have! Thank you!**

## Description
After creating an event and navigating to the event page, if you make edits and return to the calendar, the event displayed on the calendar are not updating as expected.

## Steps to reproduce
1. Go to 'http://localhost:3000/organize/1/projects/calendar'
2. Click on 'week' tab
3. Create an event
4. Edit event title / type
5. Go back to the calendar by clicking back arrow

### Expected Behaviour
Calendar should show updated event after editing.

### Actual Behaviour
It displays the event as "Untitled event" even after it has been edited. 
So does event popper.

## Screenshots (if you have any)

https://github.com/zetkin/app.zetkin.org/assets/77925373/99161011-a0e6-4ed3-a226-07813bb45a3a

**Comment by richardolsson** [comment]
Fixed by #1413
