### ISSUE TITLE
Hide mentions of upcoming features

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1412]
## Description
There are features that won't make it into R40, but which previous work has already included mentions of. We need to remove those mentions so that they don't confuse users.

## Relevant Job Stories
None

## Estimated size (S, M, L)
This is small, because it just concerns taking away buttons and labels.

## Prerequisites
None

## Requirements
- [x] In the selection bar, hide the "Edit events" button
- [x] Remove the "Limit to" / `limit` operator from Smart Search
  - [x] Remove `OPERATION.LIMIT` enum value in `src/features/smartSearch/components/types.ts` and all mentions of it
  - [x] Remove the "Limit to" strings from `src/features/smartSearch/l10n/messageIds` and all uses of them

## Possible implementations
None

## Design specifications
None

## Open questions
None

**Comment by alexandrakoch** [comment]
.
