### ISSUE TITLE
Event popper and calendar item show wrong participant and reminder count

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1417]
## Description
Several numbers related to participants in both the calendar event item and in the event popper show incorrectly. 

## Steps to reproduce
1. Go to http://localhost:3000/organize/4/projects/calendar?campId=&focusDate=2023-06-10&timeScale=week
2. Drag in calendar to create an event
3. Click "Create single event", which will redirect you to the new event (may take some time in dev mode)
4. Click the "Participants" tab
5. Click "Add people"
6. Search to add two people. You can search for the name "Richard" 😉 
7. On one participant, click "Cancel" so that you have one booked and one cancelled participant
8. Hover the remaining participant to show the little "contact" icon next to the name – click it
9. Click the "Send all reminders" button in the summary up top
10. On the remaining participant, click cancel. You should now have a list of two cancelled participants, one of which has received a notification. There should be no booked participants left. See "Correct numbers" screenshot below.
11. Go back to http://localhost:3000/organize/4/projects/calendar?campId=&focusDate=2023-06-10&timeScale=week
12. Click the event

### Expected Behaviour
* The event item in the calendar should show 0/2 participants (because the minimum required participants is 2, and one is booked)
* The popper should show 0/2 participants
* The popper should show 0/0 notified (should only care about active participants, not cancelled)

### Actual Behaviour
* The event item in the calendar shows 2/2 participants (seems to count cancelled as well)
* The popper shows 2/2 participants (also counts cancelled?)
* The popper shows 1/2 notified (also counts cancelled?)

### Wrong numbers (calendar event and popper)
![image](https://github.com/zetkin/app.zetkin.org/assets/550212/23bcb50b-c78d-499b-aecb-970cae3e1e1f)

### Correct numbers (participants page)
![image](https://github.com/zetkin/app.zetkin.org/assets/550212/f788195a-679b-4e6a-9dd5-68bb271e67e3)

**Comment by richardolsson** [comment]
Actually, the same issue seems to exist with the participants card on the event overview page (screenshot below).

Both the **reminders** and the **participant count** (green pill, "2/2") are showing the wrong numbers and seem to include cancelled participants.

![image](https://github.com/zetkin/app.zetkin.org/assets/550212/df1ca8ce-bfdf-460c-a414-e114732a938a)

Maybe it's possible to create a utility function that can be reused in these situations?

**Comment by Searoose** [comment]
I'll take a look

**Comment by richardolsson** [comment]
I think this is no longer a problem since updates on the backend. Can someone please see if it's possible to reproduce?

**Comment by kaulfield23** [comment]
I could reproduce this bug. The numbers are wrong in calendar, event popper and event overview as well. I will work on this!
