### ISSUE TITLE
Rename "Projects" to "Projects & Activities" in menu

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1419]
## Description
With the new expandable nav menu, there is room for long descriptions of the sections.

## Relevant Job Stories
None

## Estimated size (S, M, L)
I think this is small, because it's just editing a string.

## Prerequisites
None

## Requirements
- [ ] When the nav menu is expanded, the options should be "People", "Projects & Activities", "Journeys", "Areas"

## Design specifications
None

## Open questions
None

**Comment by alexandrakoch** [comment]
On it 🕵️‍♀️
