### ISSUE TITLE
Clicking week number leads to wrong week

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1420]
## Description
In the month calendar view, it is possible to click the week numbers in the far left column. Doing so should lead to the week view for that week, but right now it leads to the week view for the current week.

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/projects/calendar
2. In the far left column, click the number of the next week

### Expected Behaviour
Should navigate to the week view for next week (setting the `focusDate` to a date in that week).

### Actual Behaviour
Navigates to week view for current week (does not change `focusDate`).

## Screenshots
None

**Comment by richardolsson** [comment]
I suspect that this was caused by the changes in #1384, and that there is something happening when clicking the week number that leads it to be set, and then reset again. But I may very well be wrong here, and this might just be some super simple mistake causing the new `focusDate` not to be calculated correctly _before_ navigating to it.

**Comment by Jrende** [comment]
I'm on it!
