### ISSUE TITLE
"Remind all" button slightly off center

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1421]
## Description
The "Remind all" button is just slightly off center vertically.

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/projects/calendar
2. In the calendar, drag to create
3. Click "Create single event", which will take you to the event page of the new event (may take some time in dev mode)
4. Click "Participants" tab
5. Click "Add people"
6. Search for some name to add a participant, e.g. "Hans"
7. Add a contact person, either by searching in the top right or by hovering "Hans" in the participant list and clicking the little icon that appears
8. Note the participants summary towards the top

### Expected Behaviour
Should show "Remind all" center aligned with the number of people reminded (0/1)

### Actual Behaviour
Shows the button but it's not centered.

## Screenshots
![image](https://github.com/zetkin/app.zetkin.org/assets/550212/0f68b154-dbc5-4987-99bf-fca3a2414989)

**Comment by Searoose** [comment]
I'm on this :)
