### ISSUE TITLE
Add `@typescript-eslint/no-unnecessary-condition` eslint rule

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1424]
## Description
Developers should be alerted when adding unnecessary conditions that are always true (or false).

## Relevant Job Stories
None

## Prerequisites
None

## Requirements
- [ ] Add the `@typescript-eslint/no-unnecessary-condition` eslint rule
- [ ] Fix all errors that arise when the rule is added.

## Possible implementations
None

## Design specifications
None

## Open questions
If the amount of errors seem overwhelming, raise the issue to be discussed with the core team.

**Comment by nehahirve92** [comment]
@richardolsson thought about warming up with this one but it's assigned to someone; but a while ago; is it being worked on?

**Comment by richardolsson** [comment]
Great question @nehahirve92! Let me check with @alexandrakoch who's coming in to the hackathon today. I'm pretty sure there's a good reason it was never finished, e.g. that we discovered something when looking into it that prevented us from going forward, but then forgot to document it here.

There's a similar one in #1298 if you're keen. 😊

**Comment by alexandrakoch** [comment]
I think it was that it triggered on a **lot** of if else statements with `both sides of the expression are literal` and  @richardolsson thought 'fixing' that would worsen readability by making the logic harder to read. @nehahirve92

**Comment by richardolsson** [comment]
I don't remember this reasoning, but I'm going to trust myself from the past, and close this. 😊
