### ISSUE TITLE
Long sentences in surveys doesn't work in SmartSearch

### ISSUE THREAD

**Issue by rebecarubio** [zetkin/app.zetkin.org#1447]
## Description
When a user is doing a smart search query and choses a long answer from a survey as in their search the interface gets to small to be able to continue working.

## Steps to reproduce
1. Go to 'http://localhost:3000/organize/1/people/views/127'
2. Click on 'New column"
3. Click on 'Custom cross-reference' to create a new smart search
4. Click on "Add people based on the response to questions"
5. Select "Fix long sentences survey"
6. Select the long question

### Expected Behaviour
Keep seen all the interface of the smart search

### Actual Behaviour
The long sentence/question expands too much to see the smart search options

## Screenshots (if you have any)
![image](https://github.com/zetkin/app.zetkin.org/assets/36491300/4563b677-eb78-49c8-b480-fb02f34c6418)

![sMartsearchbug](https://github.com/zetkin/app.zetkin.org/assets/36491300/ab2bbea8-ac52-4845-8634-fc67322ac5e2)

**Comment by richardolsson** [comment]
How are you solving this? I would recommend just truncating the text at a certain number of characters at the end, or in the middle (so that both the start and end of the question is displayed).
