### ISSUE TITLE
Spring cleaning 3

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#147]
This is a spring cleaning task, similar to #53 and #82 (click for more info and links to pull requests). On these issues, we list code maintenance/style issues as we come across them, so that we can fix a whole bunch of them in one go.

- [x] Be consistent about `attr?: type` vs `attr: type | undefined`
- [x] Add linting that forbids single-line if statements and loops

Done elsewhere: 
- [x] Add [`eslint-plugin-no-only-tests`](https://www.npmjs.com/package/eslint-plugin-no-only-tests) to prevent accidentally committing `it.only()`
- [x] Decide on tab width for YAML files and add correct setting to `.editorconfig`
- [x] Consider using non-relative imports to get rid of `../../../../../../` in imports (everywhere except playwright)
- [x] Move all `@types` dependencies to dev dependencies

Wont do:
- [ ] Verify that ordering of interface/type members is enforced, which may not be the case according to testimony by @kristofferlarberg when building #159
- [ ] Order interfaces alphabetically in types modules (and perhaps elsewhere as well)?
- [ ] Use consistent scheme for path index pages (e.g. `src/pages/o/[orgId].tsx` vs `src/pages/o/my/index.tsx`)

**Comment by djbusstop** [comment]
> Add [eslint-plugin-no-only-tests](https://www.npmjs.com/package/eslint-plugin-no-only-tests) to prevent accidentally committing it.only()

This is solved already with a regex in the CI

**Comment by djbusstop** [comment]
> Verify that ordering of interface/type members is enforced, which may not be the case according to testimony by @kristofferlarberg when building https://github.com/zetkin/app.zetkin.org/pull/159

Not sure this is worth the amount of work to do?

**Comment by richardolsson** [comment]
> > Verify that ordering of interface/type members is enforced, which may not be the case according to testimony by @kristofferlarberg when building #159
> 
> > Order interfaces alphabetically in types modules (and perhaps elsewhere as well)?
> 
> Not sure this is worth the amount of work to do?

I agree completely! Felt a little self-cringe when I read that this weekend. Lets forgot I ever put that on there. 😊

**Comment by richardolsson** [comment]
> Use consistent scheme for path index pages (e.g. `src/pages/o/[orgId].tsx` vs `src/pages/o/my/index.tsx`)

Also not sure if this is something we need to be consistent about?
