### ISSUE TITLE
No visual indication of what's happening after clicking Remind all

### ISSUE THREAD

**Issue by niklasva82** [zetkin/app.zetkin.org#1482]
## Description
When clicking Remind all in an event, nothing happens for a long time while the server is busy sending emails.

## Steps to reproduce
1. Go to an event with participants
2. Click on Remind all
3. Wait for operation to succeed

### Expected Behaviour
Some visual indication that the server is currently processing the request.

### Actual Behaviour
No visual indication. Nothing happens for several seconds until the client receives a response from the server.

**Comment by MattettaM** [comment]
Looking into this with Haeju
