### ISSUE TITLE
Deleting a selected event in the calendar does not close the bottom bar

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#1491]
**Please be as thorough as possible, but if you can't answer everything, please just submit what you have! Thank you!**

## Description
I had created a few events in my project calendar and wanted to delete some of them via their "event poppers". Along the way one of the events got marked (in the checkbox) before I deleted it, and when it was deleted the bottom-bar still stayed. It seems the state of an event being checked did not get cleared when the checked event no longer exists.

## Steps to reproduce
1. Go to a project that has events, or create some events in a project
2. go to the calendar
3. check the checkbox of one event 
4. notice the bottom bar appear
5. now delete the checked event using the ellipsis menu on its "event popper"

### Expected Behaviour
The bottom bar disappears, as the only checked event no longer exists

### Actual Behaviour
The bottom bar is still there, saying 1 event is selected

## Screenshots (if you have any)
![bild](https://github.com/zetkin/app.zetkin.org/assets/58265097/fcb3305b-a11a-4483-b3cb-1a24a2238fb7)

**Comment by richardolsson** [comment]
I'm so glad you picked up on this! Thanks for creating an issue for it.
