### ISSUE TITLE
Deleting an event throws an error(404)

### ISSUE THREAD

**Issue by kaulfield23** [zetkin/app.zetkin.org#1496]
**Please be as thorough as possible, but if you can't answer everything, please just submit what you have! Thank you!**

## Description
When I attempt to delete an event from the single event popper, it triggers the error and receives status 404.

## Steps to reproduce
1. Create an event in a project calendar.
2. Click on the created event
3. Click on the ellipsis menu in single event popper
4. Delete the event

### Expected Behaviour
No error should appear.
### Actual Behaviour
Unhandled Runtime Error appears.
![image](https://github.com/zetkin/app.zetkin.org/assets/77925373/1856fba4-2cf2-4345-aabe-aba66ca7d5ec)

## Screenshots (if you have any)

https://github.com/zetkin/app.zetkin.org/assets/77925373/a2589a70-382c-404c-a2c3-b35c03f486b2

**Comment by niklasva82** [comment]
What happens here is not that the delete is unsuccessful, but that a new GET request is made after the action has already been deleted. I tried tracking down why last week but I was unsuccessful.

**Comment by richardolsson** [comment]
Leave this to me. I have a plan. 😊

**Comment by niklasva82** [comment]
> Leave this to me. I have a plan. 😊

Great!

**Comment by richardolsson** [comment]
Here's my plan:

I suggest we add a `deleted` property to `RemoteItem`. When something is deleted, we don't actually delete it from the store, we just mark it as deleted. This will immediately prevent it from being retrieved again and getting 404 errors (the bug in this issue). Then the UI can get the deleted item and decide how to deal with it. 

What do you think @niklasva82 ? Maybe this is something you could work on now that I've laid out my plan (sorry but I don't expect to be able to find the time to do it myself in the near future).

**Comment by richardolsson** [comment]
Also see #1208 for a related issue that could be solved the same way.

**Comment by ziggabyte** [comment]
Confirm that this is still a bug after the email feature has been merged to main

**Comment by ziggabyte** [comment]
Closing this, as this bug was solved by introducing the `deleted` property on remote items in the work on the email feature.
