### ISSUE TITLE
Recent organizations in organization switcher are swapped when filtering

### ISSUE THREAD

**Issue by yusf** [zetkin/app.zetkin.org#1507]
## Description
The recent section of the organization switcher is sorted by most recently selected organization. When using the switcher's filter on organization tree, the order of the most recent changes. 

## Steps to reproduce
1. Open organization switcher
2. Type something in the filter that will match several of the most recent organizations

### Expected Behaviour
For the order of the items in the "Recent organizations (filtered)" that also matches the filter **to remain sorted by the original logic**.

### Actual Behaviour
Item order is changed

## Screenshots (if you have any)
<img width="298" alt="bild" src="https://github.com/zetkin/app.zetkin.org/assets/346211/60def71a-4f4b-4ccf-960d-7e04ce7e7186">
<img width="299" alt="bild" src="https://github.com/zetkin/app.zetkin.org/assets/346211/026bf638-3adc-4c97-a7ec-bd3f6cbfaf34">

**Comment by ajoensson** [comment]
I'll have a look at it!

**Comment by ajoensson** [comment]
The order is swapped for "all organizations" as well. Should this be changed as well? Could not see anything about ordering by search score in [the original issue](https://github.com/zetkin/app.zetkin.org/issues/1374).

Example: ("Ringstuga" jumps above "Journeys sandbox")
![Screenshot 2023-09-10 at 14 07 48](https://github.com/zetkin/app.zetkin.org/assets/5444360/ecba8408-73a1-4107-bab9-7e847b4ff407)![Screenshot 2023-09-10 at 14 07 55](https://github.com/zetkin/app.zetkin.org/assets/5444360/9409418f-73c5-42a7-aad6-52387e97517d)

**Comment by richardolsson** [comment]
Great question @ajoensson. I think it would make sense to retain ordering. But I can't entirely wrap my head around what that does with the way hierarchy is represented while searching/filtering. Try searching for "org" and you should find organizations with varying parents.

If you can make that feel right with retained alphabetical sorting, I think it makes sense to be consistent across both lists.

Great work identifying this! 💯

**Comment by ajoensson** [comment]
It didn't seem to affect the display of hierarchical data, I'll retain ordering there too!
Before/after:
![Screenshot 2023-09-10 at 14 40 01](https://github.com/zetkin/app.zetkin.org/assets/5444360/61a490ad-1055-46d4-aff3-ca4bd334b5b9)![Screenshot 2023-09-10 at 14 36 28](https://github.com/zetkin/app.zetkin.org/assets/5444360/6931d77c-662c-41c2-878e-bd46348870da)
