### ISSUE TITLE
Ellipsis menu position in nav menu user section is wrong

### ISSUE THREAD

**Issue by yusf** [zetkin/app.zetkin.org#1508]
## Steps to reproduce
1. Open user menu

### Expected Behaviour
- For the menu to appear right over the ellipsis button. (screenshot shows box indicating the button borders)
- For the menu to be contained and aligned within the limit of the whole nav menu pane, not exceed it.

<img width="355" alt="bild" src="https://github.com/zetkin/app.zetkin.org/assets/346211/359c2034-f545-4e9d-b3c6-2fadc978b6e3">

### Actual Behaviour
- Menu covering the ellipsis button.
- Menu expands past nav menu pane limit
- 
<img width="403" alt="bild" src="https://github.com/zetkin/app.zetkin.org/assets/346211/f30e69e6-e3db-41f8-9103-faf9bdbdae37">

**Comment by richardolsson** [comment]
I believe there is some sort of property on the popper/menu component used in the ellipsismenu, to control where the popper anchors next to the icon.

Solving this bug should mean exposing that property on `ZUIEllipsisMenu` and setting it here such that the popper anchors it's bottom right corner to the icon button.
