### ISSUE TITLE
Fix that Head tag in EventList overwrites Head tag

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#153]
Because the Map component in EventList uses Leaflet it requires a link to an external stylesheet in a Head element. This apparently overwrites fx the title tag in the general Head tag.

**Comment by richardolsson** [comment]
I've added the `entry-level` label. I'm not sure about the difficulty of this, but the first step is research and that could probably be done without knowing much about the codebase.

**Comment by richardolsson** [comment]
Closing this as the activist-facing pages have not been a priority, and when we do shift focus to them we will want to start that process fresh.
