### ISSUE TITLE
Group Tags is not correctly translated in Swedish

### ISSUE THREAD

**Issue by Bagera** [zetkin/app.zetkin.org#1535]
## Description
When looking at a journey instance the string "Group Tags" is translated into "gruppetiketter" when I think it should be "gruppera etiketter"

## Screenshots
![image](https://github.com/zetkin/app.zetkin.org/assets/2950171/5562b4dd-40fa-4773-925a-bc79bdaaeab6)

**Comment by richardolsson** [comment]
This should be fixed at https://translate.zetkin.org, not in the codebase directly.

**Comment by richardolsson** [comment]
This should already be fixed (by Patrik). Confirm once new strings have been loaded.
