### ISSUE TITLE
Some strings are not internationalized

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1538]
## Description
Some strings are not internationalized:

* "Add N columns" in the list column dialog
* Calendar bulk actions move/copy
* The headline "Calls and conversations" in the call assignment insights tab
* "Delete" in ellipsis menu in view browser

## Steps to reproduce
1. Set your browser language to Swedish, Norwegian, Danish or German
2. Go to one of the pages/screens mentioned above

### Expected Behaviour
Localized versions of texts should show

### Actual Behaviour
English texts show.

## Screenshots (if you have any)
N/A

**Comment by rebecarubio** [comment]
I can't reproduce the bug in "Add N columns" in the list column dialog. The button string gets translated:


![Image](https://github.com/zetkin/app.zetkin.org/assets/36491300/2026b9ed-b230-4787-8ade-ff06509d6ff3)

**Comment by richardolsson** [comment]
That's a good sign @rebecarubio. I was able to reproduce it on dev (http://app.dev.zetkin.org/organize/1/people) in German but not in Swedish. So maybe it's just that the translations are missing in German at https://translate.zetkin.org, or that we need to update the German strings YAML file.

**Comment by rebecarubio** [comment]
- "Add N columns" in the list column dialog --> missing German translation
- Calendar bulk actions move/copy --> missing translations in all available languages
- The headline "Calls and conversations" --> it was a hardcoded string. Implementation in PR.
- "Delete" in ellipsis menu in view browser --> all translations are available in all languages and yaml files are updated. I can't reproduce the bug
![Image](https://github.com/zetkin/app.zetkin.org/assets/36491300/8a3e2525-4201-4687-a781-b4f830ac6c39)

**Comment by richardolsson** [comment]
Nice!

What are the message ID of the strings that are missing one or several translations?

> * "Delete" in ellipsis menu in view browser --> all translations are available in all languages and yaml files are updated. I can't reproduce the bug
>   ![Image](https://user-images.githubusercontent.com/36491300/269339862-8a3e2525-4201-4687-a781-b4f830ac6c39.png)

This is a misunderstanding. You have looked in the single-view page. The problem I found was in the view browser, i.e. in the list of views that you can find for example at http://localhost:3000/organize/1/people. I'm pretty sure it's hardcoded.

**Comment by rebecarubio** [comment]
Summary of message ID of the strings that are missing:
-  `views.columnDialog.editor.buttonLabels.addColumns` (missing German)
- `calendar.selectionBar.moveCopyButtons.[`copy + move] (missing all languages)
- `callAssigments.insightsHeader` (missing all languages)
- `views.browser.menu.delete `(missing all languages)
