### ISSUE TITLE
Input field for adding people to lists missing

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1562]
## Description
The input bar at the bottom of static lists, that the user can use to add a single person to the list, has gone missing. This was probably introduced by the upgrade of MUI X.

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/people
2. Click on "Create list"
3. In the new list empty screen, search to add a single person

### Expected Behaviour
The new person is added, the list shows the person in the table, and the input field used to add the person moves to the bottom of the screen where the user can continue using it to add more people.

### Actual Behaviour
The new person is added, the list shows the person in the table, but the input field is nowhere to be found so the user can not add any more people to the list.

## Screenshots
I'm expecting to see the input field in the bottom, under the table footer (the row where it says "Total rows: 1"). Instead that table footer is at the very bottom of the screen and there is nothing underneath it, which is unexpected to me.
![image](https://github.com/zetkin/app.zetkin.org/assets/550212/1010c2a8-31d0-4d95-81ce-65eaa4991fe8)

**Comment by richardolsson** [comment]
I think this has higher priority than the refactor because this is a bug that prevents users from using static lists. Do you think you can look at this today @ziggabyte?

**Comment by ziggabyte** [comment]
I am actually not able to reprouce this on `main` in Firefox or Chrome... to me it seems to work the same as on `app.dev`?

**Comment by richardolsson** [comment]
This was a mistake on my part. I had forgotten to `yarn install` the updated versions of MUI X, and the only way that manifested was through this. 🤷
