### ISSUE TITLE
Error retrieving Insights in call assignment 

### ISSUE THREAD

**Issue by rebecarubio** [zetkin/app.zetkin.org#1568]
**Please be as thorough as possible, but if you can't answer everything, please just submit what you have! Thank you!**

## Description
When users tries to gets Insights from a Call Assignment there's an error and data doesn't get fetched.

## Steps to reproduce
1. Go to any call assignment, like  'http://localhost:3000/organize/1/projects/1/callassignments/30'
2. Click on 'Insights folder.'
3. Page is render with and error and API request fails with error 500

### Expected Behaviour
Insights gets fetched and API request doesn't fail

### Actual Behaviour
Api request fails. Error in API url string

## Screenshots (if you have any)
![image (1)](https://github.com/zetkin/app.zetkin.org/assets/36491300/9647a90f-95bf-4082-b23c-9c7cf41bc517)

**Comment by richardolsson** [comment]
We deleted this feature (in #1555) for the time being.
