### ISSUE TITLE
Download events ICS file

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#157]
On the event page, add a link that downloads an ICS calendar file for the event. There should be libraries for creating ICS files that can be used for this.

**Comment by richardolsson** [comment]
> Might I be so bold as to suggest "a personal My Zetkin things ICS"?

A personal (synchronized) ICS would be an awesome feature! The bad news is that it's quite complicated with the Zetkin auth/security model to expose data like that through just a URL (without going through the OAuth code flow). But the good news is that the recent addition of API keys does make this possible. The only thing preventing it from being a no-brainer is adding proper support for "scopes", so that an API key created for this purpose cannot be used for any other purpose in case it leaks.

**Comment by olleolleolle** [comment]
This reminds me of the "this API key is for Build Status Badge only" in CI
systems' API key UIs. That is, they make it a very clear "low-scope" type
of API key, and add specific UI to create one.

**Comment by richardolsson** [comment]
This issue is not specific enough, but the feature idea is tracked elsewhere and will return!
