### ISSUE TITLE
Verify that a project exists in getServerSideProps

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#1576]
## Description
you can access an activity via the url even if the project the activity belongs to is deleted.

## Steps to reproduce
1. Go to projects/1 - you get 404
2. Go to projects/1/events/1

### Expected Behaviour
404, since the project does not exist

### Actual Behaviour
You access the page of the event.

## Suggested solution
Here is how it is solved in call assignments:

https://github.com/zetkin/app.zetkin.org/blob/020dcc3a1f45a1b9228bb60cf68b8ee28533277b/src/pages/organize/%5BorgId%5D/projects/%5BcampId%5D/callassignments/%5BcallAssId%5D/index.tsx#L28-L31

**Comment by robynpartridge** [comment]
Tried to reproduce this just now on main branch and got the expected behavior.
