### ISSUE TITLE
Assignee cell in edit mode assigns random person in searched list

### ISSUE THREAD

**Issue by kaulfield23** [zetkin/app.zetkin.org#1582]
**Please be as thorough as possible, but if you can't answer everything, please just submit what you have! Thank you!**

## Description
When I try to assign a specific person in assignee cell, it assigns random person when I write previous assignee's name in search field. 

## Steps to reproduce
1. Go to http://localhost:3000/organize/6/people/lists/432 or http://app.dev.zetkin.org/organize/2/people/views/226
2. Click on avatar in assignee cell.
 - If there is no assignee yet, assign a person. Type 'car' in the search field and pick **Carl Hornby**.
3. You can now see the assignee. Try to edit and assign to another person who has the same first name as the previous assignee. (e.g. Type 'car' in the search field and pick **Carl Chalen**.)
4. If it assigns the correct person, repeat step 3 until it assigns the wrong person.

### Expected Behaviour
Should assign the correct person.
### Actual Behaviour
Assigns random person in the searched list.
## Screenshots (if you have any)

https://github.com/zetkin/app.zetkin.org/assets/77925373/9a9d6c90-0369-4e90-aefe-c81915ff4376

**Comment by richardolsson** [comment]
I'm not sure if this is still the case after #1555, so a first step for any volunteer interested in this is checking if the bug can be reproduced.

**Comment by avart** [comment]
This bug is reproducible by following the above steps. I can start work on it this week.
