### ISSUE TITLE
Adding Notes, Assigned person column is not working

### ISSUE THREAD

**Issue by kaulfield23** [zetkin/app.zetkin.org#1583]
**Please be as thorough as possible, but if you can't answer everything, please just submit what you have! Thank you!**

## Description
When I try to add a notes column or assigned column, page shows that something went wrong.

## Steps to reproduce
1. Go to a list (e.g. http://localhost:3000/organize/1/people/lists/238)
2. Click on `+ New column`
3. Add "Assigned person"  or "Notes" in "Outreach" / "Assigned person" in "Utility"
4. You will see the error `There was an error creating the column` on the bottom right.

### Expected Behaviour
Should add columns.
### Actual Behaviour
Nothing happens but shows error on the bottom right

## Screenshots (if you have any)

https://github.com/zetkin/app.zetkin.org/assets/77925373/c0dcacfb-4899-4257-9f92-adc2d982110f

### Network panel
- Request
 
![image](https://github.com/zetkin/app.zetkin.org/assets/77925373/fbc3cceb-d42a-4af9-8f17-ede0a9958451)

- Response

![image](https://github.com/zetkin/app.zetkin.org/assets/77925373/05ca48c8-52a0-4b09-ae6d-e59a3e9dea85)

**Comment by richardolsson** [comment]
I solved this for the "Notes" column in d36b2ada45fef3f262d95f2073882c24ed749180, but didn't realize the issue also affects person columns.

Whoever takes this on can look at my solution in d36b2ada45fef3f262d95f2073882c24ed749180. This seems to be a copy-paste mistake, that for a long time had no negative effects, but stopped working after we introduced server-side validation of the configuration schema for different types of columns.
