### ISSUE TITLE
Calendar filter popup does not close on blur/clicking away.

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#1584]
## Description
If I open the calendar filter popup to select filters for what events I see in the calendar, and then click on, for example, another tab, the filter popup stays open. 

## Steps to reproduce
1. Go to the calendar of all/any projects
2. Click on the Filter button in the top right corner
3. Now click to do something else, for example on the "Overview" tab

### Expected Behaviour
When I get to the Overview tab, the Filter popup has closed

### Actual Behaviour
The Filter popup stays open and floating on top of the overview page.

## Screenshots (if you have any)
![bild](https://github.com/zetkin/app.zetkin.org/assets/58265097/046b4942-adcd-48f8-b1e2-f697fca31467)

**Comment by richardolsson** [comment]
I believe this was fixed by PR #1659. Do you agree?

**Comment by richardolsson** [comment]
I'm closing this as I believe it was fixed. 💯
