### ISSUE TITLE
"Book all" updates numbers incorrectly

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1591]
## Description
Using the "book all" button in an event's participants tab causes the number state to update incorrectly.

## Steps to reproduce
1. Go to any event page
2. Make sure there are sign-ups (if there are none, add them via the API or by setting up a call assignment and signing some people up via the assignment)
3. Click on the "Book all" button

(To reproduce more rapidly without having to repeat step 2, use the API to remove the participants which will not remove the sign-ups, causing them to show up again)

### Expected Behaviour
The number of sign-ups should go from N to zero, and the number of participants should increase by N.

### Actual Behaviour
The number of sign-ups go to zero, but the number of participants increase by some seemingly arbitrary number.

## Screenshots (if you have any)
![image](https://github.com/zetkin/app.zetkin.org/assets/550212/21680677-c21a-40c5-af46-bdc053480260)

**Comment by annafock** [comment]
I'm starting to look at this
