### ISSUE TITLE
Implement File upload step and data parsing 🚚

### ISSUE THREAD

**Issue by rebecarubio** [zetkin/app.zetkin.org#1598]
## Description

A user should be able to upload a file

See epic #1595 for context.

## Relevant Job Stories
* When I import data from excel, I want Zetkin to filter out excel internal data columns from the columns I am presented with, so that I don’t have to try to understand if it is relevant data

## Estimated size (S, M, L)

I think this issue is {L} because it takes care of different actions that we don't have defined and it's a new feature

## Requirements:
[] Upload file clicking button
[] Upload file dragging file

## Possible implementations
Reference https://github.com/zetkin/organize.zetk.in/blob/master/src/actions/importer.js

## Design specifications

![Image](https://github.com/zetkin/app.zetkin.org/assets/36491300/016560e7-a3b0-4d57-99f5-48d31bb7aae6)

## Open questions

**Comment by ziggabyte** [comment]
Closed as completed by #1605 and #1612
