### ISSUE TITLE
Milestones not loaded if journey was loaded as part of list

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1604]
## Description
When a journey has been loaded as part of the journeys list, the milestones for that journey are not included. Navigating to an instance of that journey without refreshing the browser (and hence invalidating the cache in the redux store) will result in no milestones being displayed.

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/journeys (this is important, this must be the entry point)
2. Click on "Case"
3. Click on one of the cases in the list
4. Click on the "Milestones" tab

### Expected Behaviour
Should list milestones

### Actual Behaviour
Says "There are no milestones".

Refreshing the page fixes this.

## Screenshots (if you have any)
![image](https://github.com/zetkin/app.zetkin.org/assets/550212/a5642542-0025-4e01-8602-b25a1535abe3)

**Comment by a-jaxell** [comment]
I'd like to work on a solution for this.
