### ISSUE TITLE
People tag tests intermittently failing

### ISSUE THREAD

**Issue by alexandrakoch** [zetkin/app.zetkin.org#1672]
## Description

Sometimes the tests `integrationTesting/tests/organize/tags/add.spec.ts` and `integrationTesting/tests/organize/tags/remove.spec.ts` will fail when running playwright locally, it's intermittent if the tests fail and when they do they sometimes fail independently of each other. I am running on the latest macOS version on an M1 Pro MacBook Pro, and have updated any libraries involved.

## Steps to reproduce
1. Run `playwright test` on a local machine a few times
2. The above tests will intermittently fail

### Expected Behaviour

The tests pass

### Actual Behaviour

The tests fail

## Screenshots

<img width="1032" alt="bild" src="https://github.com/zetkin/app.zetkin.org/assets/50528622/bef75302-4f3a-40b9-9c5e-6491cdc53ce1">
<img width="1012" alt="bild" src="https://github.com/zetkin/app.zetkin.org/assets/50528622/c0c1fa35-0121-48ec-8adc-1c475406a99d">

**Comment by richardolsson** [comment]
I can't reproduce this now, and I haven't seen the problem in a long while, so I'm guessing it's fixed, perhaps by 28c685cd7876271f25ed886264c283167df273f0.
