### ISSUE TITLE
Error fetching breadcrumbs in Callers tab of standalone Call Assignment

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#1680]
**Please be as thorough as possible, but if you can't answer everything, please just submit what you have! Thank you!**

## Description
When I go to the Callers tab of a standalone Call Assignment, I get an error from fetching the breadcrumbs. The `undefined` campaign ID is not interpreted as `standalone` and instead just sent as `undefined` in the query string. 
![bild](https://github.com/zetkin/app.zetkin.org/assets/58265097/8a11d7e5-1855-4f3b-abfe-687622a4812d)

## Steps to reproduce
1. Go to a call assignment that does not belong to a project
2. Go to the Callers tab
3. Notice that it does not have any breadcrumbs at the top of the page
4. Look in the network panel and see a `500` status from the request to get the breadcrumbs

### Expected Behaviour
I get breadcrumbs that look the same as they do on the Overview tab of the same call assignment

### Actual Behaviour
I get no breadcrumbs at all.

**Comment by richardolsson** [comment]
I'm not able to reproduce this on `main` at http://localhost:3000/organize/1/projects/standalone/callassignments/2/callers. Are you @ziggabyte?

**Comment by ziggabyte** [comment]
@richardolsson I am reproducing it on the callers tab of [http://localhost:3000/organize/1/projects/standalone/callassignments/6](http://localhost:3000/organize/1/projects/standalone/callassignments/6), the url has `/undefined/` in it instead of `/standalone/`. Will investigate.
