### ISSUE TITLE
Sidebar/menu animates too aggressively

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1685]
## Description
The menu on the left-hand side on all /organize/ID pages animates on every page load / navigation. I think it should only animate when the user triggers it to open/close.

## Steps to reproduce
1. Go to http://localhost:3000/organize/1
2. Make sure the navbar on the left is open (click little arrow over logo if not)
3. Reload the page

### Expected Behaviour
The navbar should be open immediately.

### Actual Behaviour
The navbar starts closed, but expands on refresh.

## Screenshots (if you have any)
None

**Comment by nanoobop** [comment]
sorry already made this

**Comment by ajoensson** [comment]
Ah gotcha!
