### ISSUE TITLE
Login should redirect to previous page

### ISSUE THREAD

**Issue by kristofferlarberg** [zetkin/app.zetkin.org#169]
In it's current state the login process redirects you to `/` after login. It would be preferred if the user is redirected to the page they visited prior the login procedure.

Steps to reproduce:

1. Go to `/o/1/events`
2. Press login button
3. Login at the login page

Expected results: Redirected to `/o/1/events`
Actual results: Redirecited to `/`

**Comment by richardolsson** [comment]
I would solve this by taking the following steps:

- [ ] Handle an optional query string parameter at /login, e.g. `?redirect`
- [ ] If the redirect param is supplied, store the path in session
- [ ] After login (in `index.tsx`) if a redirect URL is in the session, redirect to there

**Comment by richardolsson** [comment]
I think this issue only existed for the login button, that doesn't exist anymore.
