### ISSUE TITLE
Correct content in header on 404

### ISSUE THREAD

**Issue by kristofferlarberg** [zetkin/app.zetkin.org#170]
The header should show correct buttons etc. when user is logged in and reaches a 404 page.

Steps to reproduce:

1. Login
2. Go to `/o/events`

Expected result: user avatar, username, Organize and Logout buttons visible in header.
Actual result:  Login button visible in header.

**Comment by richardolsson** [comment]
Hi Kristoffer! I'm just here to close this ancient issue because it's not really relevant anymore. 😊
