### ISSUE TITLE
Some breadcrumbs lead astray

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1749]
## Description
The breadcrumbs for "Call assignments" and "Surveys" lead to weird places. They should be removed entirely.

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/projects
2. Click on Activities
3. Click on any survey or call assignment
4. In the breadcrumbs, click "Surveys" or "Call assignments"

### Expected Behaviour
Should lead to someplace useful.

### Actual Behaviour
Leads to a 404, because there is no page at the paths that represent those breadcrumbs.

## Proposed solution
Change the breadcrumbs backend code to ignore these paths, similar to how it's been solved for lists.

**Comment by annafock** [comment]
I'm looking in to this one
