### ISSUE TITLE
Add ellipsis menu for deleting a participant from event

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1760]
## Description
A user should be able to delete a participant from an event. This used to be possible in Gen2. Currently in Gen3 however, it's only possible to "cancel" their participation, which used to be the main reason for removing participants in Gen2. But it turns out, sometimes a user will accidentally add a participant, and then they should be able to fully delete them.

## Relevant Job Stories
None

## Estimated size (S, M, L)
I think this issue is medium because although it's not technically complicated, it does require a couple of patterns be implemented, including changes to a hook and the store, and UI.

## Prerequisites
None

## Requirements
- [ ] There should be an ellipsis menu for each participant in the participants list
- [ ] In the ellipsis menu, there should be a delete option
- [ ] Clicking the option should remove the participant 

## Possible implementations
See the caller list under call assignments for how to implement an ellipsis menu.

The API for deleting a participant is `DELETE /api/ogs/{org_id}/actions/{event_id}/participants/{person_id}`.

## Design specifications
There is no design for this, but the ellipsis menu should be added at the rightmost edge of the table under "Booked Participants":

![image](https://github.com/zetkin/app.zetkin.org/assets/550212/c6824be0-b25d-4433-989e-fdc6f91f3251)

There's a similar pattern for callers under "Call assignments", see the ellipsis menu to the right of the "CUSTOMIZE" button:

![image](https://github.com/zetkin/app.zetkin.org/assets/550212/dc794f3b-98a3-4691-b963-de9b54ed8078)

## Open questions
None

**Comment by richardolsson** [comment]
Maybe the ellipsis menu should actually only be under "Cancelled", that way we don't have to worry about fitting it next to all of the other attendance buttons (cancelled, no-show, attended). It does mean the user could only delete a person after cancelling them, but that might make some sense. The user flow would then be:

1. Add participant by mistake
2. Click "Cancel" on that participant
3. Scroll down to list of cancelled participants and use the ellipsis menu to delete

**Comment by richardolsson** [comment]
Actually, come to think of it, maybe we don't even need an ellipsis menu if we just put a "delete" button on every participant under "Cancelled"?

**Comment by kaulfield23** [comment]
I agree! If there is only one menu in ellipsis, I see no point to make it.
