### ISSUE TITLE
Project is not being included in breadcrumbs

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1771]
## Description
The project that an event or other project activity belongs to is being excluded from the breadcrumbs.

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/projects/1/calendar
2. Navigate to any event in the calendar (or create a new one)
3. Compare URL to breadcrumbs

### Expected Behaviour
Since this event is in project 1, the name of that project should be visible in the breadcrumbs.

### Actual Behaviour
Breadcrumbs does not include the project.

## Screenshots (if you have any)
None

**Comment by ajoensson** [comment]
I'll take a look!

**Comment by richardolsson** [comment]
This used to work, so it is a regression somewhere, probably in `pages/api/breadcrumbs.ts`.

**Comment by ajoensson** [comment]
It was! I have a fix that I'll post soon!
