### ISSUE TITLE
Importer: unable to select xslx file for import on macOS

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#1776]
**Please be as thorough as possible, but if you can't answer everything, please just submit what you have! Thank you!**

## Description
This needs to be investigated further. When attempting to import an xslx file by selecting from local files, the local xlsx files where not possible to select. 

## Steps to reproduce
1. Go to /people
2. Select "import people" from the top right corner button
3. Attempt to upload a file by selecting from your local files (aka not dragging-dropping)

### Expected Behaviour
xslx files are possible to select

### Actual Behaviour
xslx files not possible to select

## Screenshots (if you have any)
![bild](https://github.com/zetkin/app.zetkin.org/assets/58265097/815763be-ebe9-4fe2-a25c-df4eb407df1b)

**Comment by joe-irving** [comment]
This is the same on Ubuntu for CSV files

Suggests the upload popup is restricted to .xls only

The can be dragged in from external file manager

**Comment by richardolsson** [comment]
What browser @joe-irving?

I investigated this quite thoroughly the other day, and it seems like there is a problem with the library we use, in combination with modern Chrome on OSX. The problem isn't actually with Chrome, but is triggered on Chrome because of how the library is programmed.

**Comment by joe-irving** [comment]
I am using Chromium Version 121.0.6167.160 (Official Build) snap (64-bit)
