### ISSUE TITLE
Importer: items in the "Import as" dropdown are not in order

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#1777]
**Please be as thorough as possible, but if you can't answer everything, please just submit what you have! Thank you!**

## Description
When selecting what to import a field as, the items in the dropdown "Import as" is not sorted in any meaningful way. I would be easier to overview if it had some sorting logic.

## Steps to reproduce
1. Go to `/people` and select "import people" from the top right corner button
2. Select a file and load it
3. When you are in the Configure stage - open the "import as" dropdown

### Expected Behaviour
The items in the dropdown are sorted in a way that make them easy to overlook and pick from

### Actual Behaviour
The items are in no order at all

## Screenshots (if you have any)
![bild](https://github.com/zetkin/app.zetkin.org/assets/58265097/ab72c904-bd0d-409b-bd88-3a8f801aa4f7)

## Suggested solution
Group the items into: ID, fields (native + custom together) and "other" (tags, orgs). Sort alphabetically on the translated title within each group.

**Comment by 262871** [comment]
Hi, I'd like to work on this issue.

**Comment by 262871** [comment]
Should there be dividers in the drop-down between the different sorted sets of labels? (sketch below)
![zetkin sorted dropdown](https://github.com/zetkin/app.zetkin.org/assets/61919302/5ab19a17-e970-40ad-bcf1-513a567348b7)

**Comment by richardolsson** [comment]
> Should there be dividers in the drop-down between the different sorted sets of labels? (sketch below)

Great question! I think the best solution would be to use the [MUI `ListSubheader` component](https://mui.com/material-ui/react-select/#grouping). Search for other occurrences of it in the codebase for examples of how that might work.
