### ISSUE TITLE
Importer: wrong format when parsing phone numbers

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#1781]
## Description
The frontend uses the wrong format for phone numbers when parsing them and sending to the backend. This results in it seeming that a lot of phone numbers are changed when they are not. 

## Steps to reproduce
1. Make a file of people who exist in zetkin, inclluding their phone numbers preferablly formatted in different ways (f.ex. 0700000000, +46 70 000 00 00, +46700000000)
2. Import this file, selecting to import phone numbers as phone number in Zetkin
3. Go to the validate step

### Expected Behaviour
There is no warning, as phone numbers have not been changed

### Actual Behaviour
You get a warning that a lot of phone numbers will get updated

## Screenshots (if you have any)
![bild](https://github.com/zetkin/app.zetkin.org/assets/58265097/845d024f-28d3-44a0-ad68-6336a4f5cb99)

## Suggested solution
Use "E.164" as the format for phone numbers in  `prepareImportOperations()`

**Comment by Logicbloke** [comment]
I'll start working on this.

**Comment by Logicbloke** [comment]
I could not reproduce this issue. Exported one of the lists that was already on the system and made changes to the phone number field of one of the rows, and it got picked up as "1 updated", then I added a country code (changed from `0727001122` to `+46727001122` and it said that the import will have no effect, then I changed to a format with spaces in it `+46 727 00 11 22` and once again it said no changes are expected after trying the reimport.
