### ISSUE TITLE
Loading /projects in an org with many events is much too slow

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1787]
## Description
The /organize/ID/projects page loads all projects and their events before rendering, making the time to load and render very slow. This is very obvious in organizations that have used Zetkin a long time.

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/projects
2. Wait for first render

### Expected Behaviour
Should be super fast

### Actual Behaviour
Takes a long time, because all events need to be loaded.

## Screenshots (if you have any)
<img width="349" alt="image" src="https://github.com/zetkin/app.zetkin.org/assets/550212/a8083a4e-9762-453c-8241-c6accf580117">

## Proposed solution
Don't load all events. This means that it won't be possible to render the dates in the project cards, but that's fine.

**Comment by awarn** [comment]
Looking at this!

**Comment by awarn** [comment]
Did the straight forward thing of just removing the events info, but it should be possible to load them without pausing initial render?
