### ISSUE TITLE
Lists: Survey option column does not have filters

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1788]
## Description
In lists, the "survey options" column type does not allow filtering. 

## Steps to reproduce
1. Go to localhost:3000/organize/1/people
2. Create a new list
3. In the new list, configure smart search with "Start with a list of all the people in the organization"
4. Click "+ NEW COLUMN"
5. Pick the "Single survey question" and pick any survey that contains a multiple-choice question
6. Pick a multiple-choice ("options") survey question
7. Pick "All Options (Single Column)" – this will create a `survey_options` type column
8. Click "FILTERS"
9. Open the "columns" dropdown

### Expected Behaviour
The dropdown should include the `survey_options` column you created. The operators should include "has", "does not have" and "is empty" similar to how filtering tag columns work under Journeys. The dropdown of values should include only the options that exist within the column.

### Actual Behaviour
The dropdown does not include the new column at all, because it does not have filtering enabled.

### How to reproduce (steps 6-7)
![image](https://github.com/zetkin/app.zetkin.org/assets/550212/042ad8c1-d7bc-4b55-a54b-ce51953cd949)

### Actual behaviour
![Screenshot 2024-02-17 at 14 04 45](https://github.com/zetkin/app.zetkin.org/assets/550212/9a133632-fdaf-4295-b955-6e8e629b3b85)

### Expected behaviour (from Journeys)
![image](https://github.com/zetkin/app.zetkin.org/assets/550212/92c3826f-acc6-409f-8493-53ae649a3320)

**Comment by KraftKatten** [comment]
This PR #1816 enables filtering, although it doesn't implement it the same as in the example from Journeys. Currently the filtering is using free-text to filter, but we want to select the options. But the current solution is good enough for now.
