### ISSUE TITLE
Nav: Org switcher chevron occluded when org title is long

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1797]
## Description
When the title of an organization is long, the header of the nav menu becomes too wide and pushes the chevron out of the frame so that it can't (easily) be clicked.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1 and log in
2. Change the name of the organization using a `PATCH /api/orgs/1` with `{ "title": "Organization With A Long Name" }`
3. Open the left hand side nav menu

### Expected Behaviour
The header should show the title with ellipsis, e.g. "Organization With A L…" followed by a downward-facing chevron.

### Actual Behaviour
The header shows the full name, or as much of it as fits within the container, and the chevron is hidden outside of the container.

## Screenshots
Note how the chevron is just barely visible (a few pixels of it) to the right of the organization name.

<img width="355" alt="image" src="https://github.com/zetkin/app.zetkin.org/assets/550212/7fd8fc0e-73e8-4e8a-8cd7-abe5ab3af799">

**Comment by ajoensson** [comment]
I'll have a look at this!
