### ISSUE TITLE
Organization selector filter too large, doesn't align

### ISSUE THREAD

**Issue by sefsh** [zetkin/app.zetkin.org#1799]
## Description
The input field for filtering for organizations in the selector in the sidebar is of a large size. The consequence is that toggling this menu makes the content jump around unnecessarily much.

## Steps to reproduce
1. Click on the dropdown icon button by the organization name in the sidebar menu.
2. Watch the button moving down with the new content.

### Expected Behaviour
![bild](https://github.com/zetkin/app.zetkin.org/assets/346211/414ebfaf-7f25-43e4-baeb-9442d1cbd9dd)

An text input field height such as this would align the input field and button of the filter widget.

### Actual Behaviour
![bild](https://github.com/zetkin/app.zetkin.org/assets/346211/091da0a4-82e9-4e55-8e6d-b5db5321821e)

**Comment by ajoensson** [comment]
I'll look into this at the same time as #1797
