### ISSUE TITLE
Journeys: Exception when sorting based on assignee with multiple assignees

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1804]
## Description
Under some circumstances an error will be thrown when trying to sort journey instances by assignee

## Steps to reproduce
1. Go to http://app.dev.zetkin.org/organize/1/journeys/1
2. Make sure there are instances with _more than one_ assignee
3. Click the "Assignees" column to sort it

### Expected Behaviour
The column should sort such that rows without an assignee appear together, and rows with assignees are sorted alphabetically.

### Actual Behaviour
An exception is thrown.

## Screenshots (if you have any)
![image](https://github.com/zetkin/app.zetkin.org/assets/550212/afed6cbb-fd34-4da6-a240-d6743fd9725f)

**Comment by ajoensson** [comment]
I think I found a solution! PR incoming.
