### ISSUE TITLE
Survey: Spelling mistake regarding activist portal

### ISSUE THREAD

**Issue by KraftKatten** [zetkin/app.zetkin.org#1814]
## Description
When viewing the screen for surveys, there is a link to the activist portal. In Swedish, there is an error in spelling.

![bild](https://github.com/zetkin/app.zetkin.org/assets/21238654/90f6ea3c-93ac-4fb7-8cbe-a91a72dff8f0)

## Steps to reproduce
1. Go to projects and activities -> activities -> choose an existing survey
2. View the right part of the screen (see image above)

### Expected Behaviour
The translation is "Visa enkäten i aktivistportalen"

### Actual Behaviour
The translation is incorrectly "Visa enkäten i aktivstportalen"

## Screenshots (if you have any)
![bild](https://github.com/zetkin/app.zetkin.org/assets/21238654/90f6ea3c-93ac-4fb7-8cbe-a91a72dff8f0)

**Comment by richardolsson** [comment]
Solving this issue is a matter of updating the string/translation at translate.zetkin.org, and then in the YAML files (which I can generate from translate.zetkin.org).

**Comment by kaulfield23** [comment]
Just fixed it!
![image](https://github.com/zetkin/app.zetkin.org/assets/77925373/312d08e7-8ae6-4f9e-bbfc-e83cab5a3a01)

**Comment by ziggabyte** [comment]
This is merged now so I am closing this issue :)
