### ISSUE TITLE
Exception in Smart Search dialog when displaying certain `survey_option` filters

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1817]
## Description
The `survey_option` Smart Search filter is configured with a list of the options the user wants to search based on. These IDs should be numbers, but are sometimes stored as strings, and when that happens (and also in other cases) the Smart Search dialog will crash when trying to display the summary of the filter.

## Steps to reproduce
1. Go to https://localhost:3000/organize/1/projects/1
2. Create a call assignment
3. Edit the targeting to use a filter "Based on options selected in a survey" and pick a survey, question and option
4. Save the Smart Search query
5. Browse to the API endpoint /api/orgs/1/call_assignments/<ID> (substitute for ID of the new assignment) and figure out the ID of the Smart Search query that makes up the `target` search
6. Make a "manual" API request to change the option ID to a string
7. Reload the page
8. Open the targeting Smart Search dialog again

### `fetch()` example to update query (step 6)
```
fetch("/api/orgs/1/people/queries/13630", {
  method: "PATCH",
  headers: { "Content-Type": "application/json" },
  body: JSON.stringify({
    filter_spec: [
      {
        id: "u3gPcypnV6",
        op: "add",
        type: "survey_option",
        config: {
          survey: 604,
          options: ["14725"], // <-- this needs to be a string
          operator: "any",
          question: "4873",
          organizations: "all",
        },
      },
    ],
  }),
});

```

### Expected Behaviour
Should render the dialog as before.

### Actual Behaviour
Crashes with an exception.

## Screenshots (if you have any)
![image](https://github.com/zetkin/app.zetkin.org/assets/550212/e3ec21df-5054-4d9b-8b14-97ec5e6b4ddb)
![image](https://github.com/zetkin/app.zetkin.org/assets/550212/a060799d-7ef2-4656-abe3-1a27b22530fa)

**Comment by awarn** [comment]
Looking at this.
