### ISSUE TITLE
Server error when idle on user pages

### ISSUE THREAD

**Issue by kristofferlarberg** [zetkin/app.zetkin.org#182]
A server error occurs instead of redirecting to login when you're idle on a user page and try to reload. 

Steps to reproduce:

1. Login
2. Go to `/my`
3. Let session run out
4. Reload page

Expected result: Redirection to login page
Actual result: 
![Skärmavbild 2021-05-18 kl  10 20 32](https://user-images.githubusercontent.com/51208557/118991408-0378c480-b984-11eb-8b35-b5bb6b618a7d.png)

**Comment by richardolsson** [comment]
Closing as this has become irrelevant.
