### ISSUE TITLE
Redirect / to /organize

### ISSUE THREAD

**Issue by joe-irving** [zetkin/app.zetkin.org#1826]
## Description

When getting new organisers into Zetkin gen 3, it has been tricky to describe the process of logging in. Logging in has actually been one of the biggest onboarding issues for the platform so far

## Steps to reproduce
1. Go to app.zetkin.org

### Expected Behaviour

1. Go to app.zetkin.org
2. Get directed to app.zetkin.org/organize
3. Log in
4. Organise some amazing things

### Actual Behaviour

1. Go to app.zetkin.org
2. Try to work out how to log in
3. Get lost
4. Give up on Zetkin and the left

### Suggested solution

Add temp redirect on next release to /organize if possible. I think adding this line in the root page would  work 

```ts
redirect("/")
```

but i don't know Next that well. Thank you xx

**Comment by richardolsson** [comment]
I'm fine with making this change, as long as we mark it as a temporary redirect (HTTP 302 Found, not HTTP 301 Moved Permanently). Once we have the activist portal in Gen3, it will live here (with easy to find links for organizers to log in).

**Comment by kizouker** [comment]
I'm on it
