### ISSUE TITLE
Import: Reduce unnecessary clicks when configuring columns

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1827]
## Description
A user should not have to make unnecessary clicks when configuring the columns of an import. Currently, some mapping types (ID, tags and organizations) require additional configuration after picking the column type

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/people
2. Click on "Create" in top right
3. Click on "Import people"
4. Drag and drop example file, e.g. [Example file.xlsx](https://github.com/zetkin/app.zetkin.org/files/14612779/Example.file.xlsx)
5. Click the checkmark next to "Member ID"
6. In the dropdown, select "ID"

### Expected Behaviour
The text "You need to configure the IDs" should appear, together with a "CONFIGURE >" button. At the same time, the configuration should open automatically on the right-hand side (where it says "Start by mapping file columns".

### Actual Behaviour
The text "You need to configure the IDs" appears, together with a "CONFIGURE >" button that the user needs to click in order to open the configuration. The user shouldn't be required to click this button in order for the configuration to appear on the right.

### Step 6
![image](https://github.com/zetkin/app.zetkin.org/assets/550212/55d197ed-b999-45f2-b445-5c1e75467f9b)

### Actual behaviour
![image](https://github.com/zetkin/app.zetkin.org/assets/550212/0d459dd3-c0bf-4f9a-a7c4-970745b6b7fc)

**Comment by velix** [comment]
Started working on this
