### ISSUE TITLE
Smart Search - Translation error - Survey options doesn't show the name of the survey in Swedish

### ISSUE THREAD

**Issue by KraftKatten** [zetkin/app.zetkin.org#1852]
## Description
The translation of the survey name doesn't include the variable tag.

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/people
2. Click on "create list"
3. In the bottom right, press configure on the Smart Search
4. Click on "Add / Remove people"
5. Scroll down to "Surveys" and click on the third option, "Based on the options [...]"
6. Ensure your browser is in Swedish
7. Select some survey

### Expected Behaviour
We want to see the name of the survey when viewing Zetkin in Swedish

### Actual Behaviour
We don't see the name of the selected survey in Swedish.

## Screenshots (if you have any)
![bild](https://github.com/zetkin/app.zetkin.org/assets/21238654/6bf5628b-70d3-420d-953c-741cd982a4c7)

**Comment by kaulfield23** [comment]
I found missing curly brackets in translation. So I added some to `feat.smartSearch.filters.surveyOption.surveySelect.survey` , `feat.smartSearch.filters.surveyOption.questionSelect.question` in swedish translation. I believe this bug will be fixed once it is converted to yml file! 

![image](https://github.com/zetkin/app.zetkin.org/assets/77925373/0164eb6b-9888-4c4c-8397-8a29d57ba9bd)

**Comment by richardolsson** [comment]
Fixed by #1869
