### ISSUE TITLE
Breadcrumbs flickers

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1862]
## Description
Breadcrumbs are invalidated (and if visible, reloaded) objects are updated. This is fine, but the problem right now is that the breadcrumbs are hidden while loading. This causes breadcrumbs to flicker.

## Steps to reproduce
1. Go to some page where titles (or anything) can be edited, e.g. https://app-zetkin-pfvx6yn5n-zetkin.vercel.app/organize/1/projects/standalone/surveys/1
2. Click on the title to edit it
3. Make any change

### Expected Behaviour
The title should change, including in the breadcrumbs. The breadcrumbs should be continuously visible and just update. All other parts of the UI should be standing still.

### Actual Behaviour
The title changes, including in the breadcrumbs, but not until after the breadcrumbs have been hidden for a short while. This flickering causes the page to reflow and all other parts of the UI to move up a few pixels and then down again.

## Screenshots
https://github.com/zetkin/app.zetkin.org/assets/550212/68f5218c-132d-409a-abda-074445192f0d

**Comment by richardolsson** [comment]
I feel like there are two things that need to change for this to work:

* While breadcrumbs are not visible, display something else (if only an empty container) that has the same height as a single-line breadcrumbs.
* Make sure the stale breadcrumbs remain visible while loading the up-to-date one. I'm not sure what's causing this not to be the case already, so more investigation will be required here.

**Comment by kaulfield23** [comment]
I was able to reproduce this bug on the `main` branch, but not on the `undocumented/email-smart-search`. I also tried it on the `epic/mass-email-mvp` and couldn't spot this bug there. I believe some fix in the `mass-email-mvp` unintentionally fixed this bug?

**Comment by richardolsson** [comment]
It looks like you're right @kaulfield23! Great work investigating this.

This was fixed by 87ad0e1db1b75a73228d337130694d689e83819e.
