### ISSUE TITLE
Import: Frontend allows ÅÄÖ in email, but backend doesn't

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1873]
## Description
When importing data, the frontend validation of email addresses allows ÅÄÖ, but the backend doesn't. This means that input can pass through client-side validation and be sent to the server, which then responds with an error message (that is not sufficiently presented to the user).

This is really two problems in one – the inconsistent validation on one hand, and the lacking error message on the other.

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/people
2. Click on Add
3. Click on "Import people"
4. Drop the following file which has an email address with åäö: [test.csv](https://github.com/zetkin/app.zetkin.org/files/14855185/test.csv)
5. Configure the import with first name, last name and email
6. Click "Validate"

### Expected Behaviour
One of two things would be acceptable:

* The validation step responds with a message saying that the email is invalid, which should happen on the frontend (similarly to how it responds if an email column contains something completely different than en email), or
* The error that comes back from the server should result in a message saying something along the lines of "an unknown error occurred during validation"

### Actual Behaviour
From the point of view of a normal user, nothing happens (the button seems unrespsonsive). What actually happens is that a request is made to the bulk preview API, which responds with 404, and that error is not in any way communicated to the user (except in development where it may throw an exception).

```json
{"data":{"error":{"message":"Unable to create op from person.import"}}}
```

## Screenshots
None

**Comment by dev-di** [comment]
I want to give this a try
