### ISSUE TITLE
Dropdown titles too long in Smart Search editor

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1877]
## Description
When editing a Smart Search filter, survey questions, titles, or anything else that can be selected in a dropdown can be so long that the UI becomes unusable.

## Steps to reproduce
1. Go to any survey
2. Add a question that has a really long title
3. Go to anywhere a Smart Search can be edited
4. Open the Smart Search dialog
5. Add another filter to reference the question (depending on what type of question it was)
6. Select the survey
7. Select the question

### Expected Behaviour
The question should be part of the sentence, but if it's really long it should be truncated with ellipsis (…).

### Actual Behaviour
The full question is displayed, rendering the UI useless because other important parts of the UI are cropped out of view.

## Screenshots (if you have any)
![image](https://github.com/zetkin/app.zetkin.org/assets/550212/4dfe9177-8944-449d-86e4-ff1086457a5b)

## Proposed solution
I think we should truncate all instances of the `StyledSelect` component.

**Comment by jularboolean** [comment]
I'm on the case!
