### ISSUE TITLE
Call assignments: Wrong numbers in call assignments in acitvity overview

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#1894]
**Please be as thorough as possible, but if you can't answer everything, please just submit what you have! Thank you!**

## Description
The numbers displayed in the call assignment cards in the activity overview does not make sense
Related: look at the other cards of the other types of activity, they may or may not be wrong in similar ways

## Steps to reproduce
1. Make sure there is a call assignment with calls made
2. Go to the acitvity overview
3. Look at the card that represents that call assignment
4. Go to the call assignment and look at the numbers in the overview tab

### Expected Behaviour
The numbers match

### Actual Behaviour
The numbers don't match

## Screenshots (if you have any)
The card in the acitivty overview:
![bild](https://github.com/zetkin/app.zetkin.org/assets/58265097/492bed28-5e93-4a58-9a36-8063dcda06ef)

The overview page on the same call assignment: 
![bild](https://github.com/zetkin/app.zetkin.org/assets/58265097/d610750c-e525-4fd2-a3bd-c0716418143a)

**Comment by richardolsson** [comment]
I don't believe this is a bug. The number 3 in the activity overview refers to the number of phone calls that have been made in the call assignment. That number is also visible on the call assignment page in the subtitle (not pictured in the screenshots in the issue). The equality between that number 3 and the number 3 next to "Blocked" in the second screenshot is a coincidence.

@ziggabyte: If you agree, please close this issue.

**Comment by ziggabyte** [comment]
Confirmed that this is not a bug :)
