### ISSUE TITLE
Moving events to another project

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1901]
## Description
A user should be able to move an event to another project. This could also make sense for other activities.

## Relevant Job Stories
None

## Estimated size (S, M, L)
I think this issue is medium because it's just a matter of changing `campaign_id´ on the event/action, but there is currently no design so we don't know exactly how to implement it.

## Prerequisites
Design

## Requirements
- [ ] It should be possible to move an event from one project to another

## Possible implementations
Unknown

## Design specifications
<img width="784" alt="image" src="https://github.com/zetkin/app.zetkin.org/assets/346211/76974308-774c-4dcb-a46f-be38f6cc9eea">

—

<img width="689" alt="image" src="https://github.com/zetkin/app.zetkin.org/assets/346211/8934d37e-9557-4993-8f5c-cf65a5147f74">

—

<img width="678" alt="Screenshot 2024-06-05 at 16 45 52" src="https://github.com/zetkin/app.zetkin.org/assets/346211/26c90621-b68c-4265-8563-e2c369d02e30">

—

<img width="700" alt="image" src="https://github.com/zetkin/app.zetkin.org/assets/346211/317d4e54-c0fc-4ff2-b96c-13b921f1c4cd">

—

![image](https://github.com/zetkin/app.zetkin.org/assets/346211/d4770663-cc78-44a6-b06c-d6c0633989a1)

—

### Flow 1
1. The new action __Move__ is added to the ellipsis menu.
2. This action opens a modal populated with all other projects in the organization
  - Same sorting of items as in project overview ("All Projects & Activities")
  - Hovering an item highlights the row
3. Clicking Move hides all buttons and displays the loader in the clicked button's location and initiates the move action.
4. When the move has been performed the event is loaded in its new project location
(5. If possible a snackbar is displayed "Event moved to [$new_project_name])

—

<img width="690" alt="image" src="https://github.com/zetkin/app.zetkin.org/assets/346211/2f2b5375-86c0-4c58-9848-121db57662f0">

### Flow 2
1. _same as in flow 1_
2. _same as in flow 1_
3. Typing in the textfield immediately filters the project list only to include matching names
4. Clicking Move hides all buttons and displays the loader in the clicked button's location and initiates the move action.
5. When the move has been performed the event is loaded in its new project location
(6. If possible a snackbar is displayed "Event moved to [$new_project_name])

## Open questions
TBD

**Comment by awarn** [comment]
Looking at this
