### ISSUE TITLE
Email: Blinking editor

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#1906]
**Please be as thorough as possible, but if you can't answer everything, please just submit what you have! Thank you!**

## Steps to reproduce
1. Go to the compose tab of an email
2. Write in the editor
3. Press enter key to create new text block
4. write some more

### Expected Behaviour
The editor stays still

### Actual Behaviour
The editor blinks and shakes a little when you write and press enter key (it seems to be re-loading or re-mounting)

## Screenshots (if you have any)
https://github.com/zetkin/app.zetkin.org/assets/58265097/1d58d058-20e9-4b8b-b041-d2befa485403

**Comment by ziggabyte** [comment]
I feel a bit underequipped to look at this myself, would love a bit of thinking-together with @richardolsson to see if we can come up with some potential solutions for this.

**Comment by richardolsson** [comment]
> I feel a bit underequipped to look at this myself, would love a bit of thinking-together with @richardolsson to see if we can come up with some potential solutions for this.

I'm sorry I couldn't get back to you today. Would love to look at it together! But lets revisit that later and focus on other things for the next few days.
