### ISSUE TITLE
Person tag in smart search displays a different sentence when editing

### ISSUE THREAD

**Issue by kaulfield23** [zetkin/app.zetkin.org#1918]
## Steps to reproduce
1. Go to any call assignment for example 'http://localhost:3000/organize/1/projects/5/callassignments/4'
2. Click on 'Define group target'
3. Click on 'Add/Remove people'
4. Click on 'Based on their tags' in 'People' section
5. Change condition to 'any' so the whole sentence will be 'Add people with any of the following tags : `tag`'
6. Click on 'Save selection'
7. Click on Edit icon of the newly created sentence
8. Now the sentence has changed to 'Add people with at least 1 of the following tags : `tag`'

### Expected Behaviour
The sentence should be the same as we set
### Actual Behaviour
The sentence has changed

## Screenshots 

https://github.com/zetkin/app.zetkin.org/assets/77925373/c1518b62-1c9b-4911-96cf-2055b5274054

Note that the request has changed as well.
- Before edit
![image](https://github.com/zetkin/app.zetkin.org/assets/77925373/227f9b00-fe8a-46c0-ba5a-67b0d088f5aa)
- After edit
![image](https://github.com/zetkin/app.zetkin.org/assets/77925373/2d82e036-2f93-4e2c-bf0a-e73a4d0ec65e)

**Comment by kizouker** [comment]
I'm on this
