### ISSUE TITLE
Try migrating user home layout to MUI

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#193]
We are considering migrating away from the Adobe Spectrum UI framework (#148) and would like to try [Material UI](https://material-ui.com) instead.

As a trial of the MUI library, we should try to migrate the /my set of pages to MUI, especially the layout (#20) which was difficult (impossible) to implement nicely using Adobe Spectrum.

There is a [`<BottomNavigation>`](https://material-ui.com/components/bottom-navigation/) component in Material UI that might be useful for this.

**Comment by djbusstop** [comment]
Closed because MUI removed, and all tasks to implement user pages assume use of MUI
