### ISSUE TITLE
Import: Not possible to import External ID using Zetkin IDs as the key

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1935]
## Description
A somewhat common pattern will be for users to export a list from Zetkin, populate it with external IDs (e.g. member IDs) and then import that list back. That's currently not possible, because it's not possible to map both Zetkin ID and External ID to (different) columns.

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/people
2. Click on "Create..."
3. Click on "Import people"
4. Import a file that contains at least two columns
5. Map the first column to Zetkin ID
6. Map the second column to External ID

### Expected Behaviour
It should be possible.

### Actual Behaviour
The "ID" option is disabled in the drop-down, because it has already been configured as Zetkin ID.

## Screenshots (if you have any)
N/A

**Comment by Bagera** [comment]
I think @sefsh would be best for the design work here, as he designed the importer flow.

**Comment by richardolsson** [comment]
Are you working on this @sefsh?

**Comment by remipou** [comment]
looking into it (if it doesn't require a backend change..)
