### ISSUE TITLE
Event: The default title of newly created event is empty string ("")

### ISSUE THREAD

**Issue by kaulfield23** [zetkin/app.zetkin.org#1937]
## Description
When I create a single event by dragging the mouse on the weekly view in the Calendar or by clicking "Create event" in the "Create Activity" button, the newly created event has default title ""(empty string) in database.
## Steps to reproduce -1
1. Go to any project. For example 'http://localhost:3000/organize/1/projects/11'
2. Click on 'Create Activity'
3. Click on 'Create Event' and check the event ID
4. Now check the data of newly created event. For example 'http://localhost:3000/api/orgs/1/actions/${eventId}'
## Steps to reproduce -2
1. Go to any project. For example 'http://localhost:3000/organize/1/projects/11'
2. Click on 'Calendar'
3. Click on 'Week'
4. Drag a mouse on random date and click on 'Create single event'.
5. Check the event ID
6. Now check the data of newly created event. For example 'http://localhost:3000/api/orgs/1/actions/${eventId}'

### Expected Behaviour
The default title of an event should be `null`
### Actual Behaviour
The default title is `""`
## Screenshots (if you have any)
![image](https://github.com/zetkin/app.zetkin.org/assets/77925373/a340046c-bbaf-4a3d-82a2-a335f7c485d6)
![image](https://github.com/zetkin/app.zetkin.org/assets/77925373/c6dbecd5-19bd-4c5a-b9c0-9128efbb0ef1)

**Comment by helihard** [comment]
Will be giving this a go!
