### ISSUE TITLE
Calendar: Changing dates of an event leaves duplicates in calendar

### ISSUE THREAD

**Issue by awarn** [zetkin/app.zetkin.org#1940]
## Description
When changing the dates on an event, a duplicate remains on the old timeslot in the calendar view.

Likely tied to frontend store issue, as the leftover duplicate event disappears when reloading the page.

## Steps to reproduce
1. Go to an event's editing view (such as /organize/[x]/projects/[y]/events/[z]), and make note of the start and end dates.
2. Go to the calendar view to make sure the event shows up.
3. Go back to the event's view and change the start and/or end dates. You might need to change them by an entire day to replicate the bug consistently.
4. Go back to the calendar view.

### Expected Behaviour
The event should only show up in the new timeslot.

### Actual Behaviour
The event shows up at both the new and old timeslots.

**Comment by richardolsson** [comment]
Thanks for reporting this! I'm wondering if this could be something introduced with #1857, which made changes to the relevant code, related to updating events in all of the places where it's stored in the store.
