### ISSUE TITLE
Event: Deleted event remains in calendar

### ISSUE THREAD

**Issue by kaulfield23** [zetkin/app.zetkin.org#1950]
## Description
A deleted event is still visible in the calendar.
## Steps to reproduce
1. Go to any single event. For example http://localhost:3000/organize/1/projects/19/events/${eventId}
2. Click on ellipsis menu right next to the 'PUBLISH' button.
3. Click on 'Delete'.
4. Go to Calendar. 

### Expected Behaviour
Deleted event should not visible in calendar

### Actual Behaviour
Still remains in calendar
## Screenshots (if you have any)

https://github.com/zetkin/app.zetkin.org/assets/77925373/f865a7f3-3ca7-4041-912d-0b0624bb7719

**Comment by helihard** [comment]
Will be giving this a go!
