### ISSUE TITLE
Event: Endless spinning circular progress in calendar day view.

### ISSUE THREAD

**Issue by kaulfield23** [zetkin/app.zetkin.org#1951]
## Description
Circular progress in calendar day view spins endlessly
## Steps to reproduce
1. Go to day view in calendar. For example, http://localhost:3000/organize/1/projects/7/calendar?focusDate=2024-05-13&timeScale=day

### Expected Behaviour
Spinner should disappear when loading is over
### Actual Behaviour
Spins endlessly
## Screenshots (if you have any)

https://github.com/zetkin/app.zetkin.org/assets/77925373/12f4eece-88c5-44f9-b2c6-76ad94c4974f

**Comment by richardolsson** [comment]
Not sure how complicated this is, but to investigate I would start by looking in the network panel whether multiple requests are being made, or if it's just one request that stalls, or if all requests finish fine and the UI just doesn't remove the loading indicator.

This could also very well be related to the issue that @helihard and @ziggabyte have been investigating, where they found that `isLoading` was not being reset properly when using `useEventsFromDateRange()`.
