### ISSUE TITLE
Event: Cancelled event changes to draft after clicking the scheduling calendar

### ISSUE THREAD

**Issue by kaulfield23** [zetkin/app.zetkin.org#1954]
## Description
In cancelled event when I click the 'Not visible or scheduled', the status 'cancelled' changes to 'draft'. 
## Steps to reproduce
1. Go to any cancelled event
2. Click on 'Not visible or scheduled'. Don't set any date. Just click outside of calendar box.

### Expected Behaviour
Event status should be remain cancelled.
### Actual Behaviour
Event status changes to draft
## Screenshots (if you have any)

https://github.com/zetkin/app.zetkin.org/assets/77925373/61012151-a59f-43e3-af33-ed9f7a63d391

**Comment by a-jaxell** [comment]
The same happens for an event that is published and then cancelled.


https://github.com/zetkin/app.zetkin.org/assets/97404672/93758707-b529-408b-bd4c-f3ab6730e41d

**Comment by a-jaxell** [comment]
When I played around with it a bit more i noticed that if an event is scheduled in the future, cancellation has no effect status icon.
It remains as 'Scheduled'.

**Comment by a-jaxell** [comment]
I have been looking a bit at the store with Redux DevTools and it seems that 
`events/eventUpdate` is dispatched with payload that sets the event status to `published` 

Im not too familiar to all the parts of the codebase yet. If someone could help me understand
what the this code does in the file linked below Id appriciate it. Because the bug disappears when i remove it 
and I cant see any other side effects.

```javascript
if (onChange) {
  onChange(value?.format('YYYY-MM-DD') ?? null);
}
```

[ZuiDatePicker.ts](https://github.com/zetkin/app.zetkin.org/blob/main/src/zui/ZUIDatePicker/index.tsx)
```typescript
...
      <ClickAwayListener
        mouseEvent="onMouseDown"
        onClickAway={() => {
          setAnchorEl(null);
          if (onChange) {
            onChange(value?.format('YYYY-MM-DD') ?? null);
          }
        }}
      >
...
```

**Comment by kaulfield23** [comment]
Hey @a-jaxell ! Thank you! I didn't know that it happens to other status except for 'draft' :) The value?.format('YYYY-MM-DD') is for converting date(Dayjs type) to string as '2024-05-17'.
```
if (onChange) {
  onChange(value?.format('YYYY-MM-DD') ?? null);
}
```
This converts the date picked from the daypicker to a string when the user changes the date!

**Comment by a-jaxell** [comment]
Thanks for explaining @kaulfield23 !

Ive been playing around a bit now and it seems that when I set a date in the picker, it will publish the event and set it to Open regardless if it is a draft, cancelled or previously

I have come up with one solution for this specific reported case for this bug but it seems that there is more under the surface.
