### ISSUE TITLE
List: Assigned avatar resets when double clicking the cell but does not update the cell

### ISSUE THREAD

**Issue by kaulfield23** [zetkin/app.zetkin.org#1956]
## Description
When I try to edit the assignee but decide not to update it, the avatar reset to default after clicking away.

## Steps to reproduce
1. Go to any list
2. Click on '+New column'
3. Click on 'Assigned Person' in 'Outreach' section
4. Set assignee to the cell
5. Double click the cell for edit mode
6. Don't set any new assignee. Just click outside of the popper

### Expected Behaviour
Assignee should be displayed in avatar
### Actual Behaviour
The avatar reset to default
## Screenshots (if you have any)

https://github.com/zetkin/app.zetkin.org/assets/77925373/e83a138e-59d0-40b0-925a-29db7840dafb

**Comment by richardolsson** [comment]
What happens when refreshing after doing this? Are any API requests made to actually clear the cell, or is it just a UI bug?

**Comment by kaulfield23** [comment]
It is just a UI bug. The assignee will be there after refreshing! @richardolsson
