### ISSUE TITLE
Survey : Unnecessary scroll in survey submission pane

### ISSUE THREAD

**Issue by kaulfield23** [zetkin/app.zetkin.org#1961]
## Description
There is unexpected scroll in submission pane
## Steps to reproduce
1. Go to any survey that has submissions to survey. For example http://localhost:3000/organize/1/projects/standalone/surveys/1/submissions
2. Click on any submission

### Expected Behaviour
No scroll when content is short
### Actual Behaviour
There is a scroll that can't be scrolled
## Screenshots (if you have any)
![image](https://github.com/zetkin/app.zetkin.org/assets/77925373/1d8dc3b2-eb19-435b-a3ee-15cf18867d58)

**Comment by henrycatalinismith** [comment]
On it. Obsessed with survey issues these days even if they're unrelated to the monster PR.
