### ISSUE TITLE
Clickable phone numbers in event participants list

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1973]
## Description
It should be possible to click phone numbers to initiate a call.

### Case A: Person hover card
1. Go to http://localhost:3000/organize/1/projects
2. Find any event with participants
3. Go to the participants tab
4. In the list of participants, click the phone number

### Case B: Event participants list
1. Go to http://localhost:3000/organize/1/projects
2. Find any event with participants
3. Go to the participants tab
4. In the list of participants, hover the person
5. Click the phone number

### Expected Behaviour
The device handling of phone links should trigger.

### Actual Behaviour
In the list, nothing happens, and in the hover card, there is a copy action bound to the phone number, so the number is copied to the clipboard.

## Screenshots (if you have any)
None

## Proposed solution
Use `tel:` links in both places. In the hover card, this means that the copy action needs to move, perhaps to it's own little button to the side of the number?

**Comment by MattettaM** [comment]
Giving this a go
