### ISSUE TITLE
"Projects & activities" page loads for >20 seconds in large organizations

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1974]
## Description
When there are a lot of old events in an organization, loading the projects page takes a very long time. This is probably because the page loads all the old events for some reason, which happens on the backend (`getServerSideProps()`).

## Steps to reproduce
1. Go to https://app.zetkin.org/organize/1/people (Vänsterpartiet Malmö on live, requires access)
2. Click "Projects & activities" in menu
3. Measure loading time

### Expected Behaviour
Should load quickly.

### Actual Behaviour
Takes 21s to load.

## Proposed solution
It looks to me like all events are loaded, which I see no reason for since only the upcoming events are relevant for the overview. Removing this line (and the lines that depend on it) should solve the problem.

https://github.com/zetkin/app.zetkin.org/blob/bd3ad4d4b13f9e07ec7a60c7279fa7ca0fa3ca19/src/pages/organize/%5BorgId%5D/projects/index.tsx#L33

**Comment by MattettaM** [comment]
Looking into it
