### ISSUE TITLE
Links do not show up in email smart search

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1975]
## Description
When a user tries to search for people who clicked specific links in an email that has been scheduled but not yet sent, those links do not appear in the Smart Search form (because they are not created until the email is actually sent). But there is nothing explaining that to the user.

## Steps to reproduce
1. Go to http://localhost:3000/organize/1
2. In any project, add an email
3. Configure targeting and lock targets
4. Add a subject line and some content (links not necessary to actually reproduce this)
5. Schedule the email to be delivered the next day
6. Go to http://localhost:3000/organize/1/people
7. Create a new list
8. Configure Smart Search
9. Add a filter for email links
10. Pick "any of the following links in the specific email" and select your email
11. Open the link dropdown

### Expected Behaviour
The list should be empty, but also include some sort of information that because the email has not yet been sent, you cannot yet pick the links.

### Actual Behaviour
Just displays "No matching links" which does not explain to the user that there might be links here later.

## Screenshots (if you have any)
![image](https://github.com/zetkin/app.zetkin.org/assets/550212/38dbe241-780e-4110-9e6d-b393f5b2810b)

**Comment by MattettaM** [comment]
Looking into this
