### ISSUE TITLE
Survey: Linking a respondent does not update anything in UI

### ISSUE THREAD

**Issue by kaulfield23** [zetkin/app.zetkin.org#1979]
## Steps to reproduce
1. Go to any survey that has anonymous submissions. For example, http://localhost:3000/organize/1/projects/11/surveys/10/submissions
3. Click on 'Link' in anonymous submission row
4. Assign random person
5. Try to unlink as well

### Expected Behaviour
Selected person should be linked and the cell should display an avatar
### Actual Behaviour
Nothing happens. So does when unlinking.
The link is updated after refreshing the page.
## Screenshots (if you have any)

https://github.com/zetkin/app.zetkin.org/assets/77925373/f370422d-0869-4562-b73a-8a3b919cbbc0

### Note that it updates `submissionList` in store
![image](https://github.com/zetkin/app.zetkin.org/assets/77925373/5ea83ca6-26f4-4559-809e-dce291aa7d04)

**Comment by richardolsson** [comment]
Fixed by #2040
