### ISSUE TITLE
Activites in the Day view of the calendar are not sorted by time

### ISSUE THREAD

**Issue by MattettaM** [zetkin/app.zetkin.org#1993]
## Description
When looking at activities in the Calendar Day view the events are not always sorted by time, but are instead sorted by the time that they were created I am guessing.

## Steps to reproduce
1. Go to an ongoing project or create a new one.
2. Create a couple of activities, 3 or more, for the same day and time.
3. Change the time for one of the activity (the first one you created, just to be safe) to start and end an hour after the current time.
4. Change the time for another activity (the last one you created, just to be safe) to start and end an hour before the current time.
5. Go to the Calendar and go to the Day view.
6. Activities should be in order of time but are not.

### Expected Behaviour
Events in the Day view should be sorted by time.

### Actual Behaviour
Events in the Day view are displayed in a seemingly random order.

## Screenshots
![333803557-be650c5e-c4d0-4532-aaba-f6af721054b4](https://github.com/zetkin/app.zetkin.org/assets/14234034/186c1645-64d2-460b-aacb-443cbc29e97f)

**Comment by remipou** [comment]
i'll take this one
