### ISSUE TITLE
Make a link to public organization page available somewhere (e.g. access settings)

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#2006]
## Description
A user should be able to find a link to the public page of an organization somewhere and my proposal is to put it in the access settings page. In the future, it could also be made more readily available on the organization dashboard, but we don't have such a dashboard yet.

## Relevant Job Stories
* When I want to assign a new official in an organization, I want to be able to find a link to the public organization page and send it ot them, so that they can connect to the organization before I try to add them as an official

## Estimated size (S, M, L)
I think this issue is medium because it's very simple data and logic-wise, but I think it would make sense to try and do some simple design work in order to figure out where the link should go.

## Prerequisites
Before coding, we need to figure out where/how to present this link.

## Requirements
- [ ] Somewhere on the access settings page there should be a link to the public organization page that opens in a separate browser tab
- [ ] It should be easy to copy the URL, e.g. using a button similar to surveys

## Possible implementations
Copy the `SurveyURLCard` component.

## Design specifications
There is no specification at this point, but I think it can be up to the coder to figure this out. One idea I have is to put it in it's own right-hand-side column similar to how public survey links are presented.

## Open questions
* What should it look like? To be proposed by assignee.

**Comment by kaulfield23** [comment]
I tested things and placed the url card on the right side like the survey. I wonder how this looks to you @richardolsson and is the URL right in this screenshot??
![image](https://github.com/zetkin/app.zetkin.org/assets/77925373/d75d383f-7c4b-49bc-a72f-abe6f584acc6)

**Comment by richardolsson** [comment]
That looks great!
