### ISSUE TITLE
Imports: Can only import organizations from one column

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#2013]
## Description
It's currently only possible to import organizations from a single column, even though there is nothing technically preventing the case of a single file having multiple columns that represent organization membership.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/people
2. Click on "Create…"
3. Click on "Import people"
4. Drop any CSV file (e.g. example below) with at least 2 columns
5. For the first column, pick "Organizations" as the target
6. For the second column, pick "Organizations" again

### Example CSV
```csv
ID,FIRST NAME,LAST NAME,CHAPTER,NETWORK
1,Clara,Zetkin,Leipzig,Feminist network
```

### Expected Behaviour
Picking organizations again should be allowed, and mapping values to organizations in both columns should result in organizations from both columns to be included when producing the final output (while avoiding duplicates).

### Actual Behaviour
It's not possible to pick "Organizations" again in step 6, because it will have been disabled.

## Screenshots (if you have any)
![image](https://github.com/zetkin/app.zetkin.org/assets/550212/72cb1aba-f21a-4c86-b2f5-c948b46c9938)

## Proposed solution
This will probably affect several parts of the import system:

* The `optionAlreadySelected()` function in `useColumn()` will need to be updated
* The `prepareImportOperations()` function may need to be updated in order to support collecting organization IDs from several columns
* The `usePersonPreview()` function may need to update in order to collect organizations from multiple columns

**Comment by katjam** [comment]
Can someone please assign this issue to me?
