### ISSUE TITLE
Phone numbers entered without country code cannot be saved in edit person dialog

### ISSUE THREAD

**Issue by helihard** [zetkin/app.zetkin.org#2019]
## Description
In the Gen3 version of Edit Person, it is not possible to save a new or edited phone number unless it has a country code, for example +46. National phone numbers, for example 0733123457, are validated as invalid. 

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/people/2
2. In the Gen3 version which handles Edit Person in-gen (without redirecting to Gen2), click on "Edit details"
3. Enter a valid phone number without a country code, for example 0733123457, in the "Phone Number" or "Alternate Phone Number" field.
4. (Enter a valid phone number with country code, for example +46733123457, to see difference in behaviour)

### Expected Behaviour
A valid national phone number should be validated as valid. The number could either have a suitable country code added on blur or on save without action needed from the user, or the user could be prompted to pick a country code (by the validation warning or from a drop down menu or similar).

### Actual Behaviour
The phone number is validated as invalid, preventing the user from saving data.

## Screenshots

https://github.com/zetkin/app.zetkin.org/assets/143598480/a0b7c4d0-907f-46ea-9f3a-32e5d76f52e8

**Comment by neta-kedem** [comment]
Hi, I've made a [PR](https://github.com/zetkin/app.zetkin.org/pull/2131) that adds default country code to the form, is this the right way to solve this? (also it's my first PR here so not sure about the process)
