### ISSUE TITLE
Edit Person: Cannot type space at end of value

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#2030]
## Description
Something is preventing me from typing a space in a field in the "Edit person" dialog. Probably this is because of some sort of trimming of the state instead of trimming it at the time of submission.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/people/19
2. Click on "Edit Details"
3. Focus the Address Field
4. Type "123 Main St" (1, 2, 3, space, M, a, i, n, space, S, t)

### Expected Behaviour
The field should say "123 Main st".

### Actual Behaviour
The field says "123MainSt" because the spaces were ignored. Going back and adding the spaces in the middle works as a workaround.

## Screenshots (if you have any)
![image](https://github.com/zetkin/app.zetkin.org/assets/550212/dfb51a2b-a103-4f85-803f-ae2fe559235c)

**Comment by kaulfield23** [comment]
This looks interesting, Can I take it if it doesn't need to be fixed asap?

**Comment by richardolsson** [comment]
Sure, have a go!
