### ISSUE TITLE
Duplicates: Person excludable even if there's only two in the list

### ISSUE THREAD

**Issue by sefsh** [zetkin/app.zetkin.org#2032]
## Description
The merge duplicates feature need at least two people to be able to merge something. Thus exclude buttons should be hidden whenever the duplicates only involves two people.

## Steps to reproduce
1. Go to /people/duplicates
2. Click Resolve on a detected duplication involving two people

### Expected Behaviour
Exclude buttons not present when not needed.

### Actual Behaviour
Exclude buttons are still present

## Screenshots (if you have any)
![bild](https://github.com/zetkin/app.zetkin.org/assets/346211/ca4f02a1-6d6c-47d2-9a4c-ef26f74d5871)

**Comment by richardolsson** [comment]
When solving this, it's important to differentiate between a potential duplicate that has exactly two people in it, and a duplicate that has more than two people. A duplicate with exactly two people should never allow excluding.

But when there are three or more people in the potential duplicate, we should allow excluding all of them temporarily. The user should be able to exclude all three, and then add back any two of them. In the meantime (while the number of included people is less than two) the "MERGE" button should be disabled.

**Comment by remipou** [comment]
looking into it
