### ISSUE TITLE
Duplicates: Wrong modal margins

### ISSUE THREAD

**Issue by sefsh** [zetkin/app.zetkin.org#2033]
## Description
- Some outer margins on the duplicates modal have the wrong value.

## Steps to reproduce
1. Go to /people/duplicates
2. Click on a Resolve button

### Expected Behaviour
<img width="258" alt="bild" src="https://github.com/zetkin/app.zetkin.org/assets/346211/f557d72a-b3ac-4b95-979e-e40666b0a2b5">

### Actual Behaviour
<img width="364" alt="bild" src="https://github.com/zetkin/app.zetkin.org/assets/346211/37e91f51-111c-43d5-a94b-60083e09947f">

**Comment by helihard** [comment]
I'm on to this!
