### ISSUE TITLE
Duplicates: Medium-sized select components are used instead of small

### ISSUE THREAD

**Issue by sefsh** [zetkin/app.zetkin.org#2034]
## Description
In the data table, medium-sized select (dropdown) components are used instead of small, which increases row height. 

## Steps to reproduce
1. Go to /people/duplicates
2. Click a Resolve button

### Expected Behaviour
All data table rows to have equal height, by select/dropdowns **size to be small rather than medium**.

### Actual Behaviour
Select/dropdown components adds extra row height.

## Screenshots (if you have any)
![bild](https://github.com/zetkin/app.zetkin.org/assets/346211/ce41abd9-db83-4857-91b9-41f9a0282d91)

**Comment by helihard** [comment]
Giving this a go!
