### ISSUE TITLE
Edit person: 16px too much margin on the right

### ISSUE THREAD

**Issue by sefsh** [zetkin/app.zetkin.org#2035]
## Steps to reproduce
1. Go to a person page
2. Click on Edit details

### Expected Behaviour
Equal outer margins on content.

### Actual Behaviour
Extra 16px outer margin on the right of content.

## Screenshots (if you have any)
<img width="319" alt="bild" src="https://github.com/zetkin/app.zetkin.org/assets/346211/d0c0bf75-1d8f-499f-aca3-1d6e58a52070"> 
<img width="327" alt="bild" src="https://github.com/zetkin/app.zetkin.org/assets/346211/1150703c-ff6b-4f5d-8378-2b675698bfd3">

**Comment by helihard** [comment]
I'm on to it!
