### ISSUE TITLE
Smart search: Sub-organization dropdown menu dropdown limited in width, breaks option lines into more than one

### ISSUE THREAD

**Issue by sefsh** [zetkin/app.zetkin.org#2036]
## Steps to reproduce
1. Go to Lists
2. Click on a list
3. Click on kebab menu 
4. Choose Edit smart search query
5. Edit any filter that's not the starting filter
6. Use the dropdown in "Search in…" section to choose "Specific organizations"
7. Open the second dropdown

### Expected Behaviour
For the menu to expand horizontally to be able to host the text of all options on one line each.

### Actual Behaviour
The menu has a limited width forcing options to wrap text into several lines.

## Screenshots (if you have any)
<img width="291" alt="bild" src="https://github.com/zetkin/app.zetkin.org/assets/346211/54e09b76-4246-47af-9548-818cf3952191">

**Comment by helihard** [comment]
Giving this a go!
