### ISSUE TITLE
Tags: Submit button says "Create" even when editing existing tag

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#2039]
## Description
When editing an existing tag, either from the tag select widget, or from the new tags page, the submit button of the edit tag dialog says "Create" or "Create and apply" when it should say "Update" or "Save" or something like that.

### Case 1
1. Go to https://app.dev.zetkin.org/organize/1/people/2
2. Click on "Add tag"
3. Click the pencil on any tag to edit

### Case 2
1. Go to https://app.dev.zetkin.org/organize/1/tags
2. Click on any tag

### Expected Behaviour
The submit button should say "Save" or "Update".

### Actual Behaviour
The submit button says "Create" or "Create and apply".

## Screenshots (if you have any)
![image](https://github.com/zetkin/app.zetkin.org/assets/550212/e56f3549-f803-4f1e-9bc0-d2e930675077)

**Comment by DaleLuce** [comment]
Im looking into this.

**Comment by richardolsson** [comment]
Fixed by #2202
