### ISSUE TITLE
Add NoSsr to Organize layout

### ISSUE THREAD

**Issue by nehahirve** [zetkin/app.zetkin.org#205]
since SSR is not helping us for the Organize pages -- 
1. no SEO as they are login pages
2. we don't need to fetch large amounts of data from the server and only render parts of it on the page

can wrap the pages in the MUI noSSR tag so they render only clientside

**Comment by richardolsson** [comment]
This is related to #238

**Comment by richardolsson** [comment]
We will need to rethink this. Closing, but a similar issue might come in the future.
