### ISSUE TITLE
Creating event from project calendar does not take project into account

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#2054]
## Description
Creating an event from inside a project calendar should create the event as part of that project, but instead creates it as a standalone event. This is a regression.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/projects
2. Pick any project
3. Go to the calendar tab
4. Go to the week view
5. Create an event by dragging in the calendar and picking "Create single event"

### Expected Behaviour
The event should be created as part of the project picked in step 2, and this should be indicated in the breadcrumbs (which should include the name of the project).

### Actual Behaviour
The event is created standalone, not part of any project, and the breadcrumbs therefor includes no project name.

## Screenshots (if you have any)
![image](https://github.com/zetkin/app.zetkin.org/assets/550212/b0ee2837-0a6f-473b-9ba5-aa0ab14a84eb)

**Comment by MattettaM** [comment]
Looking at this
