### ISSUE TITLE
ZUICopyToClipboard component is possibly redundant

### ISSUE THREAD

**Issue by helihard** [zetkin/app.zetkin.org#2055]
## Description
The ZUICopyToClipboard component seems to not be in use. (ZUIInlineCopyToClipBoard and ZUITextfieldToClipboard are used instead for various copying tasks.) 

ZUICopyToClipboard also seems to contain some less than ideal styling solutions (for example, several hard-coded values) and, when used, produces some less than desirable UI effects (such as, when paired with text instructions/a text component, overlapping of the copy icon with the text, and overlapping of the success message with the text, in some browser sizes). 

If arriving at the conclusion that the ZUICopyToClipboard component is indeed not in use or needed for future purposes, perhaps it could be deleted.

If used or needed, the component might benefit from refactoring.

**Comment by richardolsson** [comment]
Once #1756 has been merged, if `ZUICopyToClipboard` is still not used anywhere, it should be deleted.
