### ISSUE TITLE
No option other than approving incoming submissions, besides leaving them pending

### ISSUE THREAD

**Issue by helihard** [zetkin/app.zetkin.org#2056]
## Description

A user should be able to dismiss a pending application (under the "People" > "Incoming" tab). Preferrably either by clicking a button in the submission table proper, or by clicking a button in the individual submission pane, similar to the different ways of approving a submission.

## Estimated size (S, M, L)
UI: S

It would hopefully be a pretty straight-forward task to define a dismissSubmission function in the useJoinSubmissionMutations hook. However, it might have to be decided upon whether it should be a .delete or a .patch function, in the latter case changing the state of the submission to 'dismissed' (which is not an existing value of the ZetkinJoinSubmission state property as of now).

**Comment by richardolsson** [comment]
This requires changes to the API before it can be started.

**Comment by richardolsson** [comment]
Fixed by #2427
