### ISSUE TITLE
Not obvious that deleting a person deletes them from entire tree

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#2070]
## Description
There are two ways of removing people in Zetkin:

* _Disconnecting_ a person from an organization makes them unavailable to the current organization and it's children, but does not delete the information associated with that person. This is useful when the person has moved away from a local branch but is still a member of the overall organization.
* _Deleting_ a person deletes them and their associated data from the entire tree. This is useful when a person wants to leave the organization, and lets their local organizer know about this, expecting all data associated with them to be deleted from the entire organization, not just the local branch.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/people/123
2. Click on the "Manage" tab
3. Click "Remove person"

### Expected Behaviour
At some point the user should be informed that deleting the person will delete them from the entire organization tree, perhaps even include the name of the parent organization?

### Actual Behaviour
Neither the "Remove person" nor the message in the confirmation dialog makes it clear that the person will be fully deleted from all other parts of the organization as well.

## Screenshots
None

**Comment by MattettaM** [comment]
Giving this a shot

**Comment by MattettaM** [comment]
Tried making a solution like this to get the root organization of the user, but it doesn't work due to hooks not being allowed to be called in this way. Will make a PR with the new warning message, but I think implementing this feature is beyond me at the moment.
```typescript
const getRootOrgById = (orgId: number): ZetkinOrganization | null => {
  var organization = useOrganization(orgId).data;
  if (organization?.parent) {
    organization = getRootOrgById(organization?.id);
  }
  return organization;
};
```
