### ISSUE TITLE
Email: Target number is wrong when many email addresses are missing

### ISSUE THREAD

**Issue by Bagera** [zetkin/app.zetkin.org#2082]
## Description

The target number shows as -5 when it should probably be 2 (7 total targets - 5 missing emails)

In this email, there seem to be no targets left, even though the smart search hits 7.

## Steps to reproduce
1. Go to [(https://app.dev.zetkin.org/organize/1/projects/8/emails/3)](https://app.dev.zetkin.org/organize/1/projects/8/emails/3)
2. Look at the numbers

## Screenshots

Activity list
![image](https://github.com/user-attachments/assets/582947f6-d55b-4bde-a0ca-c0505f57cef6)

Email page
![image](https://github.com/user-attachments/assets/3abea846-1fec-40ee-8516-9d31710c08e4)

**Comment by kaulfield23** [comment]
I'm taking this one!
