### ISSUE TITLE
Journey Instance List Milestone Date

### ISSUE THREAD

**Issue by joe-irving** [zetkin/app.zetkin.org#2095]
## Description

An organiser I work with has requested to be able to see the next date of the milestone on a journey instance. They can only see the deadline in "X days until" format. This is not very helpful for when they need to know upcoming dates quickly

### Expected Behaviour

An optional column for "Next Milestone Date" as you can see in the mock up of design on  #575 

### Actual Behaviour

There is no such field

## Screenshots

This is the mock up in above issue

![158752494-1d1c5cbb-bc69-412a-b954-feb13c889abc](https://github.com/user-attachments/assets/e1d51059-aadb-48b6-a3ea-4561f103e743)

**Comment by remipou** [comment]
having a look at this one
