### ISSUE TITLE
Duplicates: "No data will be lost" is misleading

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#2099]
## Description
When two or more person objects are merged to resolve a duplicate, all related objects (such as events, phone calls, journeys, tags etc) are transferred to the remaining person object, while all other person objects are deleted. This means that no _related (but separate)_ data will be lost.

However, if there are conflicting field values on the person records, e.g. two different email addresses or two different last names, the user must pick which one to keep, and the other one will be lost. This means that some data (field values) can be lost when merging duplicates.

There is a message in the dialog that can easily be interpreted as claiming that _no data_ will be lost, which is not true, as described above.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/people/duplicates
2. Click on "Resolve" on any of the duplicates
3. Scroll the right hand half of the modal to the bottom to find the message

### Expected Behaviour
Message should indicate that related data will be transferred.

### Actual Behaviour
The message claims that no data will be lost, which indicates that field values are also kept.

> **No data will be lost**
> All activity history and tags from all people being merged will carry over and will be visible on the merged person.

## Screenshots (if you have any)
![image](https://github.com/user-attachments/assets/0a1244b4-8d77-46c9-8310-dfbb5077dbcc)

## Proposed solution
The text should be changed to not imply that _no data_ will be lost, perhaps by more explicitly pointing to related data. When making these changes, new message IDs should be introduced so that translations will be updated.

**Comment by a-jaxell** [comment]
I have a problem recreating the bug since I am not really sure on how to make duplicate persons.
When I visit the specified link I cant find any duplicate persons.
Ive tried downloading a csv and then uploading it again but with no success.

However I have added a PR with suggested changes that I will test when I can view them in a use case.
