### ISSUE TITLE
Data protection link always leads to zetkin.org regardless of instance

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#2116]
## Description
For on-premise instances it should be possible to have a non-standard privacy policy.

## Steps to reproduce
1. Go to any survey in the activist portal
2. At the bottom of the survey page, click the privacy policy link

### Expected Behaviour
Should lead to specific privacy policy links defined by an environment variable.

### Actual Behaviour
Always links to zetkin.org/privacy

**Comment by kristofferlarberg** [comment]
I'll have a look at this!
