### ISSUE TITLE
Lists: Can't drag a list into a folder that is outside of view – implement alternative without drag and drop

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#2126]
## Description
When a user wants to move a list into a folder, they can drag and drop it onto the folder. But if they have lots of folders and lists, and the list they want to move is far down, and the folder they want to move it into is far up, dragging won't work because it's not possible to scroll while dragging.

## Steps to reproduce
1. https://app.dev.zetkin.org/organize/1/people (and log in)
2. Find a folder towards the top that you will want to move a list into and remember it's name and location
3. Scroll to bottom of list
4. Grab one of the list "files" and drag up towards top of screen, trying to drag it to the folder you picked in step 2

### Expected Behaviour
The list should scroll up when you approach the top edge.

### Actual Behaviour
Scrolling works sometimes, but not always and not for everyone. This entire flow also doesn't work on touch screens very well.

## Screenshots (if you have any)
![image](https://github.com/user-attachments/assets/e1b44505-94d1-4b09-bbfc-d440b91493e0)

## Proposed solution
Besides this drag and drop interaction, it would be nice if there was a moving UX that didn't rely on drag and drop. Implementing such a UX would fix this problem, and also make the UI more touchscreen friendly. Here's my proposal:

* In the ellipsis menu on the right, add a "Move to…" option
* When the user selects "Move to…", open a dialog similar to the one proposed for events in #1901
* List all folders in a tree-like structure

![image](https://github.com/user-attachments/assets/74ea93ca-865a-41bc-992c-44a82e0203ec)

**Comment by ajoensson** [comment]
I'll take a look at this!
