### ISSUE TITLE
Call assignments: Caller list does not show person hover card

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#2144]
## Description
In Zetkin, you can create call assignments where you assign callers to do phonebanking. In most places where a person is referenced in Zetkin UI, you can hover that UI element and get a popup with some details about the person and a link to their profile page. This component is called `ZUIPersonHoverCard`.

When hovering a caller in the callers list, I expect the `ZUIPersonHoverCard` to appear, but it doesn't.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/projects
2. Create a project
3. In the project, create a call assignment
4. Go to the "Callers" tab
5. Add a caller
6. Hover the avatar of the caller in the list

### Expected Behaviour
The hover card should show up.

### Actual Behaviour
Nothing happens

### Hovering the avatar of "Helena Izqierda"
![image](https://github.com/user-attachments/assets/68e5e512-8bfe-4223-b375-d3bb744b8440)

### The `ZUIPersonHoverCard` in another context
![image](https://github.com/user-attachments/assets/0521a731-bb20-4e4b-90ce-68b5d24531b2)

**Comment by helihard** [comment]
Going to look into this!
