### ISSUE TITLE
Safer ZUIDuration

### ISSUE THREAD

**Issue by WULCAN** [zetkin/app.zetkin.org#2149]
## Description

A developer should be able to use any combination of `ZUIDuration` properties without risk of confusing users.

On d0eb97013dae87e35a446c6139f141dc67ee81d7, `ZUIDuration` has props to individually control whether days, hours , minutes, seconds or milliseconds will be displayed. This works well if all props controlling larger units are true and only props controlling smaller units are false: the displayed duration will simply be truncated according to configured props.

If a prop for some larger unit is false, while props for smaller units are true, ZUIDuration will simply omit those larger units rather than displaying the duration using the units available.

* `<ZUIDuration seconds={123456} />` renders correctly as 1 day 10h 17m
* `<ZUIDuration withDays={false} seconds={123456} />` renders as 10h 17m but would more correctly render as 34h 17m
* `<ZUIDuration withHours={false} seconds={123456} />` renders as 1 day 17m but would more correctly render as 1 day 617m

[Screencast from 2024-09-21 14-36-23.webm](https://github.com/user-attachments/assets/e66b2568-a1ab-4b5e-bf20-b4f166f28443)

## Estimated size (S, M, L)

I think this issue is S because it is contained in a component and we already have that component represented in Storybook, making it easy to test.

## Possible implementations

One solution could be to change the API into something like `<ZUIDuration precision={'minutes'} seconds={duration} />` and not support disabling larger units.

The source code for ZUIDuration is in `src/zui/ZUIDuration/index.tsx`

**Comment by KraftKatten** [comment]
Looking into this one :)
