### ISSUE TITLE
Missing space in copied text from a ZUIDuration

### ISSUE THREAD

**Issue by WULCAN** [zetkin/app.zetkin.org#2150]
## Description

Copied text from a ZUIDuration has no spaces between the components even though it is rendered with gaps between the components.

There's plenty of spaces around the spans in `src/zui/ZUIDuration/index.tsx` but as this is tsx and not HTML, no spaces will be included in the DOM. If it were rendered to HTML, it would be `<span style="margin-right: 4px;">3h</span><span style="margin-right: 4px;">25m</span>` which reveals that there is no space between the spans.

## Steps to reproduce
1. Open ZUIDuration under Atoms in Storybook, for example by running `yarn run storybook` and opening http://localhost:6006/?path=/docs/atoms-zuiduration--docs
2. Select the rendered duration and copy it.
3. Paste it into a text field

I expect this being reproducible on `/organize/[orgId]/projects/[campId]/emails/[emailId]/insights` too but I couldn't find any example project on the dev site with email insights.

### Expected Behaviour

`3h 25m` should be pasted, like what was rendered.

### Actual Behaviour

`3h25m` is pasted, without the space between 3h and 25m.

With durations longer than 1 day, it's worse as there is a space between the number of days and the word `days` but no other spaces: `14 days6h56m`

## Screenshots (if you have any)

[Screencast from 2024-09-21 15-19-02.webm](https://github.com/user-attachments/assets/422ba66f-f4ec-4c46-955c-939c43be3c84)

**Comment by Idkirsch** [comment]
we will (hopefully) fix this
