### ISSUE TITLE
Lists: Remove tag value from cell in list causes error

### ISSUE THREAD

**Issue by kaulfield23** [zetkin/app.zetkin.org#2153]
**Please be as thorough as possible, but if you can't answer everything, please just submit what you have! Thank you!**

## Steps to reproduce
1. Go to any list
2. Click on cell that has value in tag
3.  Remove value

### Expected Behaviour
Removing value should not cause an error
### Actual Behaviour
Get an error : ` state.tagsByPersonId[personId].items` is `undefined`

## Screenshots (if you have any)

https://github.com/user-attachments/assets/20ed7c74-219c-4f42-b48c-d494c0e8dc6f

Note that this happens because there is no value in `tagsByPersonId` in redux

**Comment by KraftKatten** [comment]
Taking this on :)
