### ISSUE TITLE
Email: Redundant margin for sent emails

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#2154]
## Description
After an email has been sent, there is a blue information bar over the editor letting the user know that the email is in read-only mode. The bar has a redundant margin underneith, which 

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/projects and log in if necessary
3. Go to any project (or create a new one)
4. Create an email
5. Define any targeting and lock the targets
6. Add some content under "Compose" and add a subject line under "Settings"
7. Click "Delivery" and schedule email for tomorrow
8. Go to Compose tab

### Expected Behaviour
There should be a blue banner immediately between the tab bar and the editor UI, letting you know that the email has been scheduled for delivery.

### Actual Behaviour
There is a blue banner, but there is a margin underneath it.

### Example 1
![image](https://github.com/user-attachments/assets/ee109fe9-6eca-4ac2-9cde-cb5a8d408d2d)

### Example 2
The extra margin is more obvious here where there's a background color on the email.
![image](https://github.com/user-attachments/assets/7693e8b1-1154-4308-9c74-a64675651941)

**Comment by ZebastianBjorkqvist** [comment]
Ill take a look at this
