### ISSUE TITLE
🧱 ZUI: Divider

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#2161]
## Description
A divider component to be used in a variety of scenarios. 

## Screenshots
![bild](https://github.com/user-attachments/assets/8b190658-3f05-4a6b-a712-4c7e7ca956ab)

## Figma link
You need to be logged into a Figma account to properly view the Figma content. 

https://www.figma.com/design/yIQMDEFSgkUOrSaJpg3k7N/ZUI?node-id=11033-145138&t=XDq42a8E5ncUc5kk-4

## Requirements
- [ ] Vertical and horizontal orientations
- [ ] Matches the styles as given in Figma

## Possible implementations
This can be built on top of the MUI Divider component.

Develop this using Storybook. We want all the design system components to be documented through their own Storybook stories.

As a general reference, you can look at the already existing ZUI components created on the `undocumented/new-design-system` branch (not ZUI components that exist on `main`, as they are not part of the new design system.)

## Git

The main git branch for the work on the new design system is `undocumented/new-design-system`. Unless otherwise instructed, do your work on a new branch branched off from this branch.

Name your branch `issue-number/zui-name`, ex: `issue-928/zui-button` for a branch where work is done that is documented in the issue with number 928, where a button component is being made.

**Comment by sarlinkle** [comment]
Working on this!
