### ISSUE TITLE
🧱 ZUI: Bar diagram

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#2166]
## Description
At various places in the UI we want to represent the status of a process by displaying some relevant data in the form of a bar diagram. 

## Screenshots
Large: 
![bild](https://github.com/user-attachments/assets/4728c96f-0683-4bae-a937-5a2869e9c896)

Medium: 
![bild](https://github.com/user-attachments/assets/4c0503a4-1443-42f7-9a32-b8153c3cb0d8)

Small: 
![bild](https://github.com/user-attachments/assets/edd2f5bc-88c6-4249-9f2f-2bc2bc05edea)

## Figma link
You need to be logged into a Figma account to properly view the Figma content.
https://www.figma.com/design/yIQMDEFSgkUOrSaJpg3k7N/ZUI?node-id=2125-72556&t=WTbaUbn5r6vpwXpe-4

## Requirements
- [ ] Sizes (small, medium or large) 
- [ ] Number of sections (2, 3 or 4)
- [ ] State of the diagram sections ( = how much of the width they take up) 
- [ ] Colors and other styling matches what is described in Figma

## Open questions
None at this point

## Possible implementations
You could potentially take inspiration from (or use bits of) the component called `ZUIStackedStatusBar`. 

Develop this using Storybook. We want all the design system components to be documented through their own Storybook stories.

For reference, you can look at the already existing ZUI components created on the `undocumented/new-design-system` branch (not ZUI components that exist on `main`, as they are not part of the new design system.)

## Git

The main git branch for the work on the new design system is `undocumented/new-design-system`. Unless otherwise instructed, do your work on a new branch branched off from this branch.

Name your branch `issue-number/zui-name`, ex: `issue-928/zui-button` for a branch where work is done that is documented in the issue with number 928, where a button component is being made.

**Comment by lewis-conroy** [comment]
working on this with river :p

**Comment by ziggabyte** [comment]
Solved by #2185
