### ISSUE TITLE
🧱 ZUI: Toggle button

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#2168]
## Description
When the user toggles between options, this is the representation of the options 

## Screenshots
![bild](https://github.com/user-attachments/assets/cc0f4da7-ef8e-4398-9b6a-8e63414fc2e1)

## Figma link
You need to be logged into a Figma account to properly view the Figma content.
https://www.figma.com/design/yIQMDEFSgkUOrSaJpg3k7N/ZUI?node-id=11022-146896&t=WTbaUbn5r6vpwXpe-4

## Requirements
- [ ] The buttons show either text or an icon
- [ ] Orientation: vertical or horizontal
- [ ] Sizes: large, medium and small
- [ ] The style matches what is described in Figma
- [ ] One option is always selected, clicking the selected option does not result in de-selecting this option

## Open questions
I am not absolutely 100% certain of the last point, about de-selecting. It's how I interpret the designs in Figma. So maybe ask a designer to confirm (or deny) this!

## Possible implementations
There is a MUI component called Toggle button that can be used for this.

Pay attention to the styling of shadows on the buttons in Figma - the style looks quite similar to the styles of `ZUIButtonGroup`, so the styling in there could potentially be used as a reference.

Develop this using Storybook. We want all the design system components to be documented through their own Storybook stories.

For reference, you can look at the already existing ZUI components created on the `undocumented/new-design-system` branch (not ZUI components that exist on `main`, as they are not part of the new design system.)

## Git

The main git branch for the work on the new design system is `undocumented/new-design-system`. Unless otherwise instructed, do your work on a new branch branched off from this branch.

Name your branch `issue-number/zui-name`, ex: `issue-928/zui-button` for a branch where work is done that is documented in the issue with number 928, where a button component is being made.

**Comment by ZebastianBjorkqvist** [comment]
Ill check this out

**Comment by ziggabyte** [comment]
Solved by #2212
