### ISSUE TITLE
Hide non-MVP features temporarily

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#217]
- [x] Menu bar: Notifications
- [x] Menu bar: Profile
- [x] Campaign page: insights tab
- [x] Campaign page: surveys box
- [x] Campaign page: call assignments box
- [x] Campaigns page: archive tab
- [x] Campaigns page: unsorted projects list
- [x] Campaigns page: "create event" (speed dial should only allow creating campaign)
- [x] Organize dashboard: entire page
- [x] Organize dashboard: Search Bar

**Comment by nehahirve** [comment]
What's the best way to hide? //TODO comments?

**Comment by richardolsson** [comment]
> @richardolsson @djbusstop What's the best way to hide? //TODO comments?

Yeah, that would be great if it can be easily done. If there's JSX that is too complicated to comment out it's also ok to just remove it. 😊

**Comment by djbusstop** [comment]
Regarding Hiding the insights and archive tabs, they can be removed from the layouts that implement them :+1:

**Comment by djbusstop** [comment]
Do we want to remove or just redirect buttons on the organize sidebar which currently navigate to pages that wont exist in the MVP

**Comment by richardolsson** [comment]
> Do we want to remove or just redirect buttons on the organize sidebar which currently navigate to pages that wont exist in the MVP

We can leave them in place, and I will set up redirects per #218
