### ISSUE TITLE
🧱 ZUI: Radio group

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#2170]
## Description
In a radio group, the user can select only one option of a set of many.

## Screenshots
![bild](https://github.com/user-attachments/assets/10a809b9-7185-4205-9d43-50299c4eaad6)

## Figma link
You need to be logged into a Figma account to properly view the Figma content.
https://www.figma.com/design/yIQMDEFSgkUOrSaJpg3k7N/ZUI?node-id=2972-11955&t=WTbaUbn5r6vpwXpe-4

## Requirements
- [ ] Sizes (small, medium, large)
- [ ] State for wich radio is selected
- [ ] Disabled state for the group
- [ ] Disabled state for individual radios
- [ ] Label for the individual radios
- [ ] Position for the individual labels
- [ ] Label text for the group
- [ ] Helper text for the group
- [ ] Styles of all states match what is described in the Figma design

## Open questions
None at the moment. 

## Possible implementations
You can use the MUI RadioGroup, FormControl and FormLabel components for this. 
Note that in Figma the individual radios, the labels and the group are described as separate figma components. This does not mean they should be separate components in the technical implementation. 

Develop this using Storybook. We want all the design system components to be documented through their own Storybook stories.

For reference, you can look at the already existing ZUI components created on the `undocumented/new-design-system` branch (not ZUI components that exist on `main`, as they are not part of the new design system.)

## Git

The main git branch for the work on the new design system is `undocumented/new-design-system`. Unless otherwise instructed, do your work on a new branch branched off from this branch.

Name your branch `issue-number/zui-name`, ex: `issue-928/zui-button` for a branch where work is done that is documented in the issue with number 928, where a button component is being made.

**Comment by lewis-conroy** [comment]
working on it
