### ISSUE TITLE
Playwright test is flaky due to weird React hydration behavior

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#2172]
## Description
There are some Playwright tests related to the new (since #1756) survey page that intermittently fail. It seems to be because Playwright is sometimes so fast to interact that it manages to fill out (part of) the survey form before JS loads, and once React is hydrated the form state is lost before the form is submitted. This is a [known problem](https://playwright.dev/docs/navigations#hydration) within the Playwright community.

Here's my analysis and proposed solution from a recent Slack thread initiated by @WULCAN :

> I've seen these also, on GitHub, but I've been unable to reproduce it locally. The code that these testa are testing is the new survey UI implemented by @henry, and it's been built using "server actions" meaning it should work fine even without JS, so at first JS hydration issues seemed unlikely to me. But thinking about it some more I realize that this could be happening:
> 
> 1. HTML loads, including a fully functional HTML form with correctly configured action and method to work without JS.
> 2. Playwright (controlled by the test) fills out the form super quickly
> 3. JS loads and hydrates the DOM, including adding change event handlers to the input elements and a submit handler that takes over submitting responsibilities from the standard browser form behavior
> 4. Playwright (controlled by the test) clicks the submit button, now (because of 3) triggering React JS code to submit the form data to the server action using fetch
> 
> Because the change event listeners that are responsible for keeping track of the state in JS are added in step 3, after the  "user" has updated the state in step 2, I guess this could explain why the form is submitted with the wrong state. I'm surprised that hydration doesn't respect the state from the DOM.
> 
> I would like us to take two actions to remedy this:
> 
> * Change the tests so that they wait until the script has loaded, I guess the document load event?
> * Add another test (if there isn't one already?) that verifies that submitting the forms without JS support also works

## Steps to reproduce
The test failure is hard to reproduce, but our theorized cause for the problem can be emulated manually by slowing down loading significantly. Here's how:

1. Open a browser window
2. Open dev tools and enable throttling, setting it to emulate some very slow connection
3. Browse to https://app.dev.zetkin.org/o/1/surveys/1
4. As soon as the HTML has loaded, but before the JS/styling loads, while the radio buttons appear completely unstyled, click one of them to select it
5. Wait for JS to finish loading

### Expected Behaviour
When JS finishes loading, the embedded styling should be applied and the form state remain, i.e. the radio button still be selected.

### Actual Behaviour
When JS finishes loading, the embedded styling is applied but the state is reset and the radio button is no longer selected. This is probably a bug (or at least unexpected behavior IMO) in either React or NEXT.js and nothing we can solve, but we believe it is the reason for the flaky tests.

## Screenshots
Note how the form first loads unstyled and I interact with it around the 3s mark. Then at 12s the JS finishes loading, the form is hydrated, and the state is lost.

https://github.com/user-attachments/assets/01d0e977-ab2c-4ec0-b51e-34289248e838

## Proposed solution
Investigate how we can tell Playwright to wait until the page fully loads. Ideally there is some sort of event that we can wait for, but worst case scenario we add a 100ms delay or something like that (avoid if at all possible).

**Comment by troldmand** [comment]
https://github.com/zetkin/app.zetkin.org/pull/2179

... seems to fix it! :)

**Comment by WULCAN** [comment]
#2179 resolves the flakiness for me, but it isn't the comprehensive solution that I think @richardolsson might be looking for here.

**Comment by richardolsson** [comment]
I think it's fine to close this issue since the specific tests are fixed by #2179. But lets try to remember that this is something that can happen again in the future (and will need to be handled separately for that potential case anyway).
