### ISSUE TITLE
🧱 ZUI: Switch

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#2173]
## Description
A little switch to be used to toggle between two options.

## Screenshots
![bild](https://github.com/user-attachments/assets/b560e303-2da7-4045-bd01-986068ba8f4c)
![bild](https://github.com/user-attachments/assets/1913cb29-57e9-4882-a364-f669aee15ac0)
![bild](https://github.com/user-attachments/assets/e17d9b34-b9f0-4393-a6b9-9d9c9bb02d17)

## Figma link

You need to be logged into a Figma account to properly view the Figma content.
https://www.figma.com/design/yIQMDEFSgkUOrSaJpg3k7N/ZUI?node-id=11022-144511&t=eOjYi3ZVCtDnZudy-4

## Requirements
- [ ] Single switch
   - [ ] Action to be performed when toggling the state of the switch
   - [ ] Sizes (medium and small)
   - [ ] Disabled 
   - [ ] Optional label
   - [ ] Label positions 
- [ ] Component to group switches together 
   - [ ]  Helper text
   - [ ]  Group label
- [ ] Styles for all states match what is described in the Figma design

## Open questions
None att the moment.

## Possible implementations
You can use the MUI Switch component and various MUI Form components to create this (like FormGroup, FormHelperText etc)

Develop this using Storybook. We want all the design system components to be documented through their own Storybook stories.

For reference, you can look at the already existing ZUI components created on the `undocumented/new-design-system` branch (not ZUI components that exist on `main`, as they are not part of the new design system.)

## Git

The main git branch for the work on the new design system is `undocumented/new-design-system`. Unless otherwise instructed, do your work on a new branch branched off from this branch.

Name your branch `issue-number/zui-name`, ex: `issue-928/zui-button` for a branch where work is done that is documented in the issue with number 928, where a button component is being made.

**Comment by samuelskanberg** [comment]
Taking a look at this

**Comment by ziggabyte** [comment]
Solved by #2214
