### ISSUE TITLE
Join forms: Autocomplete does not empty on selection

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#2175]
## Steps to reproduce
1. Go to `.../people`
2. Click on the "Join forms" tab
3. Click on the title of a join form item in the list to open the pane where you can view and edit a join form
4. Open the dropdown/autocomplete to add a field
5. Select a new field to be added

### Expected Behaviour
The dropdown/autocomplete empties from the previous selection, so I can easily open it again and see all the options

### Actual Behaviour
The selected option stays in the dropdown/autocomplete, so when I click to open it all I see is that option. 

## Screenshots (if you have any)

Here I have just selected the field "C/O address" to be added, and the dropdown/autocomplete still has this value after the selection is complete.

![371034260-df9b55b8-153a-4bc1-bfd5-9cdd0bd78851](https://github.com/user-attachments/assets/de8d1255-1887-4d14-9791-a2ab7b1d00d4)

**Comment by richardolsson** [comment]
I was the one who built this (I believe?) but I now think the entire idea of using an autocomplete for this is a bit flawed so I think whoever takes this on can also suggest alternative solutions entirely.

**Comment by kristofferlarberg** [comment]
I'll have a look at this.
