### ISSUE TITLE
Smart Search: Search criteria misleading in English and all translations

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#2177]
## Description
There is a filter/selection for the Smart Search feature which allows an admin user to search for people based on their phone call history. One criteria is to search for people who have not been reached in a certain call assignment, but it's labelled in a misleading way making it sound like it will only find people who were called and not reached, when in fact it finds people who were not reached regardless of whether they were called.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/people
2. Click on "Create"
3. Click on "Create list"
4. In the new list, click "Configure" under "Configure Smart Search list"
5. Click "Add/remove people"
6. Find and add the "Call history" filter
7. Open the dropdown that is by default configured to "have been called"
8. Pick the third option
9. Click "Save selection"

### Expected Behaviour
The options should be:

* "have been called" (operator is `called`)
* "have been successfully reached" (operator is `reached`)
* "have not been reached" (operator is `notreached`)

Selecting the third option should also remove the "at least N times" part of the sentence, and remove the `minTimes` data from the configuration.

### Actual Behaviour
The third option is "have been unsuccessfully tried", which sounds like the people that match have been called but not reached (incorrect) and the `minTimes` part remains in the `configuration` that is sent to the API (check browser network panel to verify).

## Screenshots (if you have any)
![image](https://github.com/user-attachments/assets/04bac0c0-6cee-4c08-8ed7-2fe620cb48ba)

## Proposed solution
A solution to this issue will have to:

- [ ] Update the label to better reflect what the filter actually does
- [ ] Remove all translations of the faulty label from YAML files so that they can be redone
- [ ] Modify the logic to remove the "at least N times" from the UI and the `minTimes` from the configuration when picking the `notreached` option

**Comment by MattettaM** [comment]
Taking a stab at this
