### ISSUE TITLE
Single-task page

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#224]
The organizer needs to be able to:

* See and edit basic task information (title, description, dates etc)
* Edit task target group (using Smart Search query)
* Publish tasks
* See progress

## Sub-tasks:

- [ ] "Summary" tab
  - [x] #327  
  - [x] #297 
  - [x] #312 
  - [x] #298 
  - [x] #299 
    - [x] #326 
- [ ] "Assignees" tab
  - [x] #338
  - [x] #340
  - [ ] Click an assignee to navigate to their profile page

**Comment by richardolsson** [comment]
## Summary tab
![image](https://user-images.githubusercontent.com/550212/125775881-930d4043-567d-4a2a-a251-0cb5d7a93bbb.png)

## Assignees (unpublished)
![image](https://user-images.githubusercontent.com/550212/125775916-df63d296-ea50-4b5f-b8ce-7e12cf6aaa78.png)

## Assignees (published)
![image](https://user-images.githubusercontent.com/550212/125775951-fd23102c-5075-47ee-832a-4feebc044b62.png)

**Comment by djbusstop** [comment]
There's a potential for a pretty loading indicator on this page? Something for gemma to think about. They can get creative with MUI components :)

**Comment by richardolsson** [comment]
Here's (roughly) how the Assignees tab should work. Also see wireframes above.

Tasks are assigned to people using a Smart Search query for targeting, when the task is published. So the organizer must define a Smart Search query, and publish the task. This can be done a few different ways:

* The organizer navigates to _Assignees_ and fills out the Smart Search query
* The task is published when
  * An organizer clicks the "Publish now" button to publish immediately
  * The `published` date passes

When a task has been published, a list of assignees will have been created at `/orgs/1/tasks/2/assigned`. This list should be rendered on the page. Each assigned task will have a status (completed etc) that should be indicated in this list.

When a task has been published, the targeting Smart Search query can no longer be modified.

**Comment by djbusstop** [comment]
### Some things not in the scope of these tasks, but which need to be done or would greatly improve the experience of tasks:

* Remove config values if the `type` is being patched
* Frontend validation for dates that requires dates be after one another

**Comment by richardolsson** [comment]
I propose we close this issue. The only missing piece is to link assignee cards to profile pages, which is not critical for now since those pages will not be part of MVP anyway.

**Comment by richardolsson** [comment]
I'm closing this. Anyone can reopen if you feel it's still relevant.

FYI @djbusstop
