### ISSUE TITLE
Images in email composer not showing

### ISSUE THREAD

**Issue by sefsh** [zetkin/app.zetkin.org#2245]
## Description
Inserting an image into the email composer does not show the image. Zetkin image hosting seem to use a combination of http and non-valid https:

<img width="789" alt="image" src="https://github.com/user-attachments/assets/c805d363-f92c-43c7-a179-5ea75f702951">

## Steps to reproduce
1. Have a privacy-respecting browser and/or addon (like the german tester had) (
2. Click [+] to add an image to the composer
3. See no image

### Expected Behaviour
<img width="1195" alt="image" src="https://github.com/user-attachments/assets/e0cb8cb1-e252-457f-808f-8d1153efd78b">

### Actual Behaviour
<img width="1372" alt="image" src="https://github.com/user-attachments/assets/44180c70-f558-4926-b69b-3f9327ffb544">

**Comment by richardolsson** [comment]
This is only happening on the dev server, due to browser settings.
