### ISSUE TITLE
Calendar: Wintertime incorrectly labeled summertime (and vice versa)

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#2251]
## Description
PR #2192 introduced labels in all calendar view modes (day, week, month) that indicate when DST starts/ends. It was later refactored in #2217.

The label is either "wintertime" or "summertime", and to me it's confusing that the label on October 27 (Sweden) is called "Summer time", because that's when Swedish "vintertid" starts.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/projects/calendar?focusDate=2024-10-21&timeScale=week
2. Look at the header of October 27

### Expected Behaviour
The header should say "Wintertime".

### Actual Behaviour
The header says "Summertime". The opposite is true for when DST switches in the spring.

## Screenshots (if you have any)
![image](https://github.com/user-attachments/assets/3041bb49-5df9-4ec1-97bf-3ccb423e1f5e)

**Comment by a-jaxell** [comment]
Currently looking into this, the logic checking wether theres been a change in DST could be 'flipped' to produce desirable result but it seems "wrong" to me atm
