### ISSUE TITLE
Welcome page for trusted organization officials soft-locks user

### ISSUE THREAD

**Issue by RodrigoRoaRodriguez** [zetkin/app.zetkin.org#2255]
## Description
As a trusted organization official, I get soft-locked after logging into [app.zetkin.org](https://app.zetkin.org/)

## Steps to reproduce
1. Go to app.zetkin.org
2. login into an trusted organization official account

### Expected Behaviour

There exists UI that the user can interact with, including a link to the users page and a logout button.

### Actual Behaviour

The user is soft-locked as there is nothing they can interact with on the page. There is neither a link to the users page or a logout button.

### How [app.zetkin.org](https://github.com/zetkin/app.zetkin.org) looks like after  trusted organization official login:

Welcome page for trusted organization officials:

- [ ] ❌ Has content
- [ ] ❌  Has a ui the user can interact with
- [ ] ❌  Has a logout button
- [ ] ❌  Has a  link to the user's page

<img width="552" alt="Screenshot 2024-10-12 at 10 28 26" src="https://github.com/user-attachments/assets/046fa39c-4d76-4adc-896b-8f4514a4dcfe">

<img width="967" alt="Screenshot 2024-10-12 at 10 26 56" src="https://github.com/user-attachments/assets/2caf4aed-766d-4138-ade1-bccd7c1cf167">

### How Zetk.in looks  like after  trusted organization official login:

For comparison here is how the welcome page for trusted organization officials looks like in  [Zetk.in](https://www.zetk.in/):

-  ✅ Has content
-  ✅ Has a ui the user can interact with
-  ✅ Has a logout button
-  ✅ Has a  link to the user's page

<img width="501" alt="image" src="https://github.com/user-attachments/assets/13f36f1b-69d9-4e91-a8d5-5caff138134b">

**Comment by richardolsson** [comment]
Thanks for reporting this!

In the steps to reproduce (and elsewhere) you write that you are signing in as a "trusted organization official". I'm unable to reproduce this on our development instance as an official, but I can reproduce it using a user account that has no official roles (`testadmin@example.com`).

Are you sure that your user account has official privileges? To allow me to confirm, can you please send an email to info@zetkin.org with the email address that you are using to log in?
