### ISSUE TITLE
Events: "title" missing on event pages

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#2258]
## Description
When visiting an event page, I expect to see some kind of nice title on the browser tab, like the title of the event maybe, or the name of the tab I'm on, but currently it shows the url. 

Level up the task: Look at all pages and make sure all pages have an aproperiate title :) 

## Steps to reproduce
1. Go to any event
2. Look at the tab in the browser

### Expected Behaviour
See a title, like the name of the event

### Actual Behaviour
See the url

## Screenshots (if you have any)
![bild](https://github.com/user-attachments/assets/00e3fea2-11b8-4789-b750-0760c06eb47e)

**Comment by dev-di** [comment]
I'll take a look at this today
