### ISSUE TITLE
Event state remains as scheduled when changing visibility to 'not visible or scheduled'

### ISSUE THREAD

**Issue by a-jaxell** [zetkin/app.zetkin.org#2264]
## Description

This was briefly mentioned in https://github.com/zetkin/app.zetkin.org/pull/2005#issue-2326323110

The Event state is not set correctly when setting and unsetting visibility date.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/projects/
2. Click on any project
3. Create an event draft
5. Set visibility to a future date
6. Click outside the date picker
7. Open the date picker and press x to clear the date
8. Click outside the datepicker

### Expected Behaviour
Event state should change to default draft state

### Actual Behaviour
Event state remains as scheduled

## Screenshots (if you have any)

https://github.com/user-attachments/assets/652c9ca6-4580-4e3f-9fbf-c3e5532baad6

**Comment by helihard** [comment]
I think I have located the error in the code, will PR a solution later today.
