### ISSUE TITLE
Add missing email address when linking survey response

### ISSUE THREAD

**Issue by sefsh** [zetkin/app.zetkin.org#2269]
## Description
If an email address is missing in the person object but provided by the survey survey response, the user should be able to update its email address when linking the response.

## Estimated size (S, M, L)

I think this issue is S because it's a simple operation.

## Possible implementations
- Add a modal asking user to add the email to the person, right after the person has been selected for linking.

## Design specifications

![image](https://github.com/user-attachments/assets/0f575060-741f-4b58-90b5-7d8ccb694093)

**Comment by richardolsson** [comment]
It's worth pointing out to whomever decides to take this on that the design specifications are using the new ZUI design system which is still being implemented. This is why buttons are black, the avatar has a gradient etc.

When implementing this, just use standard MUI components for now, with the default colors from the theme.
