### ISSUE TITLE
Empty state email Blocked section

### ISSUE THREAD

**Issue by sefsh** [zetkin/app.zetkin.org#2281]
## Description
Email _Blocked_ section lacks a recipients counter for its empty state.

## Steps to reproduce
1. Create an email activity

### Expected Behaviour
![image](https://github.com/user-attachments/assets/8df8b6d6-28cc-423d-aa37-0698535df62c)
A number in a chip in the section header that summarizes the total number of blocked recipients within targeted segment.

### Actual Behaviour
![image](https://github.com/user-attachments/assets/0ab668d4-9af1-46be-accc-d092a9993097)
No number in a chip in the section header.

**Comment by helihard** [comment]
Can also try to solve this one while I'm already at #2280
