### ISSUE TITLE
Create tasks from campaign page

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#230]
Add a "Create task" option to the speed dial (see also #229).

Task config is a little bit complicated, with several types of tasks that each have a different set of settings. The form needs to be separate into two steps (ideally two dialogs that can be opened separately)?

## Main dialog
* Title
* Type, one of:
  * Offline task (`offline`)
  * Share a link (`share_link`)
  * Visit a link (`visit_link`)
* Campaign (required, can't be null for tasks)
* Instructions (multiline text field)
* Dates for
  * Publishing (optional, will remain draft until date is set and has past)
  * Deadline (optional)
  * Expiry (optional)

### Config for `offline` tasks
No further config (i.e. no second step) required.

### Config for `share_link` tasks
* Link URL
* Default message when sharing (multiline text)

### Config for `visit_link` tasks
* Link URL

**Comment by djbusstop** [comment]
See https://github.com/zetkin/zetkin-platform/issues/43 for task API spec.
