### ISSUE TITLE
DOM exception thrown in Edge when editing event title

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#2302]
## Description
A user that is using Microsoft Edge is getting exceptions when trying to edit the title of a newly created event. This is not happening in Firefox or Chrome.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org _using Microsoft Edge_
2. Go to any project (or create a new one)
3. Create an event
4. On the page of the new event, click the title to edit it
5. Press any character on the keyboard

### Expected Behaviour
The character should appear in the title input field

### Actual Behaviour
An exception is thrown and the page "whitescreens". The exception reads something along the lines of "Can't use `removeChild()`. Element is not a child". This is a standard DOM error, so I'm guessing the error is being thrown in React somewhere?

## Screenshots (if you have any)
None

**Comment by MattettaM** [comment]
I can't seem to reproduce this bug. I have gotten the latest version of the project and tested in Edge Version 131.0.2903.86, which seems to be the most up to date version.

**Comment by richardolsson** [comment]
Ok @MattettaM! Let's assume there was something temporary, or something that has been fixed, or some incompatibility with a browser extension or something. 💯
