### ISSUE TITLE
German translation of `terms.description` not rendering

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#2303]
## Description
Pages in Zetkin can be translated to different languages, one of which is German. Text elements in content created in Zetkin (e.g. surveys) can be written in any language the user prefers, but on top of that there is UI rendered by Zetkin that will need to be translated by our volunteers translators.

When visiting the page where a survey can be filled out in a browser that is configured to prefer German, all page UI can render correctly in German, except for the string identified as `feat.surveys.surveyForm.terms.description`, which for some reason renders in English even though it seems to be translated (in src/locale/de.yml).

## Steps to reproduce
1. Configure your browser to prefer German (e.g. using the "Locale Switcher" Chrome extension)
2. Go to https://app.dev.zetkin.org/organize/1/surveys/1
3. Make sure that UI is rendered in German in general (e.g. the submit button at the bottom of the page)
4. Scroll down to where the privacy policy terms are explained

### Expected Behaviour
The description should be in German, like other parts of the UI.

### Actual Behaviour
The description is in English, as if there was no translation. If you do the same thing for Swedish, it does work, so it does not seem to be a general problem with the internationalization.

## Screenshots (if you have any)
![image](https://github.com/user-attachments/assets/ac16fe91-edc9-4bd7-9507-0051a25806a0)

## Proposed solution
I have no idea what's causing this, but I would start by having a look at the `src/locale/de.yml` file and make sure that the translation is there. I have looked for it and it seems to be there as far as I can tell.

Next I would try to make the translation simpler (by editing `de.yml` directly, which is not how it should normally be modified, but a good way to debug). Maybe there is something with the format that is breaking the translation. If the problem is with the translation itself, the fix should not be a PR but an update to the translation (comment on this issue to explain what needs to be done).

**Comment by ajoensson** [comment]
I found the issue! 

```
The intl string context variable "Organisation" was not provided to the string "[...] Informationen in Zetkin von {Organisation} gespeichert und verarbeitet [...]"
```

Simply changing the translation to
```
Informationen in Zetkin von {organization} gespeichert und verarbeitet
```
fixes the issue. I guess whoever translated this string was not aware that the values between curly braces should not be translated. An easy mistake to make!

**Comment by richardolsson** [comment]
Great work! I will fix the translation and it will be in a release soon.
