### ISSUE TITLE
Importer: Disabled read-only fields in importer rather than invisible

### ISSUE THREAD

**Issue by niklasva82** [zetkin/app.zetkin.org#2308]
## Description

A user should be able to see which fields are not possible to import to because they are shared read-only fields.

## Estimated size (S, M, L)

I think this issue is S because it should be a relatively simple matter. Information about whether the field is read-only should probably be added to the Option, and the options should be disabled if it is.

## Requirements

- [ ] In the importer where you select which fields should be mapped to a column, when a field is read only, that is `field.organization.id != org_id` and `field.org_write != 'suborgs'`, it should still be visible in the drop-down but disabled.

## Possible implementations

The `fieldOptions` are passed to `FieldSelect`. The `Option` type in `useColumn` is changed to include e.g. a `disabled` field which can be populated in the same hook if `field.org_write` is not `'suborgs'` and the organization of the field does not match the current organization.

## Open questions

Whether and in that case how to indicate why the field has been disabled.

**Comment by Herover** [comment]
Giving this one a try
