### ISSUE TITLE
Invalid operator `some` in survey options Smart Search filter

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#2314]
## Description
Smart Search has a filter for finding people based on survey options (`survey_option`). The UI for configuring this filter has a "some" option, which is not valid and should be removed.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/people
2. Create a new list
3. Configure the list using Smart Search
4. Click "Add/remove people"
5. Add a filter based on "Responses to checkbox questions"
6. Click the operator dropdown

### Expected Behaviour
The options should be "all", "any" and "none".

### Actual Behaviour
The options are "all", "any", "none" and "some" (the last of which is invalid).

## Screenshots (if you have any)
![image](https://github.com/user-attachments/assets/18846696-99b7-476b-b801-fa868bde8bf3)

**Comment by helihard** [comment]
I'm on it.
