### ISSUE TITLE
Smart search: Not possible to select default option without first selecting non-default option

### ISSUE THREAD

**Issue by niklasva82** [zetkin/app.zetkin.org#2330]
## Steps to reproduce
1. Create a new smart search
2. Click on Add/Remove peope
3. Click on Personal info
4. Select gender

### Expected Behaviour
It should be possible to click save.

### Actual Behaviour
It's not possible to click save without first clicking "female" , changing it to "male", and then changing it back to "female".

## Screenshots (if you have any)
![image](https://github.com/user-attachments/assets/987d318e-fef3-4adc-840a-d8871c8f4bf5)

## Proposed solution
Presumably, this is because the internal state is not set by default in the gender filter. Set the filter to the default option in the filter component upon loading it.

**Comment by Jrende** [comment]
On it!
