### ISSUE TITLE
Migrate to MUI 5.0

### ISSUE THREAD

**Issue by nehahirve** [zetkin/app.zetkin.org#234]
https://next.material-ui.com/guides/migration-v4/

To implement after migration

- [ ] Moving tooltips on calendar bars and events
- [ ] Boxes should take refs without use of the spread operator
- [ ] Use the NextLinkComposed component?
- [ ] Nest themes in theme.js in a performant way, so that we can use the theme palette in style and prop overrides

**Comment by richardolsson** [comment]
MUIv5 is [out of beta](https://medium.com/material-ui/introducing-mui-core-v5-0-3b6ea3143ae), and I think we should upgrade now before we build much more UI.

It's also relevant for the Views feature (part of #438) which will use the new premium (paid) [MUI X](https://mui.com/x/) library and the `XGrid` component.

@nehahirve I know you were very keen to take this on earlier. Do you still want to, or are you ok if someone else does it? 😊

**Comment by nehahirve** [comment]
@richardolsson yeah i'm still keen! The earliest time I'd have is October 3, can you wait until then? If I'm not able to do it that weekend, then probably best that someone else does so it doesn't become blocking.

**Comment by richardolsson** [comment]
> @richardolsson yeah i'm still keen! The earliest time I'd have is October 3, can you wait until then? If I'm not able to do it that weekend, then probably best that someone else does so it doesn't become blocking.
> 
> Also -- how much test coverage is there now for the UI? Since I haven't been working with this in a while I might not know if something's breaking

I'm happy to hear! 😊 

This is actually not required to happen until mid-october, which is when we plan to have released R29 and will start working on R30 and some features where MUI 5 would be nice to have. By then, we should have test coverage up quite a bit (thanks to @djbusstop working on that right now during R29).

If you still want to do the bulk of it on October 3rd that's great, but no rush!

**Comment by richardolsson** [comment]
This was attempted by @nehahirve and @djbusstop in #488, but ran into the problems described in that PR, summed up by @djbusstop:

> the integration with mui-rff and date pickers is not yet ready to replace the mui pickers solution we had already implemented. What I suggest to do is to try to keep the current implementation of the pickers, and update the rest of MUI RFF.
> […]
> Closing as this work is on pause due to reasons described in above comment.

Here's my take:

I did some research into React Final Form and mui-rff because I felt a little bit on the sidelines of this entire problem. Having watched a presentation on RFF and read the README of mui-rff, I'm not quite sure why we even need mui-rff. Couldn't we just use RFF directly and avoid the hassles above?

RFF seems like a very healthy open-source project, mui-rff less so. I accept that it may simplify some things a little bit, but I think it's also evident by the situation that we're in that it complicates other parts. And I feel like if we were to use RFF directly, we would at least own the complications ourselves, and not be dependent on a quite small library that is not very rapidly updated.

**Comment by richardolsson** [comment]
I'm having issues with mui-rff in another area now, so I'm actually quite keen to get rid of it if there's no great reason to keep it. 🙄

**Comment by djbusstop** [comment]
I agree with the message about ditching mui-rff. But I think the consequences is we will need to write our own input components which wrap MUI inputs in RFF, which is what we were trying to avoid. I think that will take quite a lot of work and ideally we test these components. Do we want to do this at this stage? I'm not sure if it's the time. But if we decide to prioritise that, and it takes a lot of time, we have to accept the time that takes from building features.

One of the biggest pain points for me was moving from mui-pickers library to the built in datepickers in MUI 5. I don't know how hard it will be to use those with RFF directly. Just want to point that out as a potential source of stress.

**Comment by richardolsson** [comment]
I think we should have another go at this, but next cycle. Postponing until R31.

**Comment by richardolsson** [comment]
We decided at a meeting today to postpone this until after the Casework/Journeys MVP has been released, to focus all efforts on completing that.
