### ISSUE TITLE
Create ReactContext for the Organization information

### ISSUE THREAD

**Issue by djbusstop** [zetkin/app.zetkin.org#235]
## Description
Currently the prop `orgId` is being passed through all children. This is a good use case for a react context, so we do not need to pass it through an arbitrary number of children.

## Solution
Create an `OrganizationContext`, which:
* Automatically detects the organisation from the URL.
* Uses react-query to get the org data and keep it up to date in the provider
* Exposes the organisation data to the context consumer

All places where `orgId` is passed to children should be replaced with the context.

**Comment by djbusstop** [comment]
We should consider doing the same for user. Currently the user is exposed in the scaffold props, but this is only directly consumable from the pages.

**Comment by richardolsson** [comment]
> One thing I am a bit unsure about is whether this context should expose just the orgId, or the entire organisation.

Great question! I think your reasoning is valid. There are some benefits of using the full object, e.g. being able to access the `slug` and not just the ID.

If you do want to include the entire organization object, you could do that by pre-loading it in `scaffold()` and adding it to the query client cache from there.

In fact, if we put it in the react-query cache with a known key (e.g. "mainOrg" or something), we don't need a special provider. Components could just retrieve it using `useQuery()`. But maybe that's error prone for other reasons.

**Comment by djbusstop** [comment]
While working on this feature I realised I did not need a context, but could use `useRouter` instead.
