### ISSUE TITLE
Areas: Title not saved when clicking directly on description (and vice versa)

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#2353]
**Please be as thorough as possible, but if you can't answer everything, please just submit what you have! Thank you!**

## Description

When I have created a new area and am adding a title, then click directly on description to add a description, the title does not get updated. I need to click somewhere outside of either title or description fields for the click to trigger the saving. 

- This also goes the other way around: editing the description and clicking directly on title does not save the description.

## Steps to reproduce
1. Go to `.../areas`
2. Click on "Draw"
3. Draw a new area
4. In the dialog that opens, click on "Untitled area" to activate editing the title
5. Add a name
6. Click on "Empty description" just below the textfield, to activate editing of the description

### Expected Behaviour
The title gets saved and the field to edit the description is acitvated

### Actual Behaviour
The title is not saved and the field to edit the description is activated.

## Screenshots (if you have any)
![bild](https://github.com/user-attachments/assets/4ed8a5b4-e3f6-4bb6-abc4-36f5c793d971)
![bild](https://github.com/user-attachments/assets/8ec9325d-bb5d-4a36-945c-dbc30bbeabbf)

**Comment by richardolsson** [comment]
This UI will likely change in the not so distant future, so if the bug proves difficult to fix, we can leave it. Of course the best case scenario would be to fix it in the meantime, so if it's a simple fix I think that's preferable. 😊

**Comment by richardolsson** [comment]
> Hi! How do you edit an area? Couldn't find it on the first step to reproduce: "1. Go to .../areas". Do you need to be a specific user, to be authorized to draw areas?

Are you running this locally? If so, you need to have the feature flag `FEAT_AREAS=*` defined as an environment variables for the Areas feature to be enabled.

The feature is enabled on https://app.dev.zetkin.org, so you can try to reproduce it there first.

**Comment by troldmand** [comment]
That's it, thanks! :)
