### ISSUE TITLE
Floor state is retained across households when editing

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#2371]
## Description
The new, experimental "canvassing" (door knocking, mailbox leafletting etc) feature in Zetkin contains a mobile-first UI for canvassers, that they use when out visiting places. The UI allows for creating places and households that are not yet documented, and editing the details of those places and households.

When editing a household shortly after editing another household, the state of the form will contain values from the previous household rather than the one that is currently being edited.

## Steps to reproduce
1. First make sure that the instance you're using has canvassing features enabled, by setting the environment variable `FEAT_AREAS=*` (which enables for all organizations) in `.env.local`. This is already the case on the dev server, but won't be the case on localhost
2. Go to https://app.dev.zetkin.org/my/canvassassignments
3. Sign in using testadmin@example.com
4. Go into one of the canvass assignments
5. Pan somewhere on the map and create a new place using the button at the bottom of the screen
6. Give the place a name and submit
7. In the new place, create many households, by pressing "create many" and creating households with at least 2 floors
8. Back in the households list (now populated with the households created in step 7), press any household on floor 1
9. On the household page, press the pencil icon to edit it
10. Change the name somehow and submit
11. Go back to the household list
12. Pick any household on floor 2
13. On the household page, press the pencil icon to edit it

### Expected Behaviour
The form that appears should have `2` in the floor input, because the household you're editing is on floor 2.

### Actual Behaviour
The form that appears has `1` in the floor input, seemingly because that was the floor of the previous household that you edited.

### The second household
![image](https://github.com/user-attachments/assets/951de146-7ad4-4acf-bfce-1ebd07ed5869)

### The second household when edited
![image](https://github.com/user-attachments/assets/ddf90323-48c1-46be-854d-c6d43286c1bb)

**Comment by ZebastianBjorkqvist** [comment]
Ill take a look at this
