### ISSUE TITLE
"Building" visualization does not fit on screen when creating many households

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#2372]
## Description
The new, experimental "canvassing" (door knocking, mailbox leafletting etc) feature in Zetkin contains a mobile-first UI for canvassers, that they use when out visiting places. The UI allows for creating places and households that are not yet documented.

Some addresses have lots of households, so there is a UI for quickly creating many households across multiple floors. The UI contains a visualization of a building that grows and shrinks when you tweak the parameters. On very small screens, that UI does not fully fit.

## Steps to reproduce
1. First make sure that the instance you're using has canvassing features enabled, by setting the environment variable `FEAT_AREAS=*` (which enables for all organizations) in `.env.local`. This is already the case on the dev server, but won't be the case on localhost
2. Resize your browser to be very small, e.g. 650px tall
3. Go to https://app.dev.zetkin.org/my/canvassassignments
4. Sign in using testadmin@example.com
5. Go into one of the canvass assignments
6. Pan somewhere on the map and create a new place using the button at the bottom of the screen
7. Give the place a name and submit
8. In the new place, press "create many"
9. Increase the number of floors to some high number

### Expected Behaviour
As the number of floors increase, the size of the "building" should shrink to fit all the floors within the space allotted by the UI.

### Actual Behaviour
As the number of floors increase, the building doesn't start shrinking until too late, after it has already been cropped.

## Screenshots (if you have any)
![image](https://github.com/user-attachments/assets/ceb76da5-cf99-44b7-942c-95d78a90970c)

## Proposed solution
There is probably something wrong with the math here, most likely the height is hard-coded or not calculated correctly from the size of the container.

**Comment by ZebastianBjorkqvist** [comment]
Ill take a look at this
