### ISSUE TITLE
Lists: Delay closing of pop-up

### ISSUE THREAD

**Issue by Bagera** [zetkin/app.zetkin.org#2386]
## Description

A user should be able to take a shortcut to an action in the pop-up without the popup closing because their mouse moved ever so slightly outside the cell on the way to the pop-up.

![image](https://github.com/user-attachments/assets/fa236e41-ad6a-4fe5-99d2-77e5e0ede17c)

## Estimated size (S)

I think this issue is small because I don't think it will affect many components.

## Possible implementations

I think just adding a delay to the closing and probably opening of a pop-up should fix this.  A delay to the opening of a pop-up could also avoid "spamming" the screen with pop-ups when you mouse over a list. A delay of 250ms might be good.

**Comment by Jrende** [comment]
On it!
