### ISSUE TITLE
Misleading with "Create person" very high in select widget

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#2395]
## Description
In lots of places we use a select widget for finding people (to add to events, assign callers etc). In it's default state, the dropdown contains a create button, which encourages creating a new person before looking to see if they are already in the database. At the very least this is problematic because it can result in duplicates, but more importantly a new person record will not be connected to any user accounts which is a problem when adding a caller (they won't be able to access the assignment unless you add the profile that's connected to their user account).

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/projects
2. Go into any call assignment
3. Go to the callers tab
4. At the bottom, in the "Add caller" list, focus the input

### Expected Behaviour
The dropdown should say something along the lines of "Start typing to search or add a new person", and no "Create person" button should be displayed until the first search completes.

### Actual Behaviour
The "Create person" button is displayed immediately.

## Screenshots (if you have any)
![image](https://github.com/user-attachments/assets/10492909-338f-41ea-a4e5-e5f314cf05dc)

**Comment by richardolsson** [comment]
Pinging @sefsh and @Bagera in case any of you want to object to my suggestion for "Expected behavior" above.

**Comment by Bagera** [comment]
I agree

**Comment by xela1601** [comment]
I'd like to start with this one for my 1st contribution. What do you think @richardolsson ?
