### ISSUE TITLE
Hex values incorrectly limited to lowercase in color widget

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#2397]
## Description
When creating tags in Zetkin, it's possible to pick a color. The color is picked by inputting a hexadecimal RGB color value into an input field, which validates the input before allowing it to be submitted. That validation is currently only allowing values where any a-f characters are lowercase, but should also allow uppercase A-F.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/tags
2. Click "CREATE"
3. Insert any title
4. In the color field, insert "ABC123" (note the uppercase ABC)
5. Click "CREATE"

### Expected Behaviour
The tag should be created with the greenish color, and appear on the tags page. For this to work with the backend, the frontend will need to convert any uppercase A-F characters to lowercase a-f counterparts.

### Actual Behaviour
The tag is not created because the server does not accept uppercase A-F, and the frontend does not convert it.

## Screenshots (if you have any)
![image](https://github.com/user-attachments/assets/cdc18f4b-d39c-4cf7-8f6d-068e25b5e76e)

**Comment by helihard** [comment]
I'm looking at this.
