### ISSUE TITLE
"The whole organization" misleading when deleting type

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#2400]
## Description
Since #2219, it's possible to delete event types via the drop down under the event title. The confirmation dialog that opens warns that types will be deleted "for the whole organization", which is misleading because it could just as easily be interpreted as the entire organization tree.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/projects
2. Go to any event
3. In the event type/category dropdown, type "my new type" and create a new type
4. Open the dropdown again and click the small garbage can

### Expected Behaviour
A dialog should open asking the user to confirm that they want to delete the type. The message should say that the type will be deleted for "all of {org}" where `{org}` is the title of the current organization.

### Actual Behaviour
The dialog opens, but it implies that the type will be deleted for the entire tree, which is misleading.

### Creating a new type (step 3)
![image](https://github.com/user-attachments/assets/73c71032-b04e-43f1-ac94-973b7db560a8)

### Garbage can to delete (step 4)
![image](https://github.com/user-attachments/assets/87319a0a-dd59-4405-94aa-a8a190ad2bb1)

### Current message (actual behavior)
![image](https://github.com/user-attachments/assets/90a6466a-e552-488e-a969-7cccadb6e630)

**Comment by helihard** [comment]
I'm looking at this.
