### ISSUE TITLE
Gender can be mapped from multiple columns

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#2437]
## Description
A new feature for mapping gender was recently added to the importer (PR #2401). The feature mimics how other features allow values to be mapped to tags, organizations or enum fields. But unlike tags or organizations, it should not be possible to import multiple genders to a single person, which it currently is.

## Steps to reproduce
1. Go to https://app.dev.zetkin.org/organize/1/people
2. Click on Create
3. Click on "Import people"
4. Drag and drop the sample file below
5. Map FNAME to First Name
6. Map LNAME to Last Name
7. Map GENDER to Gender
8. Configure the gender mapping 
9. Click the checkbox next to PROFESSION
10. Open the "Import as" dropdown

### Sample file (CSV)
```csv
FNAME,LNAME,GENDER,PROFESSION
Clara,Zetkin,f,organizer
Richard,Olsson,m,programmer
```

### Expected Behaviour
The dropdown should contain lots of options, some of which should be disabled because they have already been configured. The Gender field should be one of the disabled fields.

### Actual Behaviour
The dropdown contains lots of options, some of which are disabled, but the gender field is not one of the disabled fields.

### Configuring gender (Step 8)
![image](https://github.com/user-attachments/assets/287f0883-3332-40d5-a71c-2fa766e08ff9)

### The dropdown with Gender enabled (step 10)
![image](https://github.com/user-attachments/assets/7c12d2b3-516b-4ad5-b634-61e9728de946)

**Comment by helihard** [comment]
I might have come up with a solution, which seems to work on my end, but not sure it's a good one. Will PR.
