### ISSUE TITLE
Find the perfect Directory structure

### ISSUE THREAD

**Issue by nehahirve** [zetkin/app.zetkin.org#246]
- [ ] Avoid imports like `../../../../../`
- [ ] consistency in the pattern /path/index.tsx or vs path.tsx

**Comment by djbusstop** [comment]
A possible solution for this is a "webpack alias" which would allow using `~` or `@` to refer to the home route, so we could use absolute imports.

**Comment by richardolsson** [comment]
The perfect structure has been found!

(Jokes aside, the current structure is more scalable and this issue is no longer relevant). 😊
