### ISSUE TITLE
Improve Create Event Form

### ISSUE THREAD

**Issue by nehahirve** [zetkin/app.zetkin.org#256]
These issues need to be fixed regarding the create event form.

- [ ] the event title should NOT be required, the activity_id and location_id SHOULD be required
- [ ] the query should be invalidated on success, to update the page, similar to when patching a campaign
- [ ] orgId can be inferred from router, no need to pass as prop

**Comment by richardolsson** [comment]
Most event features, including this form, were disabled for MVP, and will need to be redesigned before release, so I'm closing this issue as no longer relevant.
