### ISSUE TITLE
Organization Page

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#26]
The organization page is the home of an organization that uses Zetkin. This is where they direct their members to find content, sign up to things and interact with the organization using Zetkin.

The page should contain:

* Title and logo of organization
* Follow button
* Sign-up form to register a Zetkin user account and connect (#47)
* Feed of upcoming events, campaigns et c (#46)

In the future it will also link to sub-pages:

* Related organizations page (#48)
* Custom organization sub-pages (#27)
* Donate page (#49)

Below are two relevant but very rough wireframes.

![image](https://user-images.githubusercontent.com/550212/106397042-cbb53380-640b-11eb-9356-60fd9aa62927.png)

**Comment by djbusstop** [comment]
Is this still a useful issue since the only outstanding task is for the registration page? Maybe we can close this, and keep the register an account task separate?

**Comment by richardolsson** [comment]
Since we removed all of the public pages, none of the items are actually completed anymore. I think we need to have a general discussion about how we think of issues for features like this. Do we track them on GitHub at all before we actually start planning their UX?

**Comment by richardolsson** [comment]
Closing this as the activist-facing pages have not been a priority, and when we do shift focus to them we will want to start that process fresh.
