### ISSUE TITLE
Make organize tabs layout configurable

### ISSUE THREAD

**Issue by nehahirve** [zetkin/app.zetkin.org#263]
The tabs needed are different for different pages -- currently the tab values are hardcoded into the component, make it configurable

**Comment by richardolsson** [comment]
I envision this to be implemented in such a way that we have a `OrganizeTabbedLayout` where you can pass all the data necessary to render the layout to the component, e.g.:

* The title
* A sub-title (if deemed relevant as we develop the UI)
* The labels and hrefs of tabs

This way, the layout will not have to retrieve any data itself.
