### ISSUE TITLE
Event title should not be required

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#267]
The event form indicates that `title` is required, which it is not. By default the `activity` is used when creating a new event.

![image](https://user-images.githubusercontent.com/550212/125453445-28b5ae4d-993d-4168-bba1-6b9713e6f6b9.png)

**Comment by nehahirve** [comment]
Mentioned already in #256 @richardolsson

**Comment by richardolsson** [comment]
Closing as duplicate of #256
