### ISSUE TITLE
Re-fetch events after creating

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#268]
Currently, the calendar/events list does not update when creating an event. Steps to reproduce:

1. Navigate to http://localhost:3000/organize/1/campaigns/calendar
2. Using the speed dial, open the "Create new event" dialog
3. Fill out title, campaign, activity, location and time (today)
4. Click submit

Expected results: The event is created and shows up in calendar
Actual results: The event is created but does not show up in calendar until page is refreshed

The react-query cache of events needs to be invalidated.

**Comment by richardolsson** [comment]
The same might be true for campaigns.

**Comment by nehahirve** [comment]
Mentioned in #256 @richardolsson ?

**Comment by richardolsson** [comment]
Closing as duplicate of #256.
