### ISSUE TITLE
Improve Search Drawer

### ISSUE THREAD

**Issue by nehahirve** [zetkin/app.zetkin.org#274]
![image](https://user-images.githubusercontent.com/62522290/125633969-a7d2e622-da33-4418-8617-c332b28aa235.png)

- [ ] You're still able to scroll when the drawer is open -- I'd think it's as easy as transmitting an event to the layout component from the search drawer, and triggering an overflow: hidden
- [ ] When in mobile view, move the Drawer to be inside the AppBar component and span the drawer to the full width of the screen instead of 25vw.

**Comment by djbusstop** [comment]
I think the search drawer won't be in the mvp? Maybe this doesn't need to go in the project.

**Comment by nehahirve** [comment]
Good point, I'll remove it from r28 but keep it marked as entry-level so it can be worked on for fun

**Comment by richardolsson** [comment]
The search drawer has recently been replaced by a modal, so this is no longer relevant.
