### ISSUE TITLE
Easier calendar navigation

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#277]
Some things could be done to make calendar navigation easier. These come to mind:

- [x] Week and month calendar: Highlight _today_ with different color
- [x] Week and month calendar: Add button to navigate to _today_
- [x] Week calendar: Differentiate night from day (7.00-22.00?) using the background color
- [x] Week calendar: Differentiate past days from future (e.g. fade out weekday/date labels slightly)

**Comment by nehahirve** [comment]
differentiating night from day might not be 100% trivial -- 
I think the best solution would be to create a CSS linear-gradient as background for the weekdays, and use the percentage values as hard edges for the gradient. It becomes clearer when one reads the function that gets the position of the event divs on the page

**Comment by richardolsson** [comment]
I have an idea for the "Today" button that I'd like to hear your thoughts on.

Besides wanting to be able to quickly navigate to today, I sometimes feel lost when I don't know whether my current view is _before_ or _after_ today. So instead of just having a big "Today" button, I thought we could indicate whether today is in the future or past compared to the current view, by showing a little icon/indicator next to the prev/next buttons.

This is what it would look like when _today_ is before the current view, e.g. if we're looking at august and it's currently July.

![image](https://user-images.githubusercontent.com/550212/127149942-b376cc42-b86e-4026-8705-83a516fd7500.png)

The opposite then would look like this:

![image](https://user-images.githubusercontent.com/550212/127150184-e38fc645-ad36-4d19-9b15-4f54fc0f0437.png)

When today is in the current view, we would hide the button entirely, but instead highlight today in the calendar (as requested by item 1 in the issue todo list):

![image](https://user-images.githubusercontent.com/550212/127150281-f2d4f631-b858-4397-93b2-8822391444d4.png)

By using the same style, the correlation would hopefully become clear. But we could always use a tooltip to describe what the button/indicator means if we want to.

What do you think?

**Comment by nehahirve** [comment]
In image 1, my instinct is that today is in the past, and we are looking at July, and today is in June. 
In image 2, instinct is that today is in the future, that we are looking at July, and today is in August.
In last image, we are looking at July, and today is in July @richardolsson

**Comment by richardolsson** [comment]
> In image 1, my instinct is that today is in the past, and we are looking at July, and today is in June.
> In image 2, instinct is that today is in the future, that we are looking at July, and today is in August.
> In last image, we are looking at July, and today is in July @richardolsson

Yeah, that's my intent. I had mislabeled the middle image, but I've fixed it now and I believe we're in agreement. 😊
