### ISSUE TITLE
Navigate to newly created campaign when submitting on new campaign

### ISSUE THREAD

**Issue by djbusstop** [zetkin/app.zetkin.org#279]
See how this is done for tasks in `/src/components/ZetkinSpeedDial/actions/createTask.tsx`

**Comment by richardolsson** [comment]
Maybe this is a nice next task for you @omidhq?

**Comment by omidhq** [comment]
> Maybe this is a nice next task for you @omidhq?

Sure! Working on issue #306 now. Will move on to this one next!
