### ISSUE TITLE
Nav bar design

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#281]
Update the nav bar design to match mock-ups, with the following exceptions:

* Separate the top four (organization realted) and the bottom two (user related) items
* Don't include the add button / speed dial in nav bar
* Don't show labels

![image](https://user-images.githubusercontent.com/550212/125759143-25ecb2b2-24c7-4378-8f50-ab21b5f4a92b.png)

**Comment by nehahirve** [comment]
Can you merge @richardolsson ?
