### ISSUE TITLE
Create Single Campaign Page Header

### ISSUE THREAD

**Issue by djbusstop** [zetkin/app.zetkin.org#288]
See figma here: https://www.figma.com/file/dnJiIWWZVLgcLILUnDOySa/Zetkin-Gen-3?node-id=101%3A3213
![campaign page header](https://user-images.githubusercontent.com/41007222/125912046-1004654f-c376-4378-a4ac-1e905a6465da.png)

**Comment by richardolsson** [comment]
There is a problem with this design, which is that it does not include the campaign description/intro text anywhere. So that needs to be added somewhere as part of the implementation.

**Comment by djbusstop** [comment]
Closed because this will be implemented in a different PR. Not yet implemented.
