### ISSUE TITLE
refactor calendars

### ISSUE THREAD

**Issue by nehahirve** [zetkin/app.zetkin.org#294]
- [ ] The ZetkinCalendar component needs more / better tests, now that it has the calendar view and navigation logic
- [ ] Perhaps have a better label for calendar week number? Now it's just '28' instead of 'week 28' or something similar.
- [ ] There is an inRange() function being used for both tasks and events -- check for consistency of use and extract to a util?
- [ ] Another function to possibly be extracted is a function that returns another date given a date and an offset in days (24 hour periods). We use this functionality frequently, I think
- [ ] Extract calendar bar to it's own component, and remove `orgId` from the props, can be inferred from the router

**Comment by richardolsson** [comment]
These have been rebuilt.
