### ISSUE TITLE
using OrganizeTabbedLayout on all campaigns page results in a bad call to useQuery

### ISSUE THREAD

**Issue by nehahirve** [zetkin/app.zetkin.org#296]
When using the tabbed layout on all campaigns pages, useQuery tries to fetch single campaign data with `undefined` as the campId, resulting in a console error (and a needless call). 

Putting the hook inside a conditional raises other warnings related to react. 

There are probably multiple solutions to this

**Comment by richardolsson** [comment]
Do you know why this is happening? Isn't the `campId` available on all these pages? Will this be fixed by #263?

Just asking to provide some more information to whoever takes on this issue.

**Comment by nehahirve** [comment]
The tabbed layout on a single campaign page uses `const campQuery = useQuery(['campaign', orgId, campId ], getCampaign(orgId  as string, campId as string))` to get the campaign title to render as the page heading. 

But the same layout is used on all campaigns pages which have no `campId`. `campId` is inferred from the router -- there is render logic that checks if it is defined and renders accordingly, but useQuery still runs, and it's risky to put the hook inside a condition

**Comment by nehahirve** [comment]
Actually a very simple solution is to use the enabled property on usequery. enable if campId exists!

**Comment by richardolsson** [comment]
That sounds like an easy fix, but IMO it feels weird that the layout is retrieving any data at all. I've elaborated on this in https://github.com/zetkin/app.zetkin.org/issues/263#issuecomment-882331693

Let's keep both issues around for now, but whoever takes them on can decide which route to take.
