### ISSUE TITLE
Implement action buttons and submenu on header of each page

### ISSUE THREAD

**Issue by djbusstop** [zetkin/app.zetkin.org#313]
See #312

Need to decide which action buttons and which submenu items are needed on each page.

**Comment by richardolsson** [comment]
I've started noting down what actions exist for the various objects. This list will keep evolving for some time as more things surface (and as I have more time to go through it more thoroughly).

## Object actions inventory
### Event
* Edit
* Delete
* Move to campaign
* Send reminders (maybe not part of actions section at all?)

### Task
* Edit
* Delete
* Move to campaign
* Publish (primary action button)

### Campaign
* Edit
* Delete
* Archive
* Publish (primary action button)

### Person
Also see "Admin" tab in wireframes.
* Edit
* Remove from organization
* Delete from entire database
* Merge with… (other people)

### PersonView
* Delete
* Move to folder
* Download
* Filter (not in sub-menu)
* Add tab (not in sub-menu)

### Survey
* Edit
* Archive
* Delete

### Call assignment
* Edit
* Delete
* Close (set end date), which is similar to archive?

**Comment by richardolsson** [comment]
No longer relevant.
