### ISSUE TITLE
Add CREATE_TASK to Campaign calander page speed dial

### ISSUE THREAD

**Issue by djbusstop** [zetkin/app.zetkin.org#330]

**Comment by omidhq** [comment]
Is adding CREATE_TASK meant for `organize/[orgId]/campaigns/[campId]/calendar` or `organize/[orgId]/campaigns/calendar` or both? @richardolsson @djbusstop

**Comment by richardolsson** [comment]
> Is adding CREATE_TASK meant for `organize/[orgId]/campaigns/[campId]/calendar` or `organize/[orgId]/campaigns/calendar` or both? @richardolsson @djbusstop

Only the one for a specific campaign (i.e. including `[campId]`) for now.
