### ISSUE TITLE
refactor smartSearch interface

### ISSUE THREAD

**Issue by nehahirve** [zetkin/app.zetkin.org#337]
### code Refactors
- [ ] Test whether we can reduce code complexity by assigning ids on creation of new filters, rather than addition to array
- [ ] Fix long lines
- [ ] pass in `config `to `getTimeFrameWithConfig()` directly
- [ ] improve label naming in .yaml and write documentation
- [ ] rename `target` to `query`
- [x] use PascalCase for interfaces
- [x] refactor `useSmartSearch` hook to type `initialFilters` better
- [x] refactor `DisplayMostActive` message ids to not use `type` variables
- [ ] change the scope of 'quantity, query, and other yaml messages to their own 'widgets' scope
- [ ] remove comment to disable eslint exhaustive dependencies from tops of files and add them back to individual cases
- [ ] refactor reduce back into map ; make sure to handle deleted tags -> https://github.com/zetkin/app.zetkin.org/pull/343#discussion_r682536003
- [ ] rename `ZetkinDataField` interface to `ZetkinPersonField`

### Improvements
- [ ] localize dates by passing in Dates instead of date strings to `FormattedMessage`
- [ ] Handle deleted resources in filters that use resources like `campaign`, `survey`, `activity`, etc.
- [ ] Handle loading states and errors in a good way -- preload data and check if valid?
- [x] #341
- [x] move assignees pages under `/calendar`
- [ ] bug in max value of person tags filter - https://github.com/zetkin/app.zetkin.org/pull/343#discussion_r682419629

### Design

- [x] Improve design of query overview - centered text and button and placement of icons

**Comment by richardolsson** [comment]
There have been some refactoring done to this, and I'm hesitant to keep this issue as it's very old by now and I'm not sure what is still relevant. There are upcoming changes to Smart Search that will be documented anew when time comes.
