### ISSUE TITLE
bug in call_history

### ISSUE THREAD

**Issue by nehahirve** [zetkin/app.zetkin.org#350]
NB: Can no longer reproduce this bug

When clicking edit existing filter button --
This bug exists in main

![image](https://user-images.githubusercontent.com/62522290/128202189-80034c38-7b08-4766-aab4-89ca19cb76d9.png)

**Comment by richardolsson** [comment]
I see you've edited the description to indicate you can't reproduce the issue. I've also never been able to reproduce it, so unless you have any reason to believe it's still relevant I think it would make sense to just close it. 😊

**Comment by nehahirve** [comment]
Closing because I still can't reproduce
