### ISSUE TITLE
Tweak color scheme

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#357]
I feel like the colors used are not entirely inline with the Zetkin visual identity. The accent color used by Zetkin should be `#EE323E`.

Here is the full table of colors from the visual identity documentation:

![image](https://user-images.githubusercontent.com/550212/128594505-c76760ea-e436-48a6-bcfc-3d294c8885c6.png)

**Comment by djbusstop** [comment]
One place to use the new colours is the submit buttons of our forms. This will be a bit tricky to implement in the theme...

**Comment by richardolsson** [comment]
This is happening as part of new design system work.
