### ISSUE TITLE
Handle (non) timezones in ZetkinRelativeTime

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#366]
The javascript `Date` object is always interpreted in the local timezone. Zetkin time is timezone-agnostic, but poses as UTC. This is ultimately a shortcoming in Zetkin that needs to be fixed eventually, but for now, the times from Zetkin should displayed as they are delivered, not translated to any other timezone.

This means that the ISO time 1986-03-21T13:37:00.000Z (which happens to be my time of birth) should be displayed to the user as 1986-03-21, 13:37:00, _regardless of device time zone_.

When this is parsed into a `Date` and then rendered, the browser will render it as 1986-03-21, 15:37:00 to me, because 13:37 UTC is 15:37 _in my local timezone_.

The `<ZetkinRelativeTime>` component renders "2 hours ago" for something that happened seconds ago.

I'm not entirely sure how to fix this, but we managed to do it in Gen2 and in the Gen3 calendar interface.

**Comment by nehahirve** [comment]
The issue seems to stem from when the task is created, the Dates in the API get 'corrected' so that when I create a task with a publish time less than an hour from now, it gets created as a task with a deadline that's already passed. Will look into this
