### ISSUE TITLE
Alert style

### ISSUE THREAD

**Issue by omidhq** [zetkin/app.zetkin.org#381]
The aim is to make the `alert` stand out against the grey background color. See #344 

<img width="1355" alt="scc" src="https://user-images.githubusercontent.com/2996847/130200420-e5ef2be7-54b3-4b9e-8a7d-11368fc1cbb6.png">

**Comment by richardolsson** [comment]
We need to pick colors for all four levels of the `alert`, which by default look like this:

![image](https://user-images.githubusercontent.com/550212/130209858-9ed0b510-9780-4d72-88ea-5b4de8473a24.png)

**Comment by richardolsson** [comment]
Another usage for alerts to be taken into account.

![image](https://user-images.githubusercontent.com/550212/130210910-0136af52-797b-4c6e-984d-1f7fc2c40a92.png)

**Comment by GemCopeland** [comment]
![Notification alerts](https://user-images.githubusercontent.com/2996847/130258346-f45c80e4-36fb-4202-8f04-74beb258d717.png)

Error: FFB5B1
Warning: FFECB3
Success: C8E6C9
Info: 464646 (the blue felt out of place with the rest of the colour palette, as a "general" colour)

The default icons look fine!

**Comment by richardolsson** [comment]
Beautiful @GemCopeland! How did we ever manage without you!?

Does this mean that the slightly more turquoise green from your first screenshot in #344 (re-posted by Omid in the issue description) should be replaced by `#C8E6C9`?
