### ISSUE TITLE
Date/time pickers timezone issues

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#384]
Related to tasks, where you can set several time fields. 

It seems to me that picking a time happens in the local timezone, but the time is then saved in UTC, which means that the picker flashes as the object is saved.

May or may not be related to #366

**Comment by nehahirve** [comment]
Fixed in #391 @djbusstop ?

**Comment by djbusstop** [comment]
The times will now be saved in the local time zone in #391

**Comment by richardolsson** [comment]
I've confirmed this to be working while reviewing #391. 🎉
