### ISSUE TITLE
Event Action Buttons

### ISSUE THREAD

**Issue by djbusstop** [zetkin/app.zetkin.org#397]
### Description
Subtask of #225 
Action buttons on the event page similar to the Task and Campaign action buttons. These buttons allow the user to edit and delete an event, and see the public page.

### Requirements
- [ ] Impact button shows "Public Page" and navigates to the public event page on click (Initially this will likely redirect to the existing public events page from Gen2)
- [ ] A menu with the following options:
  - [ ] "Edit event" button which opens the Event form
    - [ ] The `CreateEventForm` needs to be extended to support editing. It would be good to rename it to `EventDetailsForm` so it's clearer. 
  - [ ] "Delete event" which opens a modal with a button to confirm deletion 

### Implementation Proposal
See the `TaskActionButtons` for an example. This might be a time to create a generic `ConfirmationModal` which can be used wherever we use delete confirmations. Also look at how to reduce code duplication for example having a reusable action buttons menu, or action buttons components. Not required, but this will be the third time this is implemented, and may be worth considering making more reusable components.

### Open Questions
- Do we need to have a menu item for "sending reminders"? See the linked epic for more info.

**Comment by richardolsson** [comment]
No longer relevant since UX design has changed since this was first outlined.
