### ISSUE TITLE
Add `ACTIONS.CREATE_EVENT` to speed dial

### ISSUE THREAD

**Issue by djbusstop** [zetkin/app.zetkin.org#398]
Subtask of #225 

### Description
The `createEvent` action was removed from the MVP scope. When adding full support for events back in to the app, we need to add it back to the speed dial wherever it should be used.

### Requirements
- [ ] The `ACTIONS.CREATE_EVENT` action should be implemented in the speed dial in the following pages
  - [ ] Single Campaign Details Page
  - [ ] Single Campaign Calendar Page
  - [ ] All Campaigns Page
  - [ ] All Campaigns Calendar Page

**Comment by richardolsson** [comment]
No longer relevant since speed dial has been removed.
