### ISSUE TITLE
Create Campaign form not validated

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#413]
I can submit an incorrect campaign which does not properly redirect to the new campaign page (because creating it failed), but also does not show an error message.

Steps to reproduce:

1. Navigate to /organize/1/campaigns
2. Open create campaign form through speed dial
3. Fill out only title
4. Submit the form

Expected results: An error saying I have not filled out all required fields
Actual results: Nothing happens

**Comment by richardolsson** [comment]
@djbusstop Have you started working on this task? Are you in need of any more information or should we reassign?

**Comment by djbusstop** [comment]
This is being resolved in #425 . If the server returns an error, then it will show an error message.

**Comment by djbusstop** [comment]
Will investigate this further before closing

**Comment by djbusstop** [comment]
@richardolsson I just tried this in my new branch and it successfully posts and creates a campaign. Looks like title is the only required field server side. Should we close this then? If you think other fields should be required, we can enforce that on the client side. Just let me know which ones should be required. @richardolsson

**Comment by richardolsson** [comment]
I think you're right, and I don't think this was ever a problem. I tried to reproduce it some time after creating it but couldn't. So maybe I was wrong all along. But the bottom line is it's working now, and that's what matters. Closing! 😊
