### ISSUE TITLE
Plan what is fetched from the Zetkin API on the client and what is fetched on the next server

### ISSUE THREAD

**Issue by djbusstop** [zetkin/app.zetkin.org#426]
### Description
Presently almost all pages "prefetch" the Zetkin API data, which means that requests must resolve before the page will be built. A benefit of this is we don't need to handle loading states because the page will load with the data. But this still may not be the best way to query the data.

This task is to write out what data on each page should be fetched server side in `getStaticProps`, and what data should be queried.

The requirements should be fulfilled in a comment below, and from there can be made in to new issues.

### Requirements
- [ ] Write out what requests are made on each page
- [ ] Write out if they would be better as server or client side
- [ ] Write out what components would be impacted if this request should be moved, and if there would need to be any new designs such as a loading indicator.
- [ ] Write out any prefetch requests which are not actually used in the current design

#### Example
- `org/[id]/campaigns`
  - request `getOrg`
    - Should remain as server side query
  - request `getCampaigns`
    - Could move to client side query
      - Impacts - Campaigns list would need a loading indicator.

### Design specifications
Any place we change the request from server to client, we will probably need a loading indicator. Need to get input from design regarding the loading indicator designs.

**Comment by richardolsson** [comment]
We (almost always) need to use `getServerSideProps()` (not `getStaticProps()`) because otherwise we can't have user authorization, which differs per request, on the API calls made by the server.
