### ISSUE TITLE
Creating a blank view

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#469]
## Description
A user should be able to create a new, blank view to be populated with data.

## Relevant job stories
* When I have an organizing or reporting task that could be solved by assembling a spreadsheet, I want to be able to create a custom view with only the data that I need, so that I don't have to export data and collect it outside of Zetkin
* When I'm about to create a new view, I want to see all the saved views in the organization so that I can see if there is already a suitable one for my needs before I create one

## Prerequisites
Don't start working on this until the following issues have been solved:

* #467 
* #486

## Requirements
- [x] There should be a floating action button, that when clicked creates a view (no modal)
  - [x] Creates a new, empty view named "Untitled View" ( `POST /orgs/{org_id}/people/views`)
  - [x] Adds two columns to the view for `first_name` and `last_name` (`POST /orgs/{org_id}/people/views/{view_id}/columns`)
  - [x] Navigates to the page of the new view
- [ ] An error message should be displayed if creating the view fails

## Possible implementations
Maybe use a simple [MUI Floating Action Button](https://mui.com/components/floating-action-button/), instead of a "Speed Dial" as there is only one option here (for now).

## Design specifications
Wireframes below point out the FAB and how to navigate from view listing to the new "Untitled view". The two individual screens are tracked separately.

![image](https://user-images.githubusercontent.com/550212/139213906-35950962-72cd-439c-8858-1d41b3ec7d8e.png)

## Open questions
* How/where do we display the error message if creating a view fails (e.g. network troubles). @GemCopeland please advise

**Comment by richardolsson** [comment]
I'm afraid the loading indicator might be difficult because the MUI library does not seem to support integrating a loading indicator with a FAB like that. But we'll see what we can do!

**Comment by GemCopeland** [comment]
Oh weird, I found it on the Material design guide. But it must be outdated. In that case, I think just the linear progress indicator at the top of the screen is good 👍
