### ISSUE TITLE
Delete a View (from list and single-view page)

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#472]
## Description
A user should be able to delete a view that is no longer relevant to them, from one of two places in the interface:

* In the views list page, where there should be an ellipsis menu (⋮) on each line
* In the view details page, where there should be an ellipsis menu in the header

## Relevant Job Stories
*  When I no longer need a view, I want to be able to delete it so that the list does not become cluttered

## Prerequisites
This task has no prerequisite issues, although part of it assumes that #468 has been implemented. If not, just ignore those parts. More information below.

## Requirements
- [x] Implement ellipsis menu with delete option in view listing
- [x] Implement ellipsis menu with delete option in view page header
- [x] Clicking delete anywhere should open a confirmation dialog (similar to deleting campaign)

## Possible implementations
Use the existing menu solution in the `TabbedLayout` for the view page (unrelated to the listing one).

Relevant API resources:
* `/orgs/{org_id}/people/views/{view_id}` (`DELETE`)

### On list page
Note that the "Suggested" cards at the top are subject to #468 being implemented first. If not, just ignore them.

![image](https://user-images.githubusercontent.com/550212/142839956-2a03bdef-abda-4f38-83b7-c0f2122d0b75.png)

### On details page
![image](https://user-images.githubusercontent.com/550212/142840137-bccee88b-f174-49a1-a84f-b56a059e21d5.png)

## Open questions
No outstanding questions at this time.

**Comment by richardolsson** [comment]
Maybe it's not a great idea to allow this to be done in a menu on the "Suggested" view card? In that context, the "delete" action can be ambiguous, and I can imagine users clicking it thinking that it will remove the "suggested" card, and losing data when it actually deletes the view.

It's worth thinking about. Maybe it's just a language issue, and this can be prevented by consciously wording the label to avoid misunderstanding.

**Comment by djbusstop** [comment]
I'll leave out the delete function from the suggested cards at the mo until we decide. I agree that writing "Permanently delete view" would make it clearer, but even then, I don't think it needs to be there.
