### ISSUE TITLE
Copy view (from list and single-view page)

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#477]
## Description
A user should be able to copy a view so as to not have to start from scratch when doing recurring tasks that require new views (e.g. organizing the same thing, the same way, every year).

## Relevant Job Stories
* When I'm about to create a new view, I want to be able to use an existing one as a template or copy an existing one, so that I don't have to start from scratch

## Prerequisites
No prerequisites, although the ellipsis menu referenced in this and multiple other issues does not yet exist at the time of writing.

## Requirements
- [x] There should be an ellipsis menu everywhere that a view is represented (suggested card, list, and single-view page)
- [ ] The ellipsis menu should contain an option to "Duplicate view"
- [ ] Clicking to duplicate view should create a new view with the same columns, content query and rows (if any) as the original one, and name it 'Copy of "Original name"', then navigate to the new view

## Possible implementations
Look at how creating a view is implemented using a "middle-end" API endpoint. Something similar should be possible to do for copying a view, so that the NEXT back-end can make all the necessary Zetkin API requests without having to pass data to/from the client.

## Design specifications (old wireframes but still applicable)
![image](https://user-images.githubusercontent.com/550212/146550032-308130e7-1617-42b3-960c-3469ddf07ccb.png)

![image](https://user-images.githubusercontent.com/550212/146549228-bdaad779-87eb-4f67-b8ad-4c8ff00216fe.png)

## Open questions
* Is the "copy columns/everything" option (nice-to-have) good, or should we have two separate options in the menu?

**Comment by richardolsson** [comment]
Postponing this indefinitely.

**Comment by ziggabyte** [comment]
Having the possibility to copy an existing view, to use the same collection of columns connected to a different Smart Search or manually adding people, was mentioned as a feature request by a user in SV. Noting this here.

**Comment by richardolsson** [comment]
This is actually a really nice feature. I'm updating it to reflect the current state of UX.

**Comment by richardolsson** [comment]
"Views" is the old name for "Lists", and remains in the code.

To get the list: /api/orgs/ORG_ID/people/views/LIST_ID
To get the columns: /api/orgs/ORG_ID/people/views/LIST_ID/column

**Comment by richardolsson** [comment]
@Herover will work on this!
