### ISSUE TITLE
Collapse/expand View header

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#479]
## Description
It should be possible to collapse the page header (title, breadcrumbs etc) to make more room for the view table.

## Relevant job stories
* When I'm navigating my view, I want to be able to hide all unnecessary chrome, so that I can browse the view unincumbered and see as many rows and columns as possible in my browser window

## Prerequisites
Don't start this issue until the following have been completed:

* #486 

## Requirements
- [ ] Show a link which toggles between collapsed/expanded header
- [ ] Smooth transition between two states

## Possible implementations
Basic changes to styling.

## Design specifications
There should be a small link with an icon on the right hand side, and a smooth transition between the two states below when clicked.

![image](https://user-images.githubusercontent.com/550212/139535050-9648da2b-5ac3-46a7-8bdc-32b3983ec9cd.png)

## Open questions
None

**Comment by lowlandjuju** [comment]
@richardolsson happy to look into this one 😀

**Comment by lowlandjuju** [comment]
Thoughts on the solution: 

The visual example above shows the user freeing up like 50-100px of space, which seems almost not worth it. If the intention is to aid users who wish to focus exclusively on the view for a certain period,  then why not collapse the entire header space into a floating button in the top right - an "expand" icon button?

**Comment by richardolsson** [comment]
> The visual example above shows the user freeing up like 50-100px of space, which seems almost not worth it.

With the screen aspect ratio in the wireframes, I can see why it would seem like that. But on smallish screens with a very wide aspect ratio, where the viewport is maybe just 700px tall, freeing up another 100px is actually quite a significant. That said, the more we can free up, the better. 😊 

> If the intention is to aid users who wish to focus exclusively on the view for a certain period, then why not collapse the entire header space into a floating button in the top right - an "expand" icon button?

I like the idea of a floating "expand" button, but I think it's nice to still have the breadcrumbs visible. Here's a counter-suggestion. 😊 

When collapsed, move the title ("Activists for campaign") to the end of the breadcrumbs, and hide everything else in the header. That makes the header just one "row" tall. Then show the expand button at the top right, next to or instead of search.

What do you think @GemCopeland?

**Comment by lowlandjuju** [comment]
Sounds very reasonable @richardolsson :-)

**Comment by GemCopeland** [comment]
> When collapsed, move the title ("Activists for campaign") to the end of the breadcrumbs, and hide everything else in the header. That makes the header just one "row" tall. Then show the expand button at the top right, next to or instead of search.
> 
> What do you think @GemCopeland?

Sounds good. Only thing I'd say is that search should remain, so the expand button should be next to it.

**Comment by lowlandjuju** [comment]
Hi @GemCopeland! I've pushed a branch for this, with a basic solution. It doesn't hide the search component, but then it looks like the search component has not yet been implemented :-D (is that [this one](https://github.com/zetkin/app.zetkin.org/issues/481), @richardolsson?)

**Comment by richardolsson** [comment]
> Hi @GemCopeland! I've pushed a branch for this, with a basic solution. It doesn't hide the search component, but then it looks like the search component has not yet been implemented :-D (is that [this one](https://github.com/zetkin/app.zetkin.org/issues/481), @richardolsson?)

No, the (globa) search feature (which is the one being referred to here) is tracked by #454.

Let's discuss your solution in the PR. Will take a look soon!
