### ISSUE TITLE
Free-text search in view

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#481]
## Description
A user should be able to search for piece of text and find only those rows which match that string, e.g. names, survey responses or whatever might be *visible* in the view.

## Relevant Job Stories
* When I'm looking for patterns in my view, I want to be able to filter the columns based on the data therein so that I can hide those rows that are not relevant to what I'm doing

## Prerequisites
This task can be started without prerequisites, although it's related to #482 and #497 which both require the addition of the (at the time of writing) not yet existing toolbar.
- [x] There should be a toolbar 

## Requirements
- [ ] There should be an option in the toolbar that opens a search pop-over
- [ ] The pop-over should include a search field
- [ ] Typing into the search field should filter the rows of the view

## Possible implementations
There is an example of how to implement this, called [Quick filter](https://v4.mui.com/components/data-grid/filtering/#quick-filter) in the MUI docs. Basically it does the filtering of rows outside of the grid.

Note that the contents of a view cell may be complex, i.e. objects of multiple properties. The searching will need to consider this, e.g. by searching the cells differently depending on column type.

Consider using React Suspense (if possible) to make sure that the search field remains responsive?

## Design specifications
![image](https://user-images.githubusercontent.com/550212/142976140-45714dea-d272-4213-814f-65d1c67017c6.png)

## Open questions
No outstanding questions at this time.

**Comment by lowlandjuju** [comment]
@richardolsson I think this is a good candidate for https://github.com/reactwg/react-18/discussions/41
But it means upgrading to `next@latest react@rc react-dom@rc` - thoughts? :)

**Comment by richardolsson** [comment]
> @richardolsson I think this is a good candidate for [reactwg/react-18#41](https://github.com/reactwg/react-18/discussions/41) But it means upgrading to `next@latest react@rc react-dom@rc` - thoughts? :)

I would love that, but I don't think we're ready quite yet. Especially not this close to release.

I think we should do it in R31 though, also related to #234. What do you think?

**Comment by lowlandjuju** [comment]
I think it depends on how large the views are - do we know what the largest view size is on production Zetkin Platform? (i.e. how  many rows)

**Comment by richardolsson** [comment]
> I think it depends on how large the views are - do we know what the largest view size is on production Zetkin Platform? (i.e. how many rows)

They are currently in the thousands, not more. I'm pretty sure filtering synchronously will be fine, and we can always upgrade later (along with many other concurrent React features that we will want to implement).

I think the big part of this task is to generate the values that are actually filtered (e.g. when there's a complex value, like an object, the algorithm needs to know what fields on the object are relevant when filtering, and how) and that will translate even if we change to `startTransition()`, don't you think?

**Comment by lowlandjuju** [comment]
I mean, if it's small numbers, why not just search every key of every object? Maybe just with some static exclusions, and maybe a minimum limit on the search query before filtering executes

**Comment by richardolsson** [comment]
> I mean, if it's small numbers, why not just search every key of every object? Maybe just with some static exclusions, and a minimum length limit on the search query before filtering executes

The reason I can think if not to just search every key of every object is that not every key of every object may be relevant relevant. I'm not sure if this matters in practice, so if you want to try it that way to begin with, I think it sounds like a good idea! 😊

**Comment by richardolsson** [comment]
Postponing this indefinitely
