### ISSUE TITLE
Pretty cell rendering for all View column types

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#487]
## Description
The View Data Grid should render pretty cells for all column types. In a future iteration they will also be made interactive, but for now, it's mainly important that cells in all columns look good. Simple columns (e.g. name or e-mail) can be just text, but more complex column values (e.g. a person link, or a boolean on/off state) should be rendered more nicely.

## Relevant job stories
* When I'm adding a column, I want it to automatically populate with data from Zetkin so that everything stays in sync
* When I'm adding a column, I want to be able to choose from one of several types so that I can work with any type of data from Zetkin in the view. These are the options currently:
  * …a field column that renders a field from a person record, so that I can see things like names, phone numbers and addresses in views
  * …a Smart Search query cross-reference column and pick a Smart Search, so that I can see whether each person in the view also matches that Smart Search query
  * …a survey response column and pick an existing survey and question, so that I can see for every person what they have responded (if anything) to that question
  * …a survey submit date column and pick a survey, so that I can see for every person what date they submitted that survey (if at all)
  * …a "notes" column, so that I can see the most recent note on each person
  * …a tag column and pick a tag, so I can toggle that tag on/off for people in the view individually
  * …a "toggle" column that I can toggle on/off for each person
  * …a person column, so that I can assign and reassign an organizer to each person record in the view

## Prerequisites
* #486 

## Requirements
- [x] Columns of type `local_person` should display the avatar of that person
- [x] Columns of type `local_bool`, `person_tag` and `person_query` should display a boolean state (checkmark)
- [x] Columns of type `person_notes` should render an excerpt of the most recent note returned
- [x] Columns of type `survey_submitted` should render the date of the most recent submission returned
- [x] Columns of type `survey_response` should render the text of all responses returned

## Possible implementations
The MUI X Data Grid component can be configured with [separate render functions for each column](https://mui.com/components/data-grid/columns/#render-cell). That may be a suitable solution.

## Design specifications
No specifics available. I'm including a general depiction of the view table wireframes below.
![image](https://user-images.githubusercontent.com/550212/139231185-87b57533-f498-4156-9634-cda732bb238a.png)

## Open questions
* What should the different column cells look like? Mainly the `local_person` and boolean ones may require some design. @GemCopeland please advise

**Comment by GemCopeland** [comment]
Hey @richardolsson,

I've made a design for the rows, which you can see on Figma – [a mockup of a view](https://www.figma.com/file/dnJiIWWZVLgcLILUnDOySa/Zetkin-Gen-3?node-id=516%3A8052) and an [overview](https://www.figma.com/file/dnJiIWWZVLgcLILUnDOySa/Zetkin-Gen-3?node-id=529%3A8895) of the different cell types you've mentioned.

![Rows](https://user-images.githubusercontent.com/2996847/139712977-6c81c272-c1bd-4359-9196-ec335b8922ac.jpg)
![View](https://user-images.githubusercontent.com/2996847/139712983-c3f63adf-288d-4624-b623-5419e5a5003c.jpg)


A few things to note:

1. I like the colourful avatars you use in Gen 2, it would be nice to keep those. I've kinda put them floating next to the name rather in the column called Avatar, as I thought that would be a bit strange. But not sure if it'll work technically to have them like this!

2. With the survey responses… displaying the full text would definitely ruin the layout of the table and how scannable it is. Would it be possible to add a text wrap option somewhere in the top bar, like on Google sheets? Then you could choose to have it truncate the text into a single line or wrap around to show the full text.
<img width="89" alt="Screenshot 2021-11-01 at 17 19 49" src="https://user-images.githubusercontent.com/2996847/139712906-81a15770-50ca-4eac-9648-8578d02f6194.png">

You may notice a slightly different nav rail! I'll make a separate issue to discuss that.
