### ISSUE TITLE
Move the floating `Create` button somewhere more prominent

### ISSUE THREAD

**Issue by GemCopeland** [zetkin/app.zetkin.org#489]
This is a suggested improvement for a future release rather than anything urgent, but I just wanted to get some thoughts down @richardolsson.

I've started to doubt the placement of the Floating Action Button / speed dial on the bottom right. Having a FAB on the bottom right of the screen works well for mobile as it makes it easy to tap it when holding a phone. However, it doesn't make as much sense on desktop. 

Usually when you look at a heatmap of a desktop website or app, people stay at the top left corner and sometimes scan down on the left side. The bottom right corner is usually a pretty "cold" area. It's also where you'd normally see a customer chat like Intercom, and the FAB looks quite similar to one of those.

My counter proposal is to have the FAB in the navigation rail on the top left, below the logo:

![Navigation rail](https://user-images.githubusercontent.com/2996847/139869747-3e2c02b9-1472-4419-ab10-c6bed68efc07.jpg)

However, this wouldn't really work as a speed-dial with multiple options. ~I think this could perhaps be solved in a different way, where clicking the FAB opens a menu on the right of the nav rail (kind of like the [Persistent action tooltip](https://mui.com/components/speed-dial/) example here).~

EDIT: 
Just noticed that the "New" button in Google Drive opens a menu like this:

<img width="318" alt="Screenshot 2021-11-02 at 16 12 24" src="https://user-images.githubusercontent.com/2996847/139900772-b7387846-3b57-4edd-b679-675c363da0e2.png">

I think that's quite a good option for Zetkin too.

Otherwise, I think we should move it so it sits alongside the tabs on the top right:

![Navigation rail - alternative](https://user-images.githubusercontent.com/2996847/139869829-78f21a06-b233-486d-954b-589f15676c6c.jpg)

I also think the current navigation icons aren't all as self explanatory as they could be, so. it would definitely be an improvement to either display their title on hover and/or make the sidebar expandable so you can choose to see the labels next to the icons.

![Navigation rail - expanded](https://user-images.githubusercontent.com/2996847/139869879-7d27030b-5471-4211-a45a-20e841d6844a.jpg)

**Comment by richardolsson** [comment]
I was hesitant at first about moving it, but I’m starting to warm up to it. 😊 

So far, I best like the idea of having it on the right-hand side. My only concern right now is that I don't think we have enough understanding about the full breadth of UI requirements yet to make a final decision. For instance, if we need to add a FAB (or "create actions" more importantly) to the single-view page, would it collide with other elements? Same goes for the calendar pages.

So I think we should leave this issue open and come back to it when we've looked at more sections of the Zetkin UX.

**Comment by richardolsson** [comment]
Hi @GemCopeland! 👋 

We have moved away from the FAB entirely, so I'm closing this as no longer relevant.
