### ISSUE TITLE
Remove person from view

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#493]
## Description
A user should be able to remove a person from a view, without removing the person from the database.

## Relevant job stories
* When a person is no longer relevant to the work I'm doing in my view, I want to be able to remove them only from the view, so that they disappear from the view but still exist in Zetkin

## Prerequisites
None

## Requirements
- [x] There should be a toolbar 
- [x] There should be a column of checkboxes for selecting people in a view
- [x] When at least one person is selected, there should be an option in the toolbar above the table to remove them

## Possible implementations
Delete from view using API request to `DELETE /orgs/{org_id}/people/views/{view_id}/rows/{person_id}`

## Design specifications
![image](https://user-images.githubusercontent.com/550212/142726836-5aaacbf7-17bc-444f-b152-faa1f160cb82.png)

## Open questions
I can't think of any.

**Comment by lowlandjuju** [comment]
@richardolsson also this one - fullstack good for learning...

**Comment by richardolsson** [comment]
> @richardolsson also this one - fullstack good for learning...

Cool! 🙌 

Have a go, and let me know if you need any hints. 😊

**Comment by lowlandjuju** [comment]
@richardolsson @djbusstop several issues depend on a single component that doesn't exist yet: the toolbar that sits above the table. The issues are this one, plus #497, #481 and #482 - so I've added "There should be a toolbar" to the prerequisites of those other issues, and then added "There should be a toolbar" as a requirement for this task - hope that's ok: just to try and avoid duplicated effort on the toolbar task...

**Comment by richardolsson** [comment]
Actually @djbusstop might implement the toolbar in #499 (which she is taking over from me for the day). Just to make sure you're not both working on the same thing.

**Comment by lowlandjuju** [comment]
Holding off on this for now 👍

**Comment by richardolsson** [comment]
It should be possible to start work on this now. The toolbar was added in #499 and the checkboxes to select rows were added in #521.
