### ISSUE TITLE
View sorting

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#497]
## Description
A user should be able to sort a view on one or multiple columns.

## Relevant job stories
* When I'm trying to make sense of the data in my view, I want to be able to sort the view on any column so that I can easily see the most recent/most relevant records on top

## Prerequisites
Plan along with #482 which also requires the grid header/toolbar to be added.
- [x] There should be a toolbar 

## Requirements
- [x] Clicking a column should toggle sorting (default behavior of the MUI DataGrid, but requires configuration on _how_ to sort values for non-basic columns)
- [x] There should be a toolbar with a menu for sorting
- [x] The menu should allow sorting on multiple columns

## Possible implementations
There is a section on [multi-column sorting](https://v4.mui.com/components/data-grid/sorting/#multi-column-sorting) in the MUI docs.

Configure how to sort using the `sortComparator` property of `GridColDef` when it's created in `makeGridColDef` (`ViewDataTable/utils.tsx`).

## Design specifications
See wireframes below. Note the similarities to #482.

![image](https://user-images.githubusercontent.com/550212/142975568-ae39ef1e-16b1-41b4-ba56-ab9cba3508c1.png)

## Open questions
None at this point

**Comment by lowlandjuju** [comment]
I have tried to define custom row sorting functions for two custom types - namely PERSON_NOTES & SURVEY_RESPONSE, which are both array types. The type definitions for data grid don't allow for sorting of array types, so - it is possible but it means disabling typescript for those functions.

In any case I don't see any reason to allow sorting by fields that contain array data - proposal: disable sorting by any column types that contain array data.
