### ISSUE TITLE
Edit fields on person profile page

### ISSUE THREAD

**Issue by djbusstop** [zetkin/app.zetkin.org#557]
### Description
A user should be able to edit the fields associated with a person.

### Relevant Job Stories
* When a piece of information in a field is incorrect, I want to be able to easily edit it so that I can keep the database up to date

### Prerequisites
#554 

### Requirements
- [ ] When editing, show a save and cancel button beneath

### Design specifications
https://www.figma.com/file/YFXcYN3LUhHghLb0cFqU85/Casework?node-id=1208%3A42080

![image](https://user-images.githubusercontent.com/41007222/152157114-186b8dc0-1835-49e4-8e68-47321cde7221.png)

![image](https://user-images.githubusercontent.com/41007222/152153808-d6bcd1b1-91ba-4d3e-8077-ce80e7eba056.png)

### Open questions
- Should we use the `EditTextInPlace` component directly, or click a button to trigger editing and then show `TextField` inputs in place?
  - If we use this component, maybe we can just debounce save? 
- Are all fields text fields?

**Comment by djbusstop** [comment]
@richardolsson The open questions on this one need answering before I can start on the requirements

**Comment by richardolsson** [comment]
Your questions are really good, and I don't think we have any good answers to them yet. I would love to discuss this more thoroughly. Let's chat about it on Slack and come up with a plan for how to move forward with editing?

**Comment by richardolsson** [comment]
This was resolved by #2011.
