### ISSUE TITLE
Navigating to organization sub-pages should be forbidden for non-organization officials

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#564]
## Description
Currently it's possible to open a page under the `/organize/X/…` path for anyone who's been authenticated to level 2, even if they're not an official in organization X.

## Steps to reproduce
1. Go to  /organize/1/campaigns
2. Sign in as testadmin@example.com
3. Go to /organize/5/campaigns (an unrelated organization)

### Expected Behaviour
User should get 404, or maybe be redirected somewhere else?

### Actual Behaviour
User is presented with an empty page without any campaigns on it, or perhaps a 500 error, because they do not have access to the campaigns belonging to organization 5.

## Requirements
EDIT: Algorithm described below was worked out during the conversation in this issue and on Slack.

### Server-side
- [x] On login, add available organisations to the session (obtained from `/orgs/{org_id}/people/{person_id}/connections`)
- [x] If the user tries to access an organization that is listed in their session, render the page with no further checks (it will be reconfirmed on the front-end)
- [x] Otherwise (user tries to access an organisation that _is not_ in their session), request available orgs again and wait for the result
  - [x] If the list of accessible organizations have changed to now include the requested organization, update the session and and then display the page
  - [x] Otherwise (the list of accessible organizations still does not include the requested organization), redirect to PAGE
- [x] Add route for PAGE, a custom page that informs the user that they aren't authorized to look at what they tried to look at

### Client-side
- [ ] On page load, async request (so as not to delay page load) available orgs for that user to check if they have changed
- [ ] If the requested organization is not in the list, redirect to PAGE

**Comment by lowlandjuju** [comment]
I think the way to do this is to store a user's organisations in their session at login time. Then redirect any request for organize/x, where x isn't found in the session. If they are added/removed from any organisation, then just invalidate their token so they have to log in again. 
The question of how to redirect - probably to a "you're not authorised" page would be the least confusing

**Comment by lowlandjuju** [comment]
I was actually thinking more about when a person is removed from an organisation. In that case would their token still give them access to an organisation they've already been removed from? Sounds like the answer is no, so no need to invalidate the token - just want to check to be sure...

**Comment by richardolsson** [comment]
> I was actually thinking more about when a person is removed from an organisation. 

Good point. You're correct in assuming that the token will no longer give them access, as authorization (as opposed to authentication) is verified per request.

In those cases, my cache invalidation solution would result in them being able to visit the restricted page after all (but not see the data on that page since the API will not let them access it). I'm not sure what the best thing to do would be in those scenarios.

My original idea was to just request the list of available organizations on every page load, but I liked your idea of caching them in the session for faster page loads.

A compromise solution would be to load the list of available organizations on the client after each page load, and throw a client-side error message/modal if the user no longer has access to an organization that had been cached in their session.

Making that request will likely become necessary soon enough anyway, because we will want to allow the user to switch organizations somewhere (probably left-hand side nav bar) and to do that we need to know what organizations they have access to.

**Comment by lowlandjuju** [comment]
@richardolsson I've added requirements based on our convo - can you check to see if you agree? :)

**Comment by richardolsson** [comment]
> * On page load, async request (so as not to delay page load) available orgs for that user to check if they have changed, in which case update the session

Nice! I'm not sure what this means?

> On page load, **async request (so as not to delay page load)** available orgs for that user to check if they have changed, in which case update the session

Do you mean it should happen on the client side? Or update the cache (session) in the background on the server?

With some clarification to that one point, I think it's spot on!
