### ISSUE TITLE
Restructure paths so views are at /organize/{orgId}/people

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#569]
## Description
The "Views" section should be directly at /people, since that IS the people database.

## Requirements
- [x] Move the page currently at /organize/{orgId}/people/views to /organize/{orgId}/people
- [x] Change the title of the page to "People"
- [x] Change any links (notably the one in the main nav bar) to point to the new URL

**Comment by lowlandjuju** [comment]
💯
