### ISSUE TITLE
Journeys section/home screen

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#573]
## Description
There should be a "top-level" section for Journeys, where users can find sub-sections/listings for each of the journey types/templates (#575).

## Relevant Job Stories
Not relevant

## Prerequisites
None

## Requirements
- [x] There should be a single tab, "Overview"
- [x] On the page, a list of all the journey types, which link to the listing for that type (#575)

## Possible implementations
Unknown

## Design specifications
![image](https://user-images.githubusercontent.com/550212/158855779-17d6348a-43ad-4acd-8f55-026884896710.png)

## Open questions
None

**Comment by GemCopeland** [comment]
More high fidelity design is here: https://www.figma.com/file/D4PrAup54f3vS4apqY3M7U/Journeys-MVP?node-id=1601%3A23692
![Journeys overview](https://user-images.githubusercontent.com/2996847/158941572-48f51b99-0616-4e9c-92a7-8a8c2314af58.jpg)

**Comment by richardolsson** [comment]
I think the Views page has cards similar like these. Maybe those could be reused (or inspiration) somehow?

**Comment by GemCopeland** [comment]
I realised there were slight differences in the card design 😅 so updated version is [here](https://www.figma.com/file/D4PrAup54f3vS4apqY3M7U/Journeys-MVP?node-id=1601%3A23692):
![Journeys overview](https://user-images.githubusercontent.com/2996847/159758716-5810e783-e355-4ce8-bbc4-cbb29920994c.jpg)
