### ISSUE TITLE
Journey listing (by type)

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#575]
## Description
A user should be able to find a list of all journeys of a specific type, e.g. all cases, on a page dedicated for that list.

## Relevant Job Stories
The following are job stories that have come out of the research we've done with a union. Other job stories in other contexts may be relevant as well.

* Whenever a member fills out the contact form on the UVW website, I want to be able to see that enquiry in the system.
* When a case comes in through the web form, I want to be able to find it in the system so that I don't have to transfer it manually from one system to another
* When I'm looking up a case, I want a brief written summary, so that I know the gist of what the case is about
* When a case ends, I want to be able to log the outcome in the system, so that we can keep track how many cases we win or lose
* When a member shows proof of payment, I want to indicate in the system that the amount has been paid, so that we can stop chasing payment
* When a case settles, I want to log that in the system so that we can separate it from win or lose
* When I'm making complex reports, I want to be able to download the raw data of all cases, so that I can analyze it in other software
* When I'm managing my time, I want to be able to indicate how big a case is, so that I can signal to others what my workload is
* When we win a case, I want to log the amount won in the system, so that we can keep track of the financial impacts of our case work
* When more than one caseworker is working a single case, I want to be able to find that case based on either caseworker, so that I don't need to know who's the "main" one
* When I'm looking for cases based on caseworker involved, I want to find those where a caseworker participated, so that I can find cases even if they're not assigned to that caseworker
* When I have some time to spare, I want to be able to see what is going on in the union’s cases, to look for legal angles to organizing efforts
* When I start my day, I want to see open cases where I'm assigned, so that I can find all the cases that I'm currently working on
* When I'm looking for my next case to work on, I want to see the member's name, their employer and the case category in a table along with information about what's urgent, so that I can easily find the next relevant case to work on
* When a new case comes in, I need to be made aware so that I can assign it

## Prerequisites
It won't be possible to build this page until the API exists, but the table component that is central to the page could be built using mock data.

## Requirements
- [x] The page should be at /organize/{org_id}/journeys/{journey_id}
- [x] The title should be the plural name of the journey, available in the data model from the API
- [x] There should only be one tab for now: Overview
- [x] The main content should be a table with the characteristics described below

### Main table
![image](https://user-images.githubusercontent.com/550212/158752494-1d1c5cbb-bc69-412a-b954-feb13c889abc.png)

This table is quite special. It contains both "static" columns that are defined in the code for the common fields on all journeys and columns that are generated based on the data that is loaded into the table. In some sense they're similar to views on a very high-level conceptual sense (customizable table), and also in that they both will use the same MUI component, but it's probably more confusing than helpful to try to think of the two as the same thing since most of the logic inbetween the high-level concept and the concrete component is very different.

Every row in the table represents a single journey.

#### Static columns
The "static" columns are always there, regardless of the data. They map 1:1 to the journey resource returned from the API, and their values can be found on attributes on that resource. Those columns include:

* ID
* Title
* Summary, capped at a sensible max length in table
* People (can be several)
* Assigned To (can be several)
* Creation date
* Next milestone
* Next milestone deadline
* Last updated

#### Dynamically generated columns
All other columns are generated from the list of tags assigned to each journey. The columns are a visual feature only, and are "generated" on the fly as the data is rendered.

In the case of **value tags**, they each map to a column in the table. For every value tag (e.g. "Amount Won") that is encountered on any journey, a column should be created. The value for each row should be the value assigned to the tag on that journey.

For **regular tags**, each new _tag group_ encountered in the data should create another column in the table. This includes the `null` group ("Ungrouped"). Every column represents a single tag group. If some journeys in the table have tags from group X and other journeys have tags from group Y, columns X and Y should be rendered in the table. The value in each cell (row/column, i.e. journey/tag group) should be a list of tags (rendered as pills) from the respective group (can be empty), assigned to that journey.

#### Table requirements
- [x] The static columns should be included in all instances of this table
- [x] Other columns should be generated dynamically from tags/tag groups
- [x] All columns should be filterable and sortable
- [x] Text columns (title, text based value tags) should be searchable
- [ ] Toolbars etc. should be visible

## Possible implementations
Use MUI DataGrid for the table base component.

The final data format is TBD, but will look something like this:

```js
[{
  id: 1,
  title: "My journey",
  summary: "Short text summary describing the case",
  people: [
    { id: 123, first_name: "Clara", last_name: "Zetkin" },
    { id: 456, first_name: "Rosa", last_name: "Luxeburg" },
  ],
  assigned_to: [], // same format as `people`
  created: "1857-07-05T13:37:00.000Z",
  updated: "1933-06-20T13:37:00.000Z",
  next_milestone: {
    title: "Collect evidence",
    deadline: "1933-06-30T13:37:00.000Z",
  },
  tags: [
    { id: 1, title: "Some basic tag", group: null, color: "#ffcc00" },
    { id: 2, title: "A value tag", group: null, color: "#00ff00", value: "This is the value" },
    { id: 3, title: "A grouped tag", group: { id: 1, title: "Group title" }, color: "#ccccff" },
  ]
}]
```

## Design specifications
The full table (with sample data) can be found in Figma:
https://www.figma.com/file/YFXcYN3LUhHghLb0cFqU85/Casework?node-id=1067%3A24310

![image](https://user-images.githubusercontent.com/550212/158751577-d29cec68-ec0a-4c62-b98f-8856d72062d1.png)

## Open questions
* What will the final data format look like?

**Comment by lowlandjuju** [comment]
@richardolsson @djbusstop I know the data model isn't finalised yet, but this part of the spec doesn't feel right to me:

"The page should be at `/organize/{org_id}/journeys/{journey_id}`"

Shouldn't it be something like "journey_type" or "journey_type_id"? I.e. doesn't `journey_id` index a single case, enquiry etc..? 

Assuming the above, then the dynamic routing should surely be according to a string id that is formed from the title of the journey **type** - e.g. `/organize/{org_id}/journeys/cases`.
For multi-word titles, they could be snake- or kebab-cased.
In the abstract: `/organize/{org_id}/journeys/{journey_type}`.

**Comment by richardolsson** [comment]
> @richardolsson @djbusstop I know the data model isn't finalised yet, but this part of the spec doesn't feel right to me:
> 
> "The page should be at `/organize/{org_id}/journeys/{journey_id}`"
> 
> Shouldn't it be something like "journey_type" or "journey_type_id"? I.e. doesn't `journey_id` index a single case, enquiry etc..?

The terminology here can be confusing (because it will probably differ a bit between code and UI), but you are correct that it should be the ID of the journey type/template, which to the user is just called "journey" (which is why I chose the confusing `journey_id` placeholder here).

There was a discussion on Journeys terminology recently on Slack and GitHub that is best documented here: https://github.com/zetkin/app.zetkin.org/issues/574#issuecomment-1072100121

Join in on the terminology discussion on that issue if you want!

> Assuming the above, then the dynamic routing should surely be according to a string id that is formed from the title of the journey **type** - e.g. `/organize/{org_id}/journeys/cases`. For multi-word titles, they could be snake- or kebab-cased. In the abstract: `/organize/{org_id}/journeys/{journey_type}`.

Whether to use a slug instead is a separate question. I had the same idea and would love to see it, but personally I don't think it's the right thing to spend our time on at this point because it would complicate things in the API (or add extra requests from NEXT). If the frontend URL is `cases`, then there will need to be a way to figure out which journey type/template that is, which would either require the API to allow retrieving journey types by slug (which complicates things there) or require NEXT to retrieve all journey types/templates and find the one with the right slug to then use it's ID in the API calls (which complicates things and makes them slower there).

**Comment by lowlandjuju** [comment]
Yeah - it could be something as simple as a slug! It could alse be a separate table with a foreign key index like "journey_types" that has id, label, org_id...
I'll just have to take your word for it that either of these is complicated to implement - this reminds me of some discussion I heard at the Zetkin days that there's an intention to refactor/restructure the platform API so that fewer things present themselves as complicated. 

For now though, if we're going with ids, then it's still unclear to me what IDs are referring to what - so, what are the ids going to be for:

- Individual journeys?
- Journey types (case, enquiry etc...)?

**Comment by lowlandjuju** [comment]
P.S. This is not urgent - I'm just chucking in some hard-code boilerplate for now, which can be extended once the data model and platform routes are in place... @richardolsson

**Comment by richardolsson** [comment]
> Yeah - it could be something as simple as a slug on the journeys table! It could alse be a separate table with a foreign key index like "journey_types" that has id, name/slug, label, org_id... I'll just have to take your word for it that either of these is complicated to implement - this reminds me of some discussion I heard at the Zetkin days that there's an intention to refactor/restructure the platform API so that fewer things present themselves as complicated.

It's not so much that it's very complicated, but it's _more_ complicated than using IDs and I think we need things to be less complicated right now to be able to meet the next release milestone.

> For now though, if we're going with ids, then it's still unclear to me what IDs are referring to what - so, what are the ids going to be for:
> 
> * Individual journeys?
> * Journey types (case, enquiry etc...)?

The ID is for the journey type/template (which in the UI is just called a "Journey"). So your second option above.

**Comment by richardolsson** [comment]
I've updated the dummy data format in the issue to include tags.
