### ISSUE TITLE
Journey assignees & members

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#577]
## Description
A user should be able to add and remove assignees to a case, and do the same with the subjects/members that the case concerns.

## Relevant Job Stories
Unknown

## Prerequisites
Allow #576 to be finished before proceeding with this.

## Requirements
- [x] The journey details view sidebar should have two sections called "Assigned To" and "Members", that work the same but with different aspects of the data:
  - [x] Lists assignees/members
  - [x] Hovering a person should show X, clicking it should unassign
  - [x] Clicking "Add" should show a select box
  - [x] Selecting a person should add them and remove the select box

## Possible implementations
Use `PersonSelect` for adding assignees/subjects.

Relevant API resources:
* Assignees and subjects are listed in the original journey instance resource (`/orgs/{org_id}/journey_instances/{instance_id}`)
* `PUT` or `DELETE` `/orgs/{org_id}/journey_instances/{instance_id}/assignees/{person_id}` to assign/unassign a person to a case
* `PUT` or `DELETE` `/orgs/{org_id}/journey_instances/{instance_id}/subjects/{person_id}` to add/remove a person to a case

### Sidebar
![image](https://user-images.githubusercontent.com/550212/161114212-982f9002-e9a8-4bf1-9c80-c36dc3bacd92.png)

### Adding person
This should show when the user clicks "Add assignee" or "Add member"
![image](https://user-images.githubusercontent.com/550212/161115004-1f4e3030-d9ed-4cfa-be66-bbf7e46656d8.png)

## Open questions
None

**Comment by lowlandjuju** [comment]
Adding designs from figma:

<img width="501" alt="journey members assignees" src="https://user-images.githubusercontent.com/4164774/159872255-a4dc06af-599e-4620-a7b2-72ed15b9918c.png">


<img width="500" alt="journey members" src="https://user-images.githubusercontent.com/4164774/159872284-2f76bc16-7eda-44f5-b094-c5acb461afd4.png">

**Comment by richardolsson** [comment]
I've updated the original issue with additional information.

**Comment by richardolsson** [comment]
I think it would be a very good idea to implement this as a component with callbacks for adding/removing assignees and subjects ("members"), e.g. `<JourneySidebar onAddAssignee={…} onRemoveAssignee={…}/>`

That way, the same component can be used on the page where new journey instances are created (tracked in #580).
