### ISSUE TITLE
Timeline framework components

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#584]
## Description
All timeline events have some common elements, that could probably be implemented using some framework that concrete event types can then live within.

## Relevant Job Stories
See #572 

## Prerequisites
None

## Requirements
- [x] A timeline contains a list of events, separated by lines
- [x] Timeline events should contain an (optional) "actor" – the person who triggered the event
- [x] Timeline events should contain a (rich) text label
- [x] Timeline events should contain a timestamp, rendered as a relative date
- [x] Timeline events can contain complex content

In a future iterations, a timeline event will also have a star button for "bookmarking" and an ellipsis menu for further actions.

## Possible implementations
Use `ZetkinRelativeTime` for timestamp.

The API will return timeline events in a format similar to the one below (details pending), which would be rendered something like "**Clara Zetkin** assigned **Clara Zetkin** yesterday".

```js
{
  name: 'journeyinstance/addassignee',
  actor: {
    id: 123,
    first_name: 'Clara',
    last_name: 'Zetkin',
  },
  timestamp: '2022-02-22T19:17:00.000Z',
  target: {
    id: 1,
    title: "My case",
  },
  details: {
    // Data format varies by type
    assignee: {
      id: 123,
      first_name: 'Clara',
      last_name: 'Zetkin',
    }
  }
}
```

### Events with separators
The event ellipsis menu and star button are not part of this task.

![image](https://user-images.githubusercontent.com/550212/155383045-c450a59c-0dcc-4683-a1ba-1a8ee4b56df0.png)

### Minimal event with only common fields
![image](https://user-images.githubusercontent.com/550212/155380810-83eceee1-7a1d-4daf-aef3-aeb408a86a3b.png)

### Event with complex content
![image](https://user-images.githubusercontent.com/550212/155381226-335cd2bd-6216-40d8-917b-4bcf8bc574e6.png)

## Open questions
None

**Comment by richardolsson** [comment]
I have updated the data format above (very minimally) to more closely match the direction we have taken recently on the backend.

**Comment by lowlandjuju** [comment]
@richardolsson re. the "target" field - would this be a possible reference to any object in any table in the database? Or just journeyinstances?

**Comment by richardolsson** [comment]
> @richardolsson re. the "target" field - would this be a possible reference to any object in any table in the database? Or just journeyinstances?

The `target` is the object that was acted upon, which will always be the prefix in the event name. So in the events we are discussing for this feature, where all events are `journeyinstance/<action>` (e.g. `journeyinstance/addassignee`) the `target` will always be a `JourneyInstance`.

There are nice ways to solve this in TypeScript that we've used elsewhere, so that TS knows based on the `name` property (an `enum`) what the type of the `target` and `details` will be.
