### ISSUE TITLE
Timeline event: Journey summary

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#588]
## Description
A user should be able to see historical changes made to the summary of a journey instance on the timeline of that instance.

## Relevant Job Stories
* When I'm covering for someone else during leave, I want to see the full history of the case so that I know where to pick up
* When a case is handed over to me, I want to be able to find all the necessary information, so that I can have a meaningful conversation with the member and not ask the same questions that have already been answered
* When a member reaches out to ask about the status of their case, I want to be able to easily find it so that I can respond without forwarding to someone else

## Prerequisites
None

## Requirements
- [x] Shows text saying who made the change
- [x] Shows timestamp
- [x] Shows the summary _after the change_
- [x] If the summary is very long (e.g. more than 3-4 lines) shows "expand" button
- [x] Clicking the expand button shows the entire (new) summary

## Possible implementations
From the API point of view, this is a regular update event, and **there could be multiple fields edited in the same event** (although it's unlikely since there will not be a user interface to edit multiple fields in a single request).

The event will look like this:

```ts
{
  type: "journeyinstance.update",
  actor: {
    id: 1,
    first_name: "Clara",
    last_name: "Zetkin",
  },
  target: {
    id: 1,
    title: "A journey instance",
  },
  details: {
    changes: {
      summary_text: {
        from: "The old text",
        to: "The new text",
      },
    },
  },
}
```

## Design specifications
<img width="872" alt="image" src="https://user-images.githubusercontent.com/550212/167096589-a9ec9b3e-104d-406e-ba1f-af49c8100379.png">

## Open questions
None

**Comment by lowlandjuju** [comment]
![journey summary](https://user-images.githubusercontent.com/4164774/159873472-a376308a-2514-43ee-8af3-3b4c88afa7fb.png)

**Comment by richardolsson** [comment]
I have updated the issue with up to date screenshot and other information including API data format.
