### ISSUE TITLE
Adding file attachments to timeline notes

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#592]
## Description
A user should be able to upload file attachments to notes. This could be used for things like contracts, payslips etc during union casework, or assignments during training programs.

## Relevant Job Stories
* When I’m handing over a case to legal staff, I want to upload relevant e-mails and have them appear in the timeline, so that I don’t have to copy-paste their content and so that all meta-data is available too
* When a case is handed over to me, I want to be able to find all the necessary information, so that I can have a meaningful conversation with the member and not ask the same questions that have already been answered

## Prerequisites
Don't start working on this until:

* Basic text notes, #591 have been implemented
* The Zetkin API has been extended to support file uploads

Also see #594, which requires similar file upload functionality.

## Requirements
- [ ] Clicking the note editor "attachment" icon should open browser file select to pick files to attach
- [ ] Dragging and dropping one or more files onto note editor should attach files
- [ ] Attached files should be listed
- [ ] E-mail files should be rendered as a preview

## Possible implementations
In Gen2 I think we used [`react-dropzone`](https://www.npmjs.com/package/react-dropzone) which worked very well.

## Design specifications
<img width="560" alt="image" src="https://user-images.githubusercontent.com/550212/154840925-8393803a-e292-4163-8084-5c949cc348ec.png">

## Open questions
Should we allow multiple files per note? I think so, but it will need to be decided on the backend.

**Comment by richardolsson** [comment]
I think it would be cool to create a general purpose component for this that would have an interface along these lines:

```tsx
<ZetkinFileDrop maxFileCount={ 10 }>
  { ({ isDraggingOver, files, selectFiles }) => {
    return (
      <>
        <RichTextEditor
          content={contentFromState}
          onClickAttachmentIcon={ () => selectFiles() }
        />
        <ul className="attachments">
          {files.map(file => (
            <li>{ file.name }</li>
          ))}
        </ul>
      </>
    );
  }}
</ZetkinFileDrop>
```

In another context (e.g. #594) the content of `ZetkinFileDrop` might instead be a preview of the uploaded image, rather than an editor like the one above.

**Comment by richardolsson** [comment]
Files of type "email" can have their contents rendered using the `<PrettyEmail>` component introduced in #661.

**Comment by richardolsson** [comment]
Nice work on that! I don't think the previews are necessary in the editor, but other than that I like it (i.e. the loading state etc).

I think I understand the implementation your suggesting and I think it's a good option. Another option that I would explore if I'm the one building this would be to build a reusable hook that returns the necessary functions and variables, some of which could then be passed to this renderer component.

**Comment by lowlandjuju** [comment]
I also would use hooks for this :+1:

**Comment by lowlandjuju** [comment]
> Nice work on that! I don't think the previews are necessary in the editor, but other than that I like it (i.e. the loading state etc)

If there's been some decision to change the spec, then I think the description of this issue needs to be updated, because currently it says: "E-mail files should be rendered as a preview"
 ¯\_(ツ)_/¯ 


> I think I understand the implementation your suggesting and I think it's a good option. Another option that I would explore if I'm the one building this would be to build a reusable hook that returns the necessary functions and variables, some of which could then be passed to this renderer component.

**Comment by richardolsson** [comment]
> > Nice work on that! I don't think the previews are necessary in the editor, but other than that I like it (i.e. the loading state etc)
> 
> If there's been some decision to change the spec, then I think the description of this issue needs to be updated, because currently it says: "E-mail files should be rendered as a preview" ¯_(ツ)_/¯

It's clear to me now that this issue assumes knowledge of the background process and the designs, because that point about rendering e-mails as previews is referring to when the file is rendered on the timeline, at which point e-mails (and e-mails only) have special rendering. Like this:

<img width="598" alt="image" src="https://user-images.githubusercontent.com/550212/170544647-a3e8fda7-b43e-4793-99ec-b00c125adaa9.png">
