### ISSUE TITLE
Task images

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#594]
## Description
A user should be able to upload an image to use as the "cover image" of a task.

## Relevant Job Stories
* When I'm creating a task to be assigned to activists, I want to add an image that illustrates the task, so that the task looks less boring when displayed alongside a long list of other tasks

## Prerequisites
Do not start this until file upload support has been added to the API.

## Requirements
- [ ] User should be able to upload a file to be added to the task
  - [ ] …using click and select a file
  - [ ] …using drag and drop
- [ ] Only basic web formats should be allowed, i.e. JPG and PNG

## Possible implementations
In Gen2 I think we used [`react-dropzone`](https://www.npmjs.com/package/react-dropzone) which worked very well.

## Design specifications
(Put any links to wireframes, figma, or other designs here etc here.)

## Open questions
None

**Comment by GemCopeland** [comment]
Hey @richardolsson, working on this now. Could you send me a screenshot of what the task page currently looks like? Did you end up going with the "task preview" card in the right column?

**Comment by richardolsson** [comment]
This is what it looks like right now. I was going to rework it to be more "step by step" instead of one huge modal to create it and then another huge modal to edit it. But we couldn't prioritize that since this (barely) works.

I think the preview card was a nice idea that could make a return if that makes sense in the design for the task image feature.

![image](https://user-images.githubusercontent.com/550212/164047728-18a32f4a-b305-4410-af81-5148bf6d3669.png)

**Comment by GemCopeland** [comment]
So I've updated the task page design to match what we did with Journeys:
![Task](https://user-images.githubusercontent.com/2996847/164271965-559b3f0e-1056-46c3-9b6f-b7056e3e8ee6.jpg)

And this is what the page would look like with edit mode on:
![Edit Task](https://user-images.githubusercontent.com/2996847/164272030-66f5054e-aaef-47a2-a16d-cb266f1676d1.jpg)

**Comment by richardolsson** [comment]
> So I've updated the task page design to match what we did with Journeys

I think this is a good option to be considered in a future revamp, but at the same time I'm not sure what you mean, because I don't understand how this matches Journeys. For journeys we have fields that are edited in place, e.g. summary (with a button next to the field). The top-right action button for journeys is never "edit", but open/close.

I think implementing this change to the task form will be a lot of work, and unless I'm mistaken it will not leave us in a state that is more consistent, because this would be yet another way that objects are edited.

I think this emphasizes the need for a deliberate look all create/edit flows to find consistent patterns that we can use throughout. We planned that for R33 (June/July development), so we should probably start looking at that quite soon. I'll start a discussion!

In the meantime, in the interest of not adding too much work to R32, I think it would be good to solve this issue in a way that does not require a revamp of the task interface in general.

Maybe we could use the file upload widget you have designed, and put it as an item in the existing list of properties in the current UI, except it's always editable (while the other fields are currently editable in a modal)?

Or maybe we could create a special modal just for image uploads (since that's something that we'll want to use in more places) and show the image in the property list, but with a button to edit the image specifically and open the special modal for that?

**Comment by GemCopeland** [comment]
> I think this is a good option to be considered in a future revamp, but at the same time I'm not sure what you mean, because I don't understand how this matches Journeys. For journeys we have fields that are edited in place, e.g. summary (with a button next to the field). The top-right action button for journeys is never "edit", but open/close.

Sorry for the confusion! I meant the [Journey "template"](https://www.figma.com/file/D4PrAup54f3vS4apqY3M7U/Journeys-MVP?node-id=1606%3A21859) editing interface.

But yes, I understand what you mean about not making it too different from the current build for now.

Will make a new version now.

**Comment by GemCopeland** [comment]
Don't all of those work when you click the "Not set" text? This is what I assumed, and so the image upload would have the same behaviour.

**Comment by niklasva82** [comment]
Alright, so basically, the API interactions here will be to upload with POST orgs/{org_id}/files, and then set the task cover id with a PATCH to orgs/{org_id}/tasks/{task_id}.

@richardolsson  we were discussing the possibility of selecting already uploaded files, i.e. a file "library", but I suppose that will have to come at a later stage?
