### ISSUE TITLE
Person hover card

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#614]
## Description
A user should be able to hover a "person" in various parts of the UI and get basic information about that person on a floating card on top of the UI.

## Relevant Job Stories
From the union casework project, related to being able to see a person's tags from different parts of the system:

* When I receive a complaint or enquiry from someone, I want to be able to see whether they are an eligible member, so that I can take the correct action
* When I'm assessing whether a member is eligible, I want to be able to easily see whether they're up to date with their payments, so that I don't have to look into their payment history to figure that out

## Prerequisites
Don't start this until #608 has been completed.

## Requirements
- [x] There should be a component that can be reused for "person hover cards"
- [x] Hovering certain references to people should open the card
- [x] The card should contain the avatar of the person
- [x] The card should contain the name of the person
- [x] The card should list the person's tags without grouping
- [x] The card should show the phone number(s) and e-mail address of the person

## Possible implementations
I'm thinking we can create a component `<PersonPopover>` that's used like this, maybe?

```tsx
<PersonPopover personId={somePerson.id}>
  <Box>Something</Box>
</PersonPopover>
```

Hovering the box would then result in the popover being displayed. The component could then be used as a wrapper for anything, not just a plain box like in the example.

A good place to implement this is for the avatars in a view avatar column.

## Design specifications
See comment below, with the following notes:

* Let's use the left hand card design
* The subtitle under a person's name cannot be implemented in this version

## Open questions
None

**Comment by lowlandjuju** [comment]
Adding what I think is the correct view from the Figma.

<img width="669" alt="Screenshot 2022-03-24 09 10 45" src="https://user-images.githubusercontent.com/4164774/159871471-5067beba-cf9b-4b87-8494-b0fd985cffba.png">
