### ISSUE TITLE
Person detail view doesn't 404 when id points to nonexistent person

### ISSUE THREAD

**Issue by djbusstop** [zetkin/app.zetkin.org#618]
### Description
`organize/1/people/somevalue` loads a broken person page. I think because it tries to fetch a user which doesn't exist, but still tries to render the content when it should 404.

### Expected Behaviour
Shows 404

### Actual Behaviour
Shows this:
![did i do this](https://user-images.githubusercontent.com/41007222/158872740-8091b9d6-c34d-4e79-9a63-e1a0af3c168d.png)

### Proposed solution
In `getServerSideProps`, fetch the person that's id is in the url. If there is no person with that id, return not found.  I took a brief look and this may be the current implementation, so this proposed solution may not work

**Comment by richardolsson** [comment]
Having looked into this more closely, this works for most values, but not for the special value `views`. When the ID is `views`, the backend will try to fetch `/orgs/1/people/views` (as if `views` was a person ID), and that's actually a valid API route which returns a list of views.

So I think the best way to solve this is to handle the special value `views` separately, and redirect from `/organize/1/people/views` to  `/organize/1/people`.
