### ISSUE TITLE
Style JourneyInstance page

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#634]
### Description
The summary field of the single journey page is not styled in line with the wireframe. 
Both places that show milestones need to not render next &/or last milestone if there is none
Padding between summary and Timeline

### Requirements
- [ ] add "cancel" functionality to summary
- [ ] change summary style to look like the wireframe
- [ ] conditionally render milestone last/next descriptions.
- [ ] look at margins/padding between timeline and summary components.

### Design specifications
![bild](https://user-images.githubusercontent.com/58265097/164170821-2dacea45-f73b-459a-b768-989c5a33073d.png)

**Comment by richardolsson** [comment]
I think this is no longer relevant. I believe everything was fixed as part of #666 (or elsewhere). Correct me if I'm wrong, @ziggabyte, and please reopen.
