### ISSUE TITLE
All buttons are now bold, including view toolbar, search button etc

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#676]
Since (I think) #642 the labels of all buttons site-wide have become bold. That's correct for most buttons, but not for all:

- [x] Search button in header should not be bold (actually it should have no label at all)
- [x] Buttons in person View toolbars should not be bold
- [x] Buttons in journey listing toolbars should not be bold

**Comment by ziggabyte** [comment]
![bild](https://user-images.githubusercontent.com/58265097/170958312-5a32a149-e62e-4cbb-951a-b3d2dac1c6f8.png)
Should both of these types of buttons be not-bold? Or just one of them? In the figma i can't find the one that is "add tag" or "start new journey", but the "edit" one is some kind of in between bold and normal? @richardolsson @djbusstop
