### ISSUE TITLE
Avoid confusion about opening note / summary

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#681]
## Description
There is confusion concerning the summary vs the closing note, and there are some steps we can take to remedy that.

The opening note is what a user enters when they create a case, and it contains the description of the background of why the case is opened. The opening note shows up in the beginning of the timeline, and never changes.

The summary is a very brief written summary of the current state of the case, which is always displayed at the top (and in the list) and can be updated at any time. When it is updated, those updates show up in the timeline as well.

The problem that is causing confusion is that the field where the opening note is entered when creating a journey instance (http://localhost:3000/organize/1/journeys/1/new) is in the same location as the summary on the instance page after creation (http://localhost:3000/organize/1/journeys/1/1) and not clearly distinguished.

## Relevant Job Stories
* When I'm looking up a case, I want a brief written summary, so that I know the gist of what the case is about
* When the summary of a case no longer correctly reflects the case, I want to be able to update it so that it correctly describes the case
* Whenever a member fills out the contact form on the UVW website, I want to be able to see that enquiry in the system.

## Prerequisites
None

## Requirements
- [x] On the journey instance page, add a placeholder for the summary field (which is empty when the instance is created) saying something like "Enter a brief summary to describe the `{journey.singular_label}`."
- [x] On the "new" page, add a headline above the textarea saying "Opening note"

## Possible implementations
None

## Design specifications
None

## Open questions
None

**Comment by ziggabyte** [comment]
Thinking about this potential confusion, has it been discussed to use the term "status" insted of summary? Given the placeholder, imo what we are asking is for people to describe the status of the case/onboarding/etc ?
