### ISSUE TITLE
Render markdown in journey instance opening notes

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#721]
Let's use `marked()` when rendering the text in the `opening_note` on the timeline.

Or, since we're starting to have so many instances of `marked` now, maybe we could create a component that takes a `markdown` property, converts it to HTML with `marked()` and passes that to `CleanHtml`?

**Comment by richardolsson** [comment]
This didn't fix the core problem, which was that newlines are not being rendered as breaks in the output. Could you look into that, @ziggabyte?

Here's a screenshot. Look at the `\n` newlines and how they get stripped somehow in the rendered output. They should become `<br/>` and I expected `marked()` to do that. Maybe there's an option for `marked`. Actually, I think there is!

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/550212/171854356-03374b9e-7c6b-4f6a-8b0e-e6dd0cd899e1.png">

**Comment by ziggabyte** [comment]
I'm on it @richardolsson  :D
