### ISSUE TITLE
Values in the "created" column in the journey instance table does not have a tooltip, the way other date columns do.

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#730]
## Description
Not all date columns in the journey instance table show dates consistently. 

## Steps to reproduce
1. Go to http://localhost:3000/organize/7/journeys/6
2. Scroll until you see the "Last updated" column
3. Scroll until you see the "Created" column

### Expected Behaviour
Both should use the same format (a relative time, like the "Last updated" column does)

### Actual Behaviour
The "created" column uses a timestamp format instead.

## Screenshots
![image](https://user-images.githubusercontent.com/550212/227782659-b17bb9b3-6fba-4ded-bff9-4b9b772357ec.png)

## Proposed solution
Use `<ZUIRelativeTime>` in the _Created_ column (same as _Last updated_) which has tooltip builtin.

**Comment by richardolsson** [comment]
Example: http://app.dev.zetkin.org/organize/7/journeys/6

**Comment by richardolsson** [comment]
New name of component: `<ZUIRelativeTime>`, I think!

**Comment by dothelooping** [comment]
Tooltip should be time relative today and Created? But should'nt it be shown in local date format?

**Comment by richardolsson** [comment]
> Tooltip should be time relative today and Created? But should'nt it be shown in local date format?

I expect the `<ZUIRelativeTime>` component to handle localization, so using it should be enough for you to resolve this task, @dothelooping
