### ISSUE TITLE
Outcome value tags does not display value.

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#797]
## Description
When adding a value tag to an open journey instance, the value is displayed. It also works correctly when adding a value tag to an already closed journey instance. But when adding a value tag as an outcome tag, only the tag name and not the value gets displayed. 

## Steps to reproduce
1. Go to journey instance
2. Click on Close
3. Create a value tag as an outcome tag
4. give the value tag a value
5. look at the tag in the timeline note and the tags in the sidebar

### Expected Behaviour
Outcome value tag displays the value assigned to it upon creation.

### Actual Behaviour
Outcome value tag does not display value.

## Screenshots
![bild](https://user-images.githubusercontent.com/58265097/186370880-0d2b9673-b89f-41ce-bb4c-c1b3e92e838a.png)

**Comment by Jrende** [comment]
I'm on the case of the missing display value
