### ISSUE TITLE
Missing translation on confirm dialog on 404 page

### ISSUE THREAD

**Issue by Bagera** [zetkin/app.zetkin.org#802]
## Description

Warnings for missing confirm dialog translations on 404 pages.

Missing translation warnings are:

- misc.ConfirmDialog.defaultTitle
- misc.ConfirmDialog.defaultWarningText
- misc.ConfirmDialog.button

## Steps to reproduce
1. Go to http://localhost:3000/organize

## Screenshots (if you have any)
![image](https://user-images.githubusercontent.com/2950171/187688550-506936ea-75a5-43f7-a0cf-4c31d56ff082.png)

**Comment by ziggabyte** [comment]
We have changed how we handle translations, making this bug no longer relevant.
