### ISSUE TITLE
Rewrite Jest tests to use createRoot

### ISSUE THREAD

**Issue by Bagera** [zetkin/app.zetkin.org#807]
## Description
ReactDOM.render is no longer supported in React 18 and we should be using createRoot instead. Jest will be running in a React 17 compatible mode until we change this.

Documentation on the issue: https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis

**Comment by ziggabyte** [comment]
This solved itself.
