### ISSUE TITLE
EPIC: Call Assignment overview & targeting

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#820]
The Call Assignments feature is a re-vamped and improved version of the existing Call Assignment interface. 

## Definitions of key terminology
* **CALL ASSIGNMENT** is part of a campaign, a process organizing **callers** to call **targets** to gather data, have conversations or whatever supports the need of the campaign.
* **TARGET** is someone who is going to be called or have been called.
* **TARGETING** is the process of defining the **target group**
* **TARGET GROUP** is the defined group of targets to call
* **CALLER** is a person assigned to call the targets

## Target audience
These are the roles that will most likely use this feature:

* Organizers working on a campaign  who use call assignments to move the campaign forward

## Requirements (job stories)
Below are job stories that describe the requirements for this feature.

### Need to have
- When I’m planning a call assignment, I want to define a target group so that Zetkin will show my callers the right people to call
- When I’m defining a target group, I want to be able to make it dynamic so that targets are automatically added and removed and will be called when the right criteria are filled as I define them
- When I’m defining a target group, I want to use Smart Search so that I can reuse my knowledge from other parts of Zetkin
- When I’m targeting a call assignment, I want to be able to define a dynamic definition of “done”, so that targets who are done can be automatically lifted out of the queue
- When I’m allocating resources for a call assignment, I want to know how many targets are left to call, so that I can assess how many callers are needed
- When I’m managing callers, I want to see which call assignments have targets ready to call, so that I can choose which assignment to assign the callers to at this moment
- When I’m managing callers, I want to see how many targets are ready to be called in an assignment, so that I can assess how many callers to assign for the next unit of time
- When a caller tells me the call queue has dried up, I want to be able to see the reason, so I can decide whether to reassign the callers, retarget the assignment, or take any other action
- When the call queue runs dry, I want to be able to see how many targets are on cooldown and might be added back to the queue later, so that I can decide whether to wait a short while or reassign the caller to another assignment
- When the call queue runs dry, I want to be able to see how many targets have been excluded because they are lacking phone numbers, so I can decide whether to focus effort on finding their phone numbers
- When the call queue runs dry, I want to be able to see how many targets have been excluded because they have flagged calls in need of organizer action, so I can decide whether to prioritize sifting through them
- When the call queue runs dry, I want to be able to see how big a portion of the target group is “done”, so that I can decide whether the empty queue is a problem or a sign of success
- When there are targets who are blocked because of missing numbers, I want to be able to see a list of them so that I can initiate a process to find and enter their numbers
- When the call queue runs dry, I want to be able to see how many targets were allocated (and not released) by inactive callers during previous sessions, so that I can free them up to be called
- When there are targets who are blocked because of previous flagged calls in need of organizer action, I want to be able to see a list of the flagged calls so that I can take action
- When the call queue runs dry, I want to be able to change targeting, so that more targets can be added to the queue and my callers keep calling
- When I’m editing the targeting of an assignment, I want ~instant~ quick feedback on what effects the changes have on the queue, so that I can decide whether the change is worth keeping
- When I return to a call assignment, I want to be able to easily see whether the target group is dynamic, so that I can know whether to expect it to change over time
- When I’ve created a call assignment I want a default definition of Done created for me automatically
- When I’m worried about the same target being hammered by calls, I want to be able to configure a minimum wait time between calls, so that I don’t have to worry
When I run out of targets in the queue, I want to be able to quickly reconfigure the minimum wait time between calls, so that targets who were called recently can be released back onto the queue

### Nice to have / known future improvements
- When I’m creating my first call assignments, I want help defining the targeting so that I don’t have to do it from scratch
- When I’m creating a call assignment, I want to be able to choose from common configurations, so that I can get to calling quickly
- When I’m targeting a call assignment from scratch, I want to be guided through the process so that I learn and become a more efficient Zetkin user and a better organizer
- When I make a common mistake in targeting (e.g. configuring the target group to exclude people that we’ve tried a couple of times, instead of doing so in the “done” definition) I want to be warned so that I can assess whether this is really the right thing for my use case

## Solution
Targeting will go on the call assignment "overview" screen.

## Tasks
- [x] #821 
- [x] #822 
- [x] #824 
- [x] #844 
- [x] #857

**Comment by richardolsson** [comment]
All tasks resolved! 💯

**Comment by richardolsson** [comment]
"Done" done!
