### ISSUE TITLE
Call assignment targeting status bar

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#821]
## Description
A user should be able to see a visualisation of the distribution of targets that are blocked, ready and done.

## Relevant Job Stories
- When I’m allocating resources for a call assignment, I want to know how many targets are left to call, so that I can assess how many callers are needed
- When I’m managing callers, I want to see which call assignments have targets ready to call, so that I can choose which assignment to assign the callers to at this moment
- When the call queue runs dry, I want to be able to see how many targets are on cooldown and might be added back to the queue later, so that I can decide whether to wait a short while or reassign the caller to another assignment
- When the call queue runs dry, I want to be able to see how big a portion of the target group is “done”, so that I can decide whether the empty queue is a problem or a sign of success
- When I’m editing the targeting of an assignment, I want ~instant~ quick feedback on what effects the changes have on the queue, so that I can decide whether the change is worth keeping

## Requirements
- [ ] Shows distribution of targets that are blocked, ready and done.
- [ ] When no target group has been created, shows a grey status bar in three equal parts

## Design specifications
![bild](https://user-images.githubusercontent.com/58265097/198537595-5f612dc6-77de-48be-8691-d4d15b546dc8.png)

![bild](https://user-images.githubusercontent.com/58265097/198246142-5bc570a3-b3b4-417f-90aa-80b2231ff37c.png)

**Comment by richardolsson** [comment]
Resolved by #826
