### ISSUE TITLE
Call assignment targeting status sections

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#822]
## Description
A user should be able to see how many targets are blocked, why they are blocked, and have the option to act on it.

## Relevant Job Stories
When the call queue runs dry, I want to be able to see how many targets have been excluded because they have flagged calls in need of organizer action, so I can decide whether to prioritize sifting through them
When the call queue runs dry, I want to be able to see how many targets have been excluded because they are lacking phone numbers, so I can decide whether to focus effort on finding their phone numbers
When the call queue runs dry, I want to be able to see how many targets are on cooldown and might be added back to the queue later, so that I can decide whether to wait a short while or reassign the caller to another assignment
When a caller tells me the call queue has dried up, I want to be able to see the reason, so I can decide whether to reassign the callers, retarget the assignment, or take any other action
When I’m allocating resources for a call assignment, I want to know how many targets are left to call, so that I can assess how many callers are needed
When I’m managing callers, I want to see how many targets are ready to be called in an assignment, so that I can assess how many callers to assign for the next unit of time
When the call queue runs dry, I want to be able to see how big a portion of the target group is “done”, so that I can decide whether the empty queue is a problem or a sign of success

## Requirements
- [ ] shows total number of blocked targets
- [ ] shows number of targets on cooldown
- [ ] shows how many hours cooldown is set to be
- [ ] shows number of targets missing phone number
- [ ] shows number of targets in need of organizer action
- [ ] shows total number of ready targets
- [ ] shows number of targets in queue
- [ ] shows number of targets allocated to caller
- [ ] shows total number of done targets
- [ ] When there is no targeting defined yet, these sections also need to be able to display no numbers, with slightly different styling.

## Design specifications
![bild](https://user-images.githubusercontent.com/58265097/198528451-3831c0c4-8b6d-45ab-adc1-2d0af133b7d5.png)

![bild](https://user-images.githubusercontent.com/58265097/198328429-868a2076-05dc-4b42-a7e3-7990d855f843.png)

**Comment by richardolsson** [comment]
When there is no targeting defined yet, these sections also need to be able to display no numbers, with slightly different styling.

**Comment by richardolsson** [comment]
Resolved by #834
