### ISSUE TITLE
Call assignment targeting targets section

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#824]
## Description
A user should be able to define a target group for the call assignment and edit that target group. A user should also be able to see a representation of the smart search filters used to create the target group.

## Relevant Job Stories
- When I’m planning a call assignment, I want to define a target group so that Zetkin will show my callers the right people to call
- When I’m editing the targeting of an assignment, I want ~instant~ quick feedback on what effects the changes have on the queue, so that I can decide whether the change is worth keeping
- When I return to a call assignment, I want to be able to easily see whether the target group is dynamic, so that I can know whether to expect it to change over time
- When the call queue runs dry, I want to be able to change targeting, so that more targets can be added to the queue and my callers keep calling
- When I’m defining a target group, I want to be able to make it dynamic so that targets are automatically added and removed and will be called when the right criteria are filled as I define them
- When I’m defining a target group, I want to use Smart Search so that I can reuse my knowledge from other parts of Zetkin

## Prerequisites
- Design of how the pictogram should look/work

## Requirements
- [x] Shows number of targets
- [ ] Shows a representation of the smart search filters used to create target
- [x] Lets user create and edit target group
- [x] If no target group has been created it shows no number and different interface.

## Design specifications
![bild](https://user-images.githubusercontent.com/58265097/198330505-ccc19674-c4a7-44f3-97c1-293f2d3f3d82.png)
![bild](https://user-images.githubusercontent.com/58265097/198330590-50316267-7626-4a8e-917c-c126b491aa36.png)

## Open questions
How should the pictogram look/work?

**Comment by richardolsson** [comment]
Solved by #848
