### ISSUE TITLE
EPIC: Call Assignment caller configuration

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#827]
Please add a high-level description here, then fill out the sections below

## Definitions of key terminology
* **CALL ASSIGNMENT** is part of a campaign, a process organizing **callers** to call **targets** to gather data, have conversations or whatever supports the need of the campaign.
* **TARGET** is someone who is going to be called or have been called.
* **CALLER** is a person assigned to call the targets

## Target audience
These are the roles that will most likely use this feature:

* Call assignment organizers

## Requirements (job stories)
Below are job stories that describe the requirements for this feature.

### Need to have
- When I know the callers beforehand, I want to be able to add callers right away, so that I’m prepared when the calling is set to start
- When a caller shows up to a phone bank spontaneously, I want to be able to add them  as a caller to the assignment quickly, so that I don’t lose important calling time
- When I’m managing a phone bank remotely and a new caller reaches out to me, I want to be able to add them as a caller from my phone, so that they can start calling before I get back to my computer
- When a caller is especially well suited to talk to a certain group of targets, I want to pick tags to prioritize for that caller, so that targets with those tags will be allocated before others
- When I prefer a certain caller to not call a some part of the target group, I want to pick tags to exclude from that caller’s queue, so that targets with those tags can be called by other callers
- When a caller has done their last session on an assignment, I want to be able to remove them from the assignment, so that they can no longer access the information in it
- When I’m organizing events and actions as part of a campaign, I want to delegate largs-scale direct contact over the phone to caller volunteers, so that I can mobilize more people to the events

### Nice to have / known future improvements
None

## Solution
Callers tab (incorrectly indicated as "Overview" tab in screenshot below) with UI to manage callers.
![image](https://user-images.githubusercontent.com/550212/201303397-6b923141-c296-4ad5-af32-83dc5e0657d2.png)

## Tasks
- #828 
- #829
- #830
- #831

**Comment by ziggabyte** [comment]
Needs design: an "inactive state" when there are no callers added to the call assignment.

**Comment by ziggabyte** [comment]
To be implemented: sorting/filtering etc of the columns
