### ISSUE TITLE
Call Assignment "Callers" tab and list

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#828]
## Description
A user should be able to navigate to see what people have been added as callers to a call assignment.

## Relevant Job Stories
- When I’m organizing events and actions as part of a campaign, I want to delegate largs-scale direct contact over the phone to caller volunteers, so that I can mobilize more people to the events

## Prerequisites
None

## Requirements
- [x] New tab under call assignment, called "Callers"
- [x] Render list of callers, with the following columns
  - [x] Full name
  - [x] Prioritized tags
  - [x] Excluded tags
- [x] Input field to filter callers by name

## Possible implementations
API resources:

* `GET /orgs/ID/call_assignments/ID/callers` to list

## Design specifications
![bild](https://user-images.githubusercontent.com/58265097/204548757-51ece913-354d-4d7e-88aa-677e3a23f423.png)

## Open questions
None

**Comment by ziggabyte** [comment]
@richardolsson @Bagera what part of the design is still TBD? 
https://www.figma.com/file/EjLcpjKWgNizCb5PRBF51P/Zetkin-3?node-id=865%3A11934&t=16RsFdzxIjq7RcMf-4

**Comment by richardolsson** [comment]
> @richardolsson @Bagera what part of the design is still TBD? https://www.figma.com/file/EjLcpjKWgNizCb5PRBF51P/Zetkin-3?node-id=865%3A11934&t=16RsFdzxIjq7RcMf-4

It probably was TBD when I created the issue, but has been designed since without the issue being updated. It should be safe to move on (and maybe update the issue and remove the tag). 🟢
