### ISSUE TITLE
Open-ended date range picker

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#833]
## Description
A user should be able to pick date ranges with optional end dates, which is useful in multiple situation (e.g. call assignments).

## Relevant Job Stories
This is a general purpose component, but an example from the call assignment use case is this:

- When I know beforehand what days we’re phone banking, I want to e able to set the start and end date, so that it automatically opens and closes on the right days
- When I’m planning a call assignment to continue indefinitely, I want to be able to configure it without a close date, so that it doesn’t close until I do so manually

## Prerequisites
None

## Requirements
- [x] When inactive, should render date range as "From X to X" or "From X onwards"
- [x] When clicked, should open a popover where start and (optional) end date can be picked
- [x] It should not be possible to set an end date that occurs before the start date

## Possible implementations
Unknown

## Design specifications
![Image](https://user-images.githubusercontent.com/2950171/202416418-086a196f-3f9f-4985-a7ae-5566ab02bd9e.png)

## Open questions
None

**Comment by Bagera** [comment]
![Image](https://user-images.githubusercontent.com/2950171/202416418-086a196f-3f9f-4985-a7ae-5566ab02bd9e.png)

The "popper" for setting the date.

Requirements say that end date should not be able to be set before start date. Does this mean you cannot set an end date that is before start date as in chronological or as in end date not being available to be set before start date is set.

**Comment by richardolsson** [comment]
Nice! I have updated the issue to reflect the new design, and clarified the requirement to answer your question, @Bagera

**Comment by richardolsson** [comment]
What should happen if the user types a date into the end date input, that precedes the date in the start date input? I.e.:

1. Focus the "Start input"
2. Enter "2022-11-21"
3. Focus the "End input"
4. Enter "2022-11-20"

What should happen? How do we alert the user that the end date can't precede the start date?

**Comment by richardolsson** [comment]
@Bagera Can you answer the questions above (in a comment or by updating the issue) based on your notes from our last discussion on this topic? I can't remember what was decided.

**Comment by richardolsson** [comment]
Updating issue to answer my questions above after talking to @Bagera
