### ISSUE TITLE
Cooldown config UI for call assignments

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#844]
## Description
A user should be able to change the `cooldown` property of call assignments.

## Relevant Job Stories
* When I’m worried about the same target being hammered by calls, I want to be able to configure a minimum wait time between calls, so that I don’t have to worry
* When I run out of targets in the queue, I want to be able to quickly reconfigure the minimum wait time between calls, so that targets who were called recently can be released back onto the queue

## Prerequisites
First solve #822.

## Requirements
- [x] The cooldown should be displayed in the "Called too recently" row of the "Blocked" status section
- [ ] There should be a small cogwheel, that when clicked opens some sort of UI for editing the cooldown (TBD)

## Possible implementations
None

### Location of cogwheel
<img width="547" alt="image" src="https://user-images.githubusercontent.com/550212/201472345-8a765343-570a-415c-aaa3-39b06a7b7efe.png">

### Popper when cogwheel is clicked
![Image](https://user-images.githubusercontent.com/58265097/202417503-1b73a93d-7636-41e9-a94d-e6c0da7fbd2a.png)

## Open questions
None

**Comment by richardolsson** [comment]
@ziggabyte Note that the UI might still change here. @Bagera has designed the popup as a modal, but I think he was suggesting to use a "popper" close to the cogwheel instead.

**Comment by Bagera** [comment]
![Image](https://user-images.githubusercontent.com/2950171/202415799-945851ce-d232-4a6b-a6bf-dcfa48e9bc52.png)

I have made a new popper version. It keeps more in line with the rest.

**Comment by richardolsson** [comment]
This wasn't closed for some reason, but was resolved by #845. 🎉 

Probably wasn't closed because that PR wasn't merged directly into main, but via another branch. Something to look out for in the future.
