### ISSUE TITLE
Handle follow/connect to organization for non-members

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#85]
There's a need to handle the case when a user is not a member of an organization and clicking on follow on this organizations org/events/campaigns page.

Steps to reproduce:

1. Login
2. Go to`/o/5`
3. Click `Follow` or `Följ`

Expected result: Since the development user is not a member of the organization with an id of 5 we expect some sort of message to indicate and handle this.
Actual result: No change in UI that indicates that the user is not a member of said organization.

**Comment by djbusstop** [comment]
`/o/` pages have been deleted. Do we need to keep this issue, since this page will be remade?

**Comment by richardolsson** [comment]
Closing this as the activist-facing pages have not been a priority, and when we do shift focus to them we will want to start that process fresh.
