### ISSUE TITLE
Define call assignment done criteria

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#857]
## Description
A user should be able to edit the done criteria for a call assignment.

## Relevant Job Stories
- When I’ve created a call assignment I want a default definition of Done created for me automatically
- When I’m targeting a call assignment, I want to be able to define a dynamic definition of “done”, so that targets who are done can be automatically lifted out of the queue

## Requirements
- [ ] There is always a default done criteria
- [x] Clicking edit button opens smart search dialog
- [x] Editing the smart search sets done criteria for call assignment

## Design specifications
![bild](https://user-images.githubusercontent.com/58265097/207360806-08abf440-064d-4520-81ed-8f00e6c2650b.png)

## Open questions
Only implement button and not the pictogram (represented in design as a chip with "call hisory")

**Comment by richardolsson** [comment]
Solved 2/3 tasks in #861. The remaining one (concerning default goal query) is not really an aspect of this feature, but related to _creating_ call assignments which we haven't implemented yet.
