### ISSUE TITLE
Errors in `ZUITextEditor`

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#868]
# Description
Lists are not working as expected in the `ZUITextEditor`.

# Steps to reproduce
1. Go to a text editor (e.g. /organize/1/campaigns/standalone/callassignments/1/conversation)
2. Activate text editor
3. Insert a bulleted list
4. Write something in the bullet
5. Press down arrow

## Expected Behaviour
Should go to line below and keep editing

## Actual Behaviour
Throws error

# Screenshots
Error when pressing arrow down in bullet list
![bild](https://user-images.githubusercontent.com/58265097/210392122-0bbeed52-5982-47ce-9241-3828da12dbdf.png)

**Comment by richardolsson** [comment]
I'm going to suggest we postpone this. It does concern an annoying bug, but it isn't a blocker when using the app in production mode.

**Comment by ziggabyte** [comment]
I'm closing this bug, as following these instructions (in Chrome and Firefox) does not reproduce an error.
