### ISSUE TITLE
View cells for each column type.

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#892]
Each column type in views needs its own cell type, so the information is clearly displayed and easy to interact with when possible.

## Definitions of key terminology
* A VIEW is a table where each row represents a person, and the set of columns define what data to display for each person. Views are common within an organization, i.e. all views are available to all officials in that organization.
* A VIEW COLUMN decides what type of data is displayed for each person in the cells of that column. Columns of different type display different kind of data, and further configuration dictates where that data is retrieved from exactly.
* A COLUMN TYPE is the technical type of the column, e.g `local_bool`
* A VIEW CELL decides how how the data for each person in a VIEW COLUMN is displayed. 

## Target audience
* Any user who looks at a view will look at, and interact with, these cells.

## Requirements (job stories)
Below are job stories that describe the requirements for this feature.
* When I have a tag column in a sheet and conditions change, I want to be able to tag/untag people from the sheet, so that I don’t have to navigate away
* When I need columns to display some arbitrary status, I want to be able to define a local Smart Search for that column, so that I can use the power of Smart Search without having to save heaps of standalone queries
* When I’m working a sheet to invite people to some event, I want to be able to record their responses both using arbitrary text and codified, so that I can keep the full information while being able to easily sort/filter
* When I’m assembling a sheet of people to be reached out to, I want to be able to assign people to an organizer, so that several organizers can share the work of reaching out to them
* When I see something misspelled in a sheet, I want to be able to edit it in place so that I can keep working once I’ve corrected it
* When I’m using survey data to identify who to include in a group, I want to group/codify responses that are similar (e.g. profession), so that I can more easily sort and group people with similar conditions together
* When I’m assembling a group based on people in a list, I want to indicate in that list whom I’ve reached out to, so that I don’t contact them more often than necessary
* When I’m working a sheet of people, I want to be able to add free text notes, so that I can keep track of arbitrary information relevant to the task at hand

## Solution
Give each column type its own specific cell typ, to best display the information in the cell.

## Tasks
- [x] #912
- [x] #895 
- [x] #896 
- [x] #898 
- [x] #903 
- [x] #907 
- [x] #908 
- [x] #909
- [x] #910
- [x] #911

**Comment by richardolsson** [comment]
Closing this as all tasks are done.
