### ISSUE TITLE
View cell for Person Field column

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#895]
## Description
The cells in a Person Field column shows the current value (if any) of a single field on the person record (e.g. first name, last name, email, join date etc).

Values can have different types:
Text (e.g. email or name)
URL (e.g. to a profile page in another system), should be clickable
Date (e.g. join date)

Should be interactive, i.e. user should be able to edit to replace the value stored on the person’s record. Editing a string is different from editing a date.

## Relevant Job Stories
* When I see something misspelled in a sheet, I want to be able to edit it in place so that I can keep working once I’ve corrected it

## Requirements
- [ ] Display no value
- [ ] Display string
- [ ] Display URL
- [ ] Display date
- [ ] Editing a cell with no value
- [ ] Editing string
- [ ] Editing URL
- [ ] Editing date

## Possible implementations
- Data grid has editable cells.
- Text and date are already covered by Data grid
- URL can be solved by using string and passing a formatting function the prop valueGetter
- Relative dates can also be achieved with valueGetter
- Use MUI-X Datepicker (https://mui.com/x/react-data-grid/recipes-editing/#usage-with-mui-x-date-pickers)

## Design specifications
https://www.figma.com/file/EjLcpjKWgNizCb5PRBF51P/Zetkin-3?node-id=1976%3A36116&t=ZwOBKqXDfw3cdL7Y-4
![bild](https://user-images.githubusercontent.com/58265097/210759063-7ab5d440-6784-44ce-9d41-c7cf7a3a8584.png)

**Comment by ziggabyte** [comment]
Since the only new feature this would add is editability, and editing in the view will not be part of R37 I'm removing this issue from 37 planning.

**Comment by richardolsson** [comment]
Done
