### ISSUE TITLE
View cell for Local Bool column

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#909]
## Description
A Local Bool column works like a checkbox for users, that they can toggle on/off. The column is local to the view and its data is not saved to the people in the view.

## Relevant Job Stories
- When I’m assembling a group based on people in a list, I want to indicate in that list whom I’ve reached out to, so that I don’t contact them more often than necessary

## Requirements
- [x] Renders a checkbox for each person
- [x] When unchecked, hovering shows ghost of checkmark
- [x] When checked, background is green
- [x] When checked, hovering lightens the checkmark color

## Design specifications
https://www.figma.com/file/EjLcpjKWgNizCb5PRBF51P/Zetkin-3?node-id=2358%3A48595&t=ZwOBKqXDfw3cdL7Y-4
![bild](https://user-images.githubusercontent.com/58265097/210793530-30b59238-e186-4097-9465-e37f0b136cae.png)

**Comment by richardolsson** [comment]
I will take over this and use as much as I can of the stuff @river-bbc built, but within the new framework.
