### ISSUE TITLE
Journey instance milestones tab throws error and does not render

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#916]
## Description
The journey instance milestones tab does not render, but throws error. 
Error messages point at JourneyInstanceLayout and DatePickers. Probably related to MUI5-migration, so might be included in the work on #856 

## Steps to reproduce
1. Go to any journey instance milestones tab, fx http://localhost:3000/organize/1/journeys/1/1/milestones
2. Behold the error message

### Expected Behaviour
Renders milestones tab.

### Actual Behaviour
Throws error.

## Screenshots (if you have any)
![bild](https://user-images.githubusercontent.com/58265097/211809240-c56171c2-ff5f-43a5-8394-d174908fbb68.png)
![bild](https://user-images.githubusercontent.com/58265097/211809311-84b94c0c-6104-480f-a1d7-256f4a482755.png)

**Comment by ziggabyte** [comment]
Creating a task seems to trigger the same error (attempted at http://localhost:3000/organize/1/campaigns/2#create-task)
![Image](https://user-images.githubusercontent.com/58265097/215269286-b793e810-0d07-4d6c-a7a6-203a1a9ed70d.png)

But here it points to the Single Campaign Layout
![Image](https://user-images.githubusercontent.com/58265097/215269318-ca1ef161-be23-4937-b6f4-5065e98a199f.png)

**Comment by richardolsson** [comment]
I can't reproduce this. Are you still getting the error?

**Comment by ziggabyte** [comment]
@richardolsson no! haha! amazing :) it fixed itself! I'll close it!

**Comment by ziggabyte** [comment]
Closing this issue because we can no longer re-produce the bug 😄
