### ISSUE TITLE
TagManager adds tags when they are disabled

### ISSUE THREAD

**Issue by rebecarubio** [zetkin/app.zetkin.org#922]
## Description
TagManager adds over and over a tag when you click it when it's disabled.

## Steps to reproduce
1. Go to 'http://app.dev.zetkin.org/organize/1/campaigns/1/callassignments/1/callers"
2. Click on 'Customize' button
3. Click on '+Add tag'
4. Click on a disabled tag 

### Expected Behaviour
nothing

### Actual Behaviour
Adds the tag if you click it when it's disabled

## Screenshots (if you have any)
![bug](https://user-images.githubusercontent.com/36491300/212918026-45d813d9-e4ac-4072-8180-757b163149e0.png)

**Comment by richardolsson** [comment]
This is being worked on by @theo8theo8 (mentioning here so that I can assign).
