### ISSUE TITLE
Refactor choices to asynchronous.

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#944]
## Description
Make the choices asynchronous and load before the choices render, so we can fetch data first and use to calculate what columns are already in the view, if the organisation has surveys etc. 

## Requirements
- [ ] Requirement 1

## Design specifications
(Put any links to wireframes, figma, or other designs here etc here.)

**Comment by richardolsson** [comment]
Based on the keyword "choices" I believe this to be related to the view column dialog. But because of the lack of information, and the fact that it is technical rather than UX, I am going to close this and if it's really an issue we will rediscover it and create a better issue.
