### ISSUE TITLE
Streamline & categorise column choices

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#958]
- names
- descriptions
- logos
- categories

**Comment by richardolsson** [comment]
Here's a proposal for how to categorize the choices to be discussed in the coming days.

## Categories
The headlines are rough ideas for category titles, and the _italic text_ below each headline is a suggestion for the category intro text.

### Basic information
_Simple fields of information about people._
- Full name (renamed from "First and Last name")
- First name (NEW, `person_field`, no config)
- Last name (NEW, `person_field`, no config)
- Email (NEW, `person_field`, no config)
- Phone (NEW, `person_field`, no config)
- Pick fields (renamed from "Person fields")

### Categorizing
_For grouping, categorizing or shortlisting people, arbitrarily or based on data in Zetkin._
- Tags
- Custom Cross-reference (Renamed from "Smart Search")
- Toggle

### Cross-referencing
_Cross-reference with data in Zetkin using Smart Search._
- Ever spoken to (NEW, `local_query`, no config)
- Ever participated (NEW, `local_query`, no config)
- Booked in future (NEW, `local_query`, no config)
- Custom Cross-reference

### Surveys
_Explore, search and filter based on people's responses to surveys._
- Submit date
- Survey question
- Many survey questions
- Full survey (NEW, not MVP)

### Outreach
_Plan, delegate and execute outreach work, and report back when you're done._
- Assigned person
- Toggle
- Notes
- Delegate

### Utility
_Trusty columns that you'll want to reuse in most situations_
- Notes
- Assigned person
- Toggle
- Follow-up

## Summary of new choices
* "Full survey" would require a new config interface, but be basically the same as "survey questions (plural)" except create columns for all of the questions once you pick a survey
* "First name", "Last name", "E-mail", "Phone" would just be shortcuts that create the respective `person_field` column
* "Ever spoken to", "Ever participated", "Booked in future" would just be shortcuts that create `local_query` columns with pre-defined filters

## Other thoughts
* I was thinking about having a category for "columns that outside collaborators can edit", but then I realized maybe that should be a separate dimension from category. Maybe it should be a boolean on the choice spec, and an icon on the card could indicate it? Maybe both?

**Comment by richardolsson** [comment]
We discussed this at today's meeting and it was approved, but with the addition that "Outreach" should also contain the email and phone fields.
