### ISSUE TITLE
CSS breaking when editing call assignment instructions

### ISSUE THREAD

**Issue by yusf** [zetkin/app.zetkin.org#970]
**Please be as thorough as possible, but if you can't answer everything, please just submit what you have! Thank you!**

## Description
When editing call assignment instructions the CSS immediately breaks.
- CA title gets clipped
- typeface changes to Roboto
- various margins changes 

## Steps to reproduce
1. Go to http://app.dev.zetkin.org/organize/1/campaigns/1/callassignments/1/conversation
2. Edit the instructions

### Expected Behaviour
CSS stays consistent

### Actual Behaviour
CSS get inconsistent

## Screenshots (if you have any)

https://user-images.githubusercontent.com/346211/217181526-65015b3c-1723-428d-aff0-4c0a81040b5a.mov

**Comment by theo8theo8** [comment]
Correct me if I am wrong, but this issue does not seem to be present any more.

**Comment by richardolsson** [comment]
I think you might be right. It seems likely that it was fixed by #1118.
