### ISSUE TITLE
Survey basic stats in header

### ISSUE THREAD

**Issue by rebecarubio** [zetkin/app.zetkin.org#989]
## Description
A user should be able to check the basic stats(questions, submissions) in the header of the survey

## Relevant Job Stories
None

## Prerequisites
Don't start until #982 is done

## Requirements
- [x] Add questions icon in survey header ("QuizOutlined")
- [ ] Add submissions icon in survey header ("ChatBubbleOutlineFilled")
- [ ] Hide the entire stat, including icon and label when a stat has the value 0.
- [ ] _to be confirmed the expected functionality of those_ 

## Possible implementations
None

## Design specifications

![Image](https://user-images.githubusercontent.com/346211/218419386-ee1ac013-2bf7-4b7a-8b8a-c7119034d88a.png)

## Open questions
- how is the expected logic of the submissions? is the icon clickable?

**Comment by yusf** [comment]
Made some additions to the issue including question stat and icon names for both
